### ISSUE TITLE
Uninstall incompatible packages: build

### ISSUE THREAD

**Issue by denix190** [platformio/platformio-atom-ide#1010]
Error: Failed to delete build: Does not exist

    at /home/denis/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:139:27
    at /home/denis/.atom/packages/platformio-ide/lib/utils.js:52:7
    at ChildProcess.onExit (/home/denis/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:498:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by ivankravets** [comment]
Just restart IDE
