### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by kimfrellsen** [platformio/platformio-atom-ide#1011]
Error: '"C:\Users\frellsen01\AppData\Local\atom\app-1.21.0\resources\app\apm\bin\apm.cmd"' is not recognized as an internal or external command,
operable program or batch file.

    at file:///C:/Users/frellsen01/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/frellsen01/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please uninstall `platformio-ide` package and install it again
