### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by hwiguna** [platformio/platformio-atom-ide#1015]
Error: Traceback (most recent call last):
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 92, in cli
    init_base_project(project_dir)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 144, in init_base_project
    config = util.load_project_config(project_dir)
  File "/Users/hwiguna/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 345, in load_project_config
    cp.read(path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: /Users/hwiguna/Git_Repositories/HariFun_157_Cube_Final/platformio-examples-develop/espressif/esp8266-webserver/platformio.ini
	[line 16]: 'ESP8266WiFi\n'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please fix /Users/hwiguna/Git_Repositories/HariFun_157_Cube_Final/platformio-examples-develop/espressif/esp8266-webserver/platformio.ini file
