### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by conor-o-brien** [platformio/platformio-atom-ide#1016]
Error: The system cannot find the path specified.
Error: spawn C:\Users\Conor\AppData\Local\atom\app-1.12.9\resources\app\apm\node_modules\atom-package-manager\bin\apm.cmd ENOENT
    at file:///C:/Users/Conor/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at throw (<anonymous>)
    at step (file:///C:/Users/Conor/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please uninstall `platformio-ide` package and install it again
