### ISSUE TITLE
InstallationManager: IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by 0xPIT** [platformio/platformio-atom-ide#1030]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/pit/.platformio/.cache/tmp-80414AQN0wXq0CnXW/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/pit/.platformio/.cache/tmp-80414AQN0wXq0CnXW/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/pit/.platformio/.cache/tmp-80414AQN0wXq0CnXW/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/pit/.platformio/.cache/tmp-80414AQN0wXq0CnXW/virtualenv-14.0.6/virtualenv.py", line 1101, in install_python
    copy_required_modules(home_dir, symlink)
  File "/Users/pit/.platformio/.cache/tmp-80414AQN0wXq0CnXW/virtualenv-14.0.6/virtualenv.py", line 1042, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/Users/pit/.platformio/.cache/tmp-80414AQN0wXq0CnXW/virtualenv-14.0.6/virtualenv.py", line 348, in copyfile
    copyfileordir(src, dest, symlink)
  File "/Users/pit/.platformio/.cache/tmp-80414AQN0wXq0CnXW/virtualenv-14.0.6/virtualenv.py", line 325, in copyfileordir
    shutil.copy2(src, dest)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/pit/.platformio/penv/lib/python2.7/stat.py'

**Comment by ivankravets** [comment]
Could you try?
```
rm -rf ~/.platformio/penv
pip install --user virtualenv
~/Library/Python/2.7/bin/virtualenv ~/.platformio/penv
source ~/.platformio/penv/bin/activate
pip install platformio
```

Does it work?

**Comment by ivankravets** [comment]
Please reopen if you still need help
