### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by antoniogoncalves** [platformio/platformio-atom-ide#1031]
Error: Can not find Python Interpreter
    at PlatformIOCoreStage._callee8$ (C:\Users\Amanda\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2389:23)
    at tryCatch (C:\Users\Amanda\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:780:40)
    at Generator.invoke [as _invoke] (C:\Users\Amanda\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1014:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Amanda\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:832:21)
    at step (C:\Users\Amanda\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1778:191)
    at C:\Users\Amanda\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1778:361
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please install Python 2.7 (not Python 3) manually and restart IDE
- https://www.python.org/downloads/
