### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by aadithyarulez** [platformio/platformio-atom-ide#1037]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: 
    at _callee$ (C:\Users\aadit\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2522:19)
    at tryCatch (C:\Users\aadit\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:780:40)
    at Generator.invoke [as _invoke] (C:\Users\aadit\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1014:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\aadit\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:832:21)
    at step (C:\Users\aadit\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2631:191)
    at C:\Users\aadit\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2631:361

**Comment by ivankravets** [comment]
Please check Internet connection and restart IDE
