### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Tontze** [platformio/platformio-atom-ide#1042]
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /home/tontze/Downloads/Sonoff-Tasmota-5.8.0' is already set
    at Registry.statusAdd (/home/tontze/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /home/tontze/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/home/tontze/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/home/tontze/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/home/tontze/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (/home/tontze/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /home/tontze/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/home/tontze/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide/commit/22127abb693390336a5c0484c8231d4c45f7d619
