### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by pverstraeten** [platformio/platformio-atom-ide#1046]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/peter/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/peter/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Fixed in the latest version. Please upgrade.
