### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by sinoprobe** [platformio/platformio-atom-ide#1050]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: read ECONNRESET
    at _callee$ (/Users/zhangyunfeng/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2522:19)
    at tryCatch (/Users/zhangyunfeng/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:780:40)
    at Generator.invoke [as _invoke] (/Users/zhangyunfeng/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1014:22)
    at Generator.prototype.(anonymous function) [as throw] (/Users/zhangyunfeng/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:832:21)
    at step (/Users/zhangyunfeng/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2631:191)
    at /Users/zhangyunfeng/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2631:402
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please restart IDe and check internet connection.
