### ISSUE TITLE
Some parts of closed terminals remain in UI

### ISSUE THREAD

**Issue by jbbr** [platformio/platformio-atom-ide#107]
PlatformIO-IDE: 1.2.0
Atom: 1.7.3
PlatformIO: 2.9.0
OS: OS X 10.11

I've played around with new PlatformIO packages and switched a lot between Serial monitor and build/upload. Now I have many dead terminal sessions open which can't be closed by clicking on X

![pio_ide_terminals](https://cloud.githubusercontent.com/assets/682607/14901123/2e5d0310-0d94-11e6-9075-67dfb6598c48.png)

When running build during serial monitor session the serial monitor gets closed and reopened again. Maybe auto-closed terminal windows remain opened in a inconsistent state?

EDIT:
When pressing X or the down arrow nothing happens. When pressing the "full-screen" button I get an exception:

```
TypeError: Cannot read property 'element' of undefined
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.adjustHeight (/Users/user/.atom/packages/platformio-ide-terminal/lib/view.coffee:395:16)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.maximize (/Users/user/.atom/packages/platformio-ide-terminal/lib/view.coffee:195:8)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platformio-atom-ide-terminal/issues
