### ISSUE TITLE
InstallationManager: ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by jrlortiz** [platformio/platformio-atom-ide#1074]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\c111327\.platformio\.cache\tmp-8704dPtIx3WkMImB\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\c111327\.platformio\.cache\tmp-8704dPtIx3WkMImB\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\c111327\.platformio\.cache\tmp-8704dPtIx3WkMImB\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\c111327\.platformio\.cache\tmp-8704dPtIx3WkMImB\virtualenv-14.0.6\virtualenv.py", line 834, in install_wheel
    from urllib.parse import urljoin
  File "C:\Python27\Lib\urllib.py", line 26, in <module>
    import socket
  File "C:\Python27\Lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
