### ISSUE TITLE
Uninstall incompatible packages: build

### ISSUE THREAD

**Issue by internetcontact** [platformio/platformio-atom-ide#1081]
Error: Failed to delete build: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Raju\.atom\packages\build\node_modules\editions'

    at file:///C:/Users/Raju/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:139:27
    at file:///C:/Users/Raju/.atom/packages/platformio-ide/lib/utils.js:52:7
    at ChildProcess.onExit (C:\Users\Raju\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:498:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\Raju\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by ivankravets** [comment]
Please remove `C:\Users\Raju.atom\packages\build` folder and restart IDE

**Comment by internetcontact** [comment]
Thanks.
