### ISSUE TITLE
InstallationManager - failure to create venv

### ISSUE THREAD

**Issue by jrial** [platformio/platformio-atom-ide#1084]
Virtualenv Create: Traceback (most recent call last):
  File "/home/nighty/.platformio/.cache/tmp-5271ejMrg0aqMuNB/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/home/nighty/.platformio/.cache/tmp-5271ejMrg0aqMuNB/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/home/nighty/.platformio/.cache/tmp-5271ejMrg0aqMuNB/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/nighty/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/home/nighty/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by jrial** [comment]
Duplicate of many similar issues, closing.
