### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by sim8989** [platformio/platformio-atom-ide#1087]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Szymon Cichy\.platformio\.cache\tmp-12736B8heG2Qt8U7m\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Szymon Cichy\.platformio\.cache\tmp-12736B8heG2Qt8U7m\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Szymon Cichy\.platformio\.cache\tmp-12736B8heG2Qt8U7m\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\Szymon Cichy\.platformio\.cache\tmp-12736B8heG2Qt8U7m\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\Szymon Cichy\.platformio\.cache\tmp-12736B8heG2Qt8U7m\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Odmowa dostepu

**Comment by ivankravets** [comment]
Please check access to `C:\Users\Szymon Cichy.platformio` folder and try to disable antivirus.
