### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by paloliska** [platformio/platformio-atom-ide#1092]
Error: Error: ENOENT: no such file or directory, open 'C:\Users\moro\.atom\packages\platformio-ide\.cache\examples.tar.gz'
    at ProjectExamplesStage.<anonymous> (C:\Users\moro\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:201:15)
    at throw (<anonymous>)
    at step (C:\Users\moro\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Fixed in the latest version. Please upgrade.
