### ISSUE TITLE
InstallationManager: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by ririfonfon** [platformio/platformio-atom-ide#1093]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\ririf\.platformio\.cache\tmp-16396goURPukDTpqg\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\ririf\.platformio\.cache\tmp-16396goURPukDTpqg\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\ririf\.platformio\.cache\tmp-16396goURPukDTpqg\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\ririf\.platformio\.cache\tmp-16396goURPukDTpqg\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\ririf\.platformio\.cache\tmp-16396goURPukDTpqg\virtualenv-14.0.6\virtualenv.py", line 747, in call_subprocess
    "Error %s while executing command %s" % (e, cmd_desc))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 19: ordinal not in range(128)

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
