### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by javigf** [platformio/platformio-atom-ide#1117]
Please manually remove file `/home/tatu/.platformio/.cache`
Error: Traceback (most recent call last):
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 74, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 44, in on_platformio_start
    after_upgrade(ctx)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 188, in after_upgrade
    app.clean_cache()
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 264, in clean_cache
    cc.clean()
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 259, in clean
    util.rmtree_(self.cache_dir)
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 633, in rmtree_
    return rmtree(path, onerror=_onerror)
  File "/usr/lib/python2.7/shutil.py", line 253, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/home/tatu/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 631, in _onerror
    raise e
OSError: [Errno 21] Is a directory: '/home/tatu/.platformio/.cache'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by javigf** [comment]
Deleting the directory mentioned at first line, fixed the error
