### ISSUE TITLE
InstallationManager exception on Atom start

### ISSUE THREAD

**Issue by MHesham** [platformio/platformio-atom-ide#1118]
The only way to get around this was to start Atom from terminal with sudo.

Error: EACCES: permission denied, mkdir '/home/mlotfy/.platformio/.cache/tmp-3326Xn2MUhvQamhY'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Object.dirSync (/home/mlotfy/.atom/packages/platformio-ide/node_modules/tmp/lib/tmp.js:357:6)
    at PlatformIOCoreStage._callee4$ (/home/mlotfy/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2073:41)
    at tryCatch (/home/mlotfy/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:780:40)
    at Generator.invoke [as _invoke] (/home/mlotfy/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1014:22)
    at Generator.prototype.(anonymous function) [as next] (/home/mlotfy/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:832:21)
    at step (/home/mlotfy/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1778:191)
    at /home/mlotfy/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1778:361
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please remove `/home/mlotfy/.platformio` folder, start Atom WITHOUT sudo.
