### ISSUE TITLE
Uninstall incompatible packages: build

### ISSUE THREAD

**Issue by brooksware2000** [platformio/platformio-atom-ide#1121]
Error: Failed to delete build: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Curtis\.atom\packages\build'

    at file:///C:/Users/Curtis/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:139:27
    at file:///C:/Users/Curtis/.atom/packages/platformio-ide/lib/utils.js:52:7
    at ChildProcess.onExit (C:\Users\Curtis\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:498:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\Curtis\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by ivankravets** [comment]
Please restart IDE, it will be fixed automatically.
