### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by bcarpenter2** [platformio/platformio-atom-ide#1124]
Error: Error: Error: Failed to download file https://github.com/IntoYun/intoyuniot-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/rsbook/.atom/packages/intoyuniot-ide/lib/installer/stages/project-examples.js:157:13)
    at Generator.throw (<anonymous>)
    at step (/Users/rsbook/.atom/packages/intoyuniot-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Fixed in the latest version. Please upgrade.

**Comment by ivankravets** [comment]
How did you install `platformio-ide`?
