### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by fanch64** [platformio/platformio-atom-ide#1130]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\fanch\.platformio\.cache\tmp-24925Gf3x6ToY4HP\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\fanch\.platformio\.cache\tmp-24925Gf3x6ToY4HP\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\fanch\.platformio\.cache\tmp-24925Gf3x6ToY4HP\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\fanch\.platformio\.cache\tmp-24925Gf3x6ToY4HP\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\fanch\.platformio\.cache\tmp-24925Gf3x6ToY4HP\virtualenv-14.0.6\virtualenv.py", line 747, in call_subprocess
    "Error %s while executing command %s" % (e, cmd_desc))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 19: ordinal not in range(128)

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```
