### ISSUE TITLE
IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Shinleii** [platformio/platformio-atom-ide#1134]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\ASUS ROG\.platformio\.cache\tmp-26172zSSmtoMkilkt\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\ASUS ROG\.platformio\.cache\tmp-26172zSSmtoMkilkt\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\ASUS ROG\.platformio\.cache\tmp-26172zSSmtoMkilkt\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\ASUS ROG\.platformio\.cache\tmp-26172zSSmtoMkilkt\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\Lib\shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\ASUSRO~1\\PLATFO~1\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
