### ISSUE TITLE
setuptools pip wheel failed with error code 2

### ISSUE THREAD

**Issue by kyonmiriam** [platformio/platformio-atom-ide#1136]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/Saiun/.platformio/.cache/tmp-6128Vm4BOmwHqZwL/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/Saiun/.platformio/.cache/tmp-6128Vm4BOmwHqZwL/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/Saiun/.platformio/.cache/tmp-6128Vm4BOmwHqZwL/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/Users/Saiun/.platformio/.cache/tmp-6128Vm4BOmwHqZwL/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/Users/Saiun/.platformio/.cache/tmp-6128Vm4BOmwHqZwL/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/Saiun/.platformio/penv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

When I try to install, it shows this

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
