### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by dkraft** [platformio/platformio-atom-ide#1141]
Error: EACCES: permission denied, mkdir '/home/dkraft/.platformio/.cache-ide/tmp-2485iTfKos6v067a'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Object._createTmpDirSync [as dirSync] (/home/dkraft/.atom/packages/autocomplete-clang/node_modules/tmp/lib/tmp.js:351:6)
    at PlatformIOCoreStage.<anonymous> (/home/dkraft/.atom/packages/platformio-ide/lib/installer/stages/platformio-core.js:208:25)
    at Generator.next (<anonymous>)
    at step (/home/dkraft/.atom/packages/platformio-ide/lib/installer/stages/platformio-core.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
permission denied

Please restart IDE
