### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by oscarbelmon** [platformio/platformio-atom-ide#1144]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/oscar/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/oscar/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Where did you find this old installer? There is 2.0.0-rc.4 where this part of the code was removed.

**Comment by oscarbelmon** [comment]
Sorry, anything is correct now.
Thank you.
