### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by crestr25** [platformio/platformio-atom-ide#1151]
Error: Traceback (most recent call last):
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 38, in __init__
    self._gather_tplvars()
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 150, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 133, in __call__
    value = self.func(*args)
  File "/home/crestr25/.platformio/penv/local/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 74, in get_project_build_data
    raise result.exception
OSError: [Errno 13] Permission denied: '/home/crestr25/Dev/RemoteSensor-HTTP/Arduino/.piolibdeps/ArduinoJson_ID64'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Something is wrong with permissions. Please don't use PIO from `root` account.
