### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by nordeep** [platformio/platformio-atom-ide#1153]
Traceback (most recent call last):
  File "C:\Users\user\.platformio\penv\Scripts\platformio-script.py", line 11, in <module>
    load_entry_point('platformio==3.5.0b3', 'console_scripts', 'platformio')()
  File "c:\users\user\.platformio\penv\lib\site-packages\platformio\__main__.py", line 123, in main
    maintenance.on_platformio_exception(e)
  File "c:\users\user\.platformio\penv\lib\site-packages\platformio\maintenance.py", line 63, in on_platformio_exception
    telemetry.on_exception(e)
  File "c:\users\user\.platformio\penv\lib\site-packages\platformio\telemetry.py", line 323, in on_exception
    skip_conditions.append("[API] Account: " in str(e))
  File "c:\users\user\.platformio\penv\lib\site-packages\platformio\exception.py", line 23, in __str__
    return Exception.__str__(self)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 222-223: ordinal not in range(128)

**Comment by ivankravets** [comment]
Could you reproduce it again?

**Comment by ivankravets** [comment]
Please reopen if you still need help
