### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by tuxmartin** [platformio/platformio-atom-ide#1154]
Error: Status 'PlatformIO: Rebuilding C/C++ Project Index for /home/martin/SONOFF/ESPEasy' is already set
    at Registry.statusAdd (/home/martin/.atom/packages/busy-signal/lib/registry.js:50:13)
    at /home/martin/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Provider.add (/home/martin/.atom/packages/busy-signal/lib/provider.js:21:18)
    at beginBusy (/home/martin/.atom/packages/platformio-ide/lib/services/busy.js:25:20)
    at ProjectIndexer.<anonymous> (/home/martin/.atom/packages/platformio-ide/lib/project/indexer.js:158:7)
    at Generator.next (<anonymous>)
    at step (/home/martin/.atom/packages/platformio-ide/lib/project/indexer.js:11:273)
    at /home/martin/.atom/packages/platformio-ide/lib/project/indexer.js:11:443
    at ProjectIndexer.<anonymous> (/home/martin/.atom/packages/platformio-ide/lib/project/indexer.js:11:99)

**Comment by ivankravets** [comment]
Fixed in the latest release
