### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mateusromanbr** [platformio/platformio-atom-ide#1162]
Error: Traceback (most recent call last):
  File "c:\users\mateus\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\mateus\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 92, in cli
    init_base_project(project_dir)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 144, in init_base_project
    config = util.load_project_config(project_dir)
  File "c:\users\mateus\.platformio\penv\lib\site-packages\platformio\util.py", line 340, in load_project_config
    cp.read(path)
  File "C:\Python27\Lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Python27\Lib\ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: C:\Users\Mateus\Documents\PlatformIO\Projects\171120-155308-megaatmega2560\platformio.ini
	[line 15]: '/*\n'
	[line 39]: "// We need to use the 'raw' pin reading methods\n"
	[line 40]: '// because timing is very important here and the digitalRead()\n'
	[line 41]: '// procedure is slower!\n'
	[line 46]: "// The maximum pulse we'll listen for - 65 milliseconds is a long time\n"
	[line 49]: '// Timing resolution\n'
	[line 60]: '// Store up to 100 pulse pairs\n'
	[line 61]: 'uint16_t pulses[100][2]; // Pair is high and low pulse\n'
	[line 64]: 'void setup(void) {\n'
	[line 75]: '}\n'
	[line 77]: 'void loop(void) {\n'
	[line 128]: '}\n'
	[line 130]: 'void printpulses(void) {\n'
	[line 146]: "/*  // Print it in a 'array' format\n"
	[line 159]: '*/\n'
	[line 162]: '}\n'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Broken INI file C:\Users\Mateus\Documents\PlatformIO\Projects\171120-155308-megaatmega2560\platformio.ini
