### ISSUE TITLE
IntoYun command failed: platform frameworks --json-output

### ISSUE THREAD

**Issue by feimax** [platformio/platformio-atom-ide#1163]
Error: Error: [API] 403 Client Error: Forbidden for url: http://ide.intoyun.com/v1/framework

    at /Users/Fei/.atom/packages/intoyuniot-ide/lib/platform/helpers.js:63:25
    at onExit (/Users/Fei/.atom/packages/intoyuniot-ide/lib/utils.js:92:7)
    at exit (/Users/Fei/.atom/packages/intoyuniot-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please uninstall unofficial `intoyuniot-ide` and use our official http://platformio.org/platformio-ide
