### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by PfadGetreide** [platformio/platformio-atom-ide#1165]
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/mazze_000/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\mazze_000\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Where did you find this old installer? There is 2.0.0-rc.4 where this part of the code was removed.
