### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mrlinux1** [platformio/platformio-atom-ide#1166]
Error: Error: Error: Failed to download file http://dl.platformio.org/ide-data/platformio-examples.tar.gz: 
    at ProjectExamplesStage.<anonymous> (/home/tsgebert/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (/home/tsgebert/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Where did you find this old installer? There is 2.0.0-rc.4 where this part of the code was removed.
