### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by vedatAltun** [platformio/platformio-atom-ide#1175]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\user\.platformio\.cache\tmp-5784GbWM47bka5PA\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\user\.platformio\.cache\tmp-5784GbWM47bka5PA\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\user\.platformio\.cache\tmp-5784GbWM47bka5PA\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\user\.platformio\.cache\tmp-5784GbWM47bka5PA\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\lib\shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\user\\.platformio\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by vedatAltun** [comment]
Thanks  I solved  my problem

Le ven. 15 déc. 2017 à 21:57, Ivan Kravets <notifications@github.com> a
écrit :

**Comment by ivankravets** [comment]
How did you solve it?
