### ISSUE TITLE
IOError: [Errno 13]

### ISSUE THREAD

**Issue by lapillo** [platformio/platformio-atom-ide#1186]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\lapillo\.platformio\.cache\tmp-14056JpqEjz66JO3E\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\lapillo\.platformio\.cache\tmp-14056JpqEjz66JO3E\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\lapillo\.platformio\.cache\tmp-14056JpqEjz66JO3E\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\lapillo\.platformio\.cache\tmp-14056JpqEjz66JO3E\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Users\lapillo\.platformio\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\lapillo\\.platformio\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
@orangemicrosys @lapillo 

Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Should be fixed in the latest release.
