### ISSUE TITLE
LookupError: unknown encoding: ascii

### ISSUE THREAD

**Issue by lapillo** [platformio/platformio-atom-ide#1196]
Traceback (most recent call last):
  File "C:\Users\lapillo\.platformio\penv\Scripts\platformio-script.py", line 11, in <module>
    load_entry_point('platformio==3.5.0b4', 'console_scripts', 'platformio')()
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 2402, in load
    return self.resolve()
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\platformio\__main__.py", line 23, in <module>
    from platformio import __version__, exception, maintenance
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\platformio\maintenance.py", line 24, in <module>
    from platformio import __version__, app, exception, telemetry, util
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\platformio\app.py", line 24, in <module>
    import requests
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\requests\__init__.py", line 97, in <module>
    from . import utils
  File "c:\users\lapillo\.platformio\penv\lib\site-packages\requests\utils.py", line 779, in <module>
    _null = '\x00'.encode('ascii')  # encoding to ASCII for Python 3
LookupError: unknown encoding: ascii

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
