### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by zhaoran0072004** [platformio/platformio-atom-ide#1206]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/zhaoran/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/zhaoran/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Where did you find this old installer? There is 2.0.0-rc.4 where this part of the code was removed.
