### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by gegevdb** [platformio/platformio-atom-ide#1208]
Virtualenv Create: Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp-10128w5TnKes5eLYE\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\.platformio\.cache\tmp-10128w5TnKes5eLYE\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\.platformio\.cache\tmp-10128w5TnKes5eLYE\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\.platformio\.cache\tmp-10128w5TnKes5eLYE\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\.platformio\.cache\tmp-10128w5TnKes5eLYE\virtualenv-14.0.6\virtualenv.py", line 780, in call_subprocess
    logger.notify('\n'.join(all_output) + '\n----------------------------------------')
  File "C:\.platformio\.cache\tmp-10128w5TnKes5eLYE\virtualenv-14.0.6\virtualenv.py", line 193, in notify
    self.log(self.NOTIFY, msg, *args, **kw)
  File "C:\.platformio\.cache\tmp-10128w5TnKes5eLYE\virtualenv-14.0.6\virtualenv.py", line 225, in log
    consumer.write(rendered+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1647: ordinal not in range(128)

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
