### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by stevie72** [platformio/platformio-atom-ide#1221]
Error: Couldn't clone https://github.com/platformio/platformio-atom-ide.git or git+ssh://git@github.com/platformio/platformio-atom-ide.git

    at utils.runAPMCommand.busyTitle (/Users/Stefan/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (/Users/Stefan/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/Stefan/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please navigate to `Settings > Packages` and update package manually.
