### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by roblad** [platformio/platformio-atom-ide#1230]
Please manually remove file `C:\Users\robert\.platformio\packages\tool-pioplus\pioplus.exe`
Error: Traceback (most recent call last):
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\robert\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\robert\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\robert\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\robert\.platformio\penv\lib\site-packages\click\core.py", line 995, in _process_result
    **ctx.params)
  File "c:\users\robert\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\robert\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\__main__.py", line 80, in process_result
    maintenance.on_platformio_end(ctx, result)
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\maintenance.py", line 52, in on_platformio_end
    check_platformio_upgrade()
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\maintenance.py", line 241, in check_platformio_upgrade
    update_core_packages(silent=True)
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\managers\core.py", line 89, in update_core_packages
    pm.update(name, requirements, only_check=only_check)
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\managers\core.py", line 51, in update
    result = PackageManager.update(self, *args, **kwargs)
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 735, in update
    self.uninstall(pkg_dir, trigger_event=False)
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 676, in uninstall
    util.rmtree_(pkg_dir)
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\util.py", line 633, in rmtree_
    return rmtree(path, onerror=_onerror)
  File "c:\Python27\Lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\users\robert\.platformio\penv\lib\site-packages\platformio\util.py", line 631, in _onerror
    raise e
WindowsError: [Error 5] Odmowa dost�pu: 'C:\\Users\\robert\\.platformio\\packages\\tool-pioplus\\pioplus.exe'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please close IDE, kill all `pioplus.exe` processes and remove `C:\Users\robert\.platformio\packages\tool-pioplus` folder. Start IDE.
