### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by terasum** [platformio/platformio-atom-ide#1236]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/chenquan/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at Generator.throw (<anonymous>)
    at step (/Users/chenquan/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please update your Atom and PlatformIO IDE extension
