### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Please manually remove file `~/.platformio\packa...

### ISSUE THREAD

**Issue by tekk** [platformio/platformio-atom-ide#1266]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-rc.4

### Stack Trace

Uncaught Error: Could not start PIO Home server: Please manually remove file `C:\Users\tekks\.platformio\packages\tool-pioplus\pioplus.exe`
Please manually remove file `C:\Users\tekks\.platformio\packages\tool-pioplus\pioplus.exe`
Error: Could not install 'tool-pioplus' with version requirements '>=0.12.0,<2' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

```
At C:\Users\tekks\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1571

Error: Could not start PIO Home server: Please manually remove file `C:\Users\tekks\.platformio\packages\tool-pioplus\pioplus.exe`
Please manually remove file `C:\Users\tekks\.platformio\packages\tool-pioplus\pioplus.exe`
Error: Could not install 'tool-pioplus' with version requirements '>=0.12.0,<2' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1571:23
    at ChildProcess.onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:499:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (/packages/platformio-ide/node_modules/cross-spawn/lib/enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.69.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.14 
git-plus 7.10.0 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-aia 0.0.5 
platformio-ide 2.0.0-rc.4 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.7.0 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment]
I hope you resolved this issue.
