### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Igor122017** [platformio/platformio-atom-ide#1281]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\User_H\.platformio\.cache\tmp-8327JywBFNSayIq\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\User_H\.platformio\.cache\tmp-8327JywBFNSayIq\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\User_H\.platformio\.cache\tmp-8327JywBFNSayIq\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\User_H\.platformio\.cache\tmp-8327JywBFNSayIq\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\User_H\.platformio\.cache\tmp-8327JywBFNSayIq\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Users\User_H\.platformio\python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\User_H\.platformio\python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5]

**Comment by Igor122017** [comment]
почему ошибка?
