### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by bangtiray** [platformio/platformio-atom-ide#1292]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Ahmad Satiri\.platformio\.cache\tmp-67727Fckp20TVjrG\virtualenv-14.0.6\virtualenv.py", line 21, in <module>
    import logging
  File "C:\Python27\Lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "C:\Python27\Lib\weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1223#issuecomment-352085982
