### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mabe71** [platformio/platformio-atom-ide#1314]
Hi, 

I tried to install the platformio-ide package in atom 1.23.1 on os x 10.9.5 and get the error message that python could not be found (see below). 
However, python is in /usr/bin/python and python --version returns Python 2.7.5
Anybody any idea how I can install platformio-ide?
Thanks.
Matthias

Error: Can not find Python Interpreter
    at PlatformIOCoreStage._callee8$ (/Users/matthias/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2411:23)
    at tryCatch (/Users/matthias/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:787:40)
    at Generator.invoke [as _invoke] (/Users/matthias/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1021:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/matthias/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:839:21)
    at step (/Users/matthias/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1792:191)
    at /Users/matthias/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1792:361

**Comment by mabe71** [comment]
I noticed that I had python3.4 installed on my system. Removing this from the $PATH did not help. Installing python2.7.14 from python.org, however, solved the problem.
