### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by vbracq** [platformio/platformio-atom-ide#1327]
Error: Error: Error: Failed to download file http://dl.platformio.org/ide-data/platformio-examples.tar.gz: 
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/F094527/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at Generator.throw (<anonymous>)
    at step (C:\Users\F094527\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Fixed in previous releases. Please use the latest RC version and upgrade your Atom installation.
