### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by ewoks** [platformio/platformio-atom-ide#1341]
Error: Couldn't clone https://github.com/platformio/platformio-atom-ide.git or git+ssh://git@github.com/platformio/platformio-atom-ide.git

    at /Users/{username_here}/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (/Users/{username_here}/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ewoks** [comment]
sorry for new issue, it can be marked as duplicate of #1334

**Comment by ewoks** [comment]
After taking deeper look, I realised that issue was on my side and  ~/.gitconfig configuration that contained sslCAInfo entry with self signed certificate :S 
Update worked after that so this issue can be closed
