### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by bcunning0116** [platformio/platformio-atom-ide#1354]
Error: Traceback (most recent call last):
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 92, in cli
    init_base_project(project_dir)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 144, in init_base_project
    config = util.load_project_config(project_dir)
  File "/Users/brandoncunningham1t/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 349, in load_project_config
    cp.read(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /Volumes/128G/Sonoff-Tasmota-development/platformio.ini, line: 1
'F\xb1\xbe\xf0+\xb6\x1f\x02\x95\xf5x\xa8x\xa6~\x17O\xfcx\x07\xbc\xacz?\x96z\xabT\xaf\xfcT?T\xab\xf1_\xd5*S\x0b\xfc_\x9e\xf5\xf7\xa4\x1e\xab\x00\x9c?\xe0,#g\xea\xb1\xc4)$\xec\xd4\xe6e\xb7\x91n6h1\x82I\xb7`cm\xbf\x02\xaf\xf4\x95i\x88x\xf4\x84\xf5\xd65\xd8h\n'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please fix `platformio.ini` and remove non-ASCII chars
