### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Error: Could not load broken JSON: ~/.platformio...

### ISSUE THREAD

**Issue by petru23** [platformio/platformio-atom-ide#1355]
[Enter steps to reproduce:]

1. After installed the PlatformIO IDE package and restarted atom I had this issue

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-rc.5

### Stack Trace

Uncaught Error: Could not start PIO Home server: Error: Could not load broken JSON: C:\Users\utente\.platformio\packages\contrib-piohome\package.json

```
At C:\Users\utente\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1571

Error: Could not start PIO Home server: Error: Could not load broken JSON: C:\Users\utente\.platformio\packages\contrib-piohome\package.json

    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1571:23
    at ChildProcess.onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:499:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (/packages/platformio-ide/node_modules/cross-spawn/lib/enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.15 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-ide 2.0.0-rc.5 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.0 
tool-bar 1.1.1 
```

**Comment by ivankravets** [comment]
Please remove `C:\Users\utente\.platformio\packages\contrib-piohome` folder and restart IDE
