### ISSUE TITLE
Minimum supported version is 2.7.6

### ISSUE THREAD

**Issue by hongselectronics** [platformio/platformio-atom-ide#1377]
On startup:

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-rc.7

### Stack Trace

Uncaught Error: Could not start PIO Home server: Error: PlatformIO Core Plus v3.5.1a5 does not run under Python version 2.7.
Minimum supported version is 2.7.6, please upgrade Python.
Python 3 is not yet supported.

```
At C:\Users\Jeremy Hong\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1612

Error: Could not start PIO Home server: Error: PlatformIO Core Plus v3.5.1a5 does not run under Python version 2.7.
Minimum supported version is 2.7.6, please upgrade Python.
Python 3 is not yet supported.


    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1612:23
    at ChildProcess.onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:534:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (/packages/platformio-ide/node_modules/cross-spawn/lib/enoent.js:40:29)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.69.0 
busy-signal 1.4.3 
file-icons 2.1.13 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.8 
platformio-ide 2.0.0-rc.7 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.7.0 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
We decrease requirements to Python 2.7.5+

Please uninstall/install our extension again.
