### ISSUE TITLE
Impossible to install on OSX :(

### ISSUE THREAD

**Issue by xbeaudouin** [platformio/platformio-atom-ide#1383]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/kiwi/.platformio/.cache/tmp-5749kq23itkaEjnV/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/kiwi/.platformio/.cache/tmp-5749kq23itkaEjnV/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/kiwi/.platformio/.cache/tmp-5749kq23itkaEjnV/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/Users/kiwi/.platformio/.cache/tmp-5749kq23itkaEjnV/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/Users/kiwi/.platformio/.cache/tmp-5749kq23itkaEjnV/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/kiwi/.platformio/penv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

This is a known issue. Could you provide TeamViewer session to debug it? I think other users would be thankful if we find a solution. You can contact me@ikravets.com. Thanks!

**Comment by ivankravets** [comment]
Please reopen if you still need help
