### ISSUE TITLE
I am trying install this package in Atom text editor for my Ardunio project, and got this error. Trying to google around, but can't fix it.

### ISSUE THREAD

**Issue by domanhtien2011** [platformio/platformio-atom-ide#1389]
Virtualenv Create: ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv.py", line 843, in install_wheel
    cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")
  File "/usr/local/lib/python2.7/pkgutil.py", line 578, in get_data
    loader = get_loader(package)
  File "/usr/local/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/local/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/local/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 38, in <module>
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 58, in <module>
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 26, in <module>
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/compat.py", line 7, in <module>
  File "/home/tiendo/.platformio/.cache/tmp-25133kycjMtwDmaHp/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3

**Comment by domanhtien2011** [comment]
Ok, I solved it by installing virtualenv package for Python, then activate it, and it is good to go.
