### ISSUE TITLE
shutil.Error

### ISSUE THREAD

**Issue by gnkarn** [platformio/platformio-atom-ide#1406]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/Gus-nuevo/.platformio/.cache/tmp-1550fzMg5gqAzumb/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/Gus-nuevo/.platformio/.cache/tmp-1550fzMg5gqAzumb/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/Gus-nuevo/.platformio/.cache/tmp-1550fzMg5gqAzumb/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/Gus-nuevo/.platformio/.cache/tmp-1550fzMg5gqAzumb/virtualenv-14.0.6/virtualenv.py", line 1101, in install_python
    copy_required_modules(home_dir, symlink)
  File "/Users/Gus-nuevo/.platformio/.cache/tmp-1550fzMg5gqAzumb/virtualenv-14.0.6/virtualenv.py", line 1042, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/Users/Gus-nuevo/.platformio/.cache/tmp-1550fzMg5gqAzumb/virtualenv-14.0.6/virtualenv.py", line 348, in copyfile
    copyfileordir(src, dest, symlink)
  File "/Users/Gus-nuevo/.platformio/.cache/tmp-1550fzMg5gqAzumb/virtualenv-14.0.6/virtualenv.py", line 325, in copyfileordir
    shutil.copy2(src, dest)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py` and `/Users/Gus-nuevo/.platformio/penv/lib/python2.7/locale.py` are the same file

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
