### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by timonde** [platformio/platformio-atom-ide#1407]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\s\.platformio\.cache\tmp-416b4uV4w8v58yW\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\s\.platformio\.cache\tmp-416b4uV4w8v58yW\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\s\.platformio\.cache\tmp-416b4uV4w8v58yW\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\s\.platformio\.cache\tmp-416b4uV4w8v58yW\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Users\s\.platformio\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\s\\.platformio\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please try to disable antivirus while installing PlatformIO IDE.
