### ISSUE TITLE
ImportError: No module named

### ISSUE THREAD

**Issue by DaxiongAI** [platformio/platformio-atom-ide#1433]
PIP: Traceback (most recent call last):
  File "/home/daxiong/.platformio/penv/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 30, in <module>
    from pip._vendor.retrying import retry
ImportError: No module named retrying

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please update `platformio-ide` package via `Settings > Updates`.
