### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ZeUsGoMo** [platformio/platformio-atom-ide#1437]
Virtualenv Create: Traceback (most recent call last):
  File "C:\SPB_Data\.platformio\.cache\tmp-46322IeK30Pfi37W\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\SPB_Data\.platformio\.cache\tmp-46322IeK30Pfi37W\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\SPB_Data\.platformio\.cache\tmp-46322IeK30Pfi37W\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\SPB_Data\.platformio\.cache\tmp-46322IeK30Pfi37W\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\SPB_Data\\.platformio\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide/issues/1407
