### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat 'D:/esp8266\ESPEasy_v2.0-20180126\Source'

### ISSUE THREAD

**Issue by cr3pt** [platformio/platformio-atom-ide#1445]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'D:\esp8266\ESPEasy_v2.0-20180126\Source'

```
At fs.js:902

Error: EPERM: operation not permitted, lstat 'D:\esp8266\ESPEasy_v2.0-20180126\Source'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1542:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:133:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:227:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/workspace.js:550:30
```

### Commands

```
     -8:01.8.0 platformio-ide:target:build (atom-pane.pane.active)
     -7:52 application:open-file (div.tool-panel.tree-view)
     -7:27 core:close (ul.list-inline.tab-bar.inset-panel)
     -7:02.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:54.2.0 platformio-ide:target:build (iframe.native-key-bindings)
     -6:54.2.0 platformio-ide:target:build-D:\esp8266\ESPEasy_v2.0-20180126\Source (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:45.9.0 platformio-ide:target:build (atom-pane.pane.active)
     -6:45.9.0 platformio-ide:target:build-D:\esp8266\ESPEasy_v2.0-20180126\Source (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:09.6.0 platformio-ide:target:build (iframe.native-key-bindings)
     -5:09.6.0 platformio-ide:target:build-D:\esp8266\ESPEasy_v2.0-20180126\Source (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:49.4.0 build:select-active-target (input.hidden-input)
     -3:23.2.0 platformio-ide:home (div.tool-panel.tree-view)
     -2:57.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:44.3.0 build:select-active-target (input.hidden-input)
     -0:35.4.0 platformio-ide:maintenance.install-commands (div.terminal)
     -0:25.8.0 platformio-ide:settings:pkg-platformio-ide (div.terminal)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.16 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-ide 2.0.0 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.0 
tool-bar 1.1.4 
```

**Comment by ivankravets** [comment]
Please restart IDE, all should work.
