### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by tassheloff** [platformio/platformio-atom-ide#1470]
Error: Cannot read property 'getReferenceTarget' of null

    at file:///C:/Users/fabio/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/fabio/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by reloxx13** [comment]
+1 same here

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1394
