### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by hitgk** [platformio/platformio-atom-ide#1479]
Error: Error: Error: Failed to download file https://github.com/IntoYun/intoyuniot-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/hhh/.atom/packages/intoyuniot-ide/lib/installer/stages/project-examples.js:157:13)
    at Generator.throw (<anonymous>)
    at step (C:\Users\hhh\.atom\packages\intoyuniot-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please upgrade Atom and PIO IDE
