### ISSUE TITLE
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1

### ISSUE THREAD

**Issue by HedmilsonDomingos** [platformio/platformio-atom-ide#1537]
pi@raspberrypi:~ $ sudo python get-pip.py
Exception:
Traceback (most recent call last):
  File "/tmp/tmpjx6EvG/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmpjx6EvG/pip.zip/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/tmp/tmpjx6EvG/pip.zip/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/tmp/tmpjx6EvG/pip.zip/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/tmp/tmpjx6EvG/pip.zip/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/tmp/tmpjx6EvG/pip.zip/pip/_vendor/distro.py", line 1050, in <module>
  File "/tmp/tmpjx6EvG/pip.zip/pip/_vendor/distro.py", line 594, in __init__
  File "/tmp/tmpjx6EvG/pip.zip/pip/_vendor/distro.py", line 933, in _get_lsb_release_info
CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1
Traceback (most recent call last):
  File "get-pip.py", line 20061, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 172, in bootstrap
    sys.exit(pip.main(["install", "--upgrade"] + args))
  File "/tmp/tmpjx6EvG/pip.zip/pip/__init__.py", line 233, in main
  File "/tmp/tmpjx6EvG/pip.zip/pip/basecommand.py", line 251, in main
  File "/tmp/tmpjx6EvG/pip.zip/pip/basecommand.py", line 72, in _build_session
  File "/tmp/tmpjx6EvG/pip.zip/pip/download.py", line 329, in __init__
  File "/tmp/tmpjx6EvG/pip.zip/pip/download.py", line 93, in user_agent
  File "/tmp/tmpjx6EvG/pip.zip/pip/_vendor/distro.py", line 1050, in <module>
  File "/tmp/tmpjx6EvG/pip.zip/pip/_vendor/distro.py", line 594, in __init__
  File "/tmp/tmpjx6EvG/pip.zip/pip/_vendor/distro.py", line 933, in _get_lsb_release_info
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please update `platformio-ide` package via `Settings > Updates`.
