### ISSUE TITLE
SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version

### ISSUE THREAD

**Issue by VolodymyrGalushka** [platformio/platformio-atom-ide#1551]
PIP: Exception:
Traceback (most recent call last):
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/vasudevdas/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

**Comment by ivankravets** [comment]
@VolodymyrGalushka, @tigertim08, @Andorin, @mac-dj73, @dy008

Please open system terminal and provide an output of 
```
python -c "import ssl; print(ssl.OPENSSL_VERSION)"
```

**Comment by ivankravets** [comment]
Try in system terminal
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install openssl
```

After that, please remove `~/.platformio/penv` folder and restart IDE.

**Comment by ivankravets** [comment]
Please upgrade PIO IDE to 2.1.0

**Comment by VolodymyrGalushka** [comment]
Thanks

**Comment by gitanupam** [comment]
Simply upgrading pip may also help but need to upgrade `pip` without using `pip` (because of recent TLS deprecation by Python.org sites). See this SO post for details: https://stackoverflow.com/q/49768770/1526703

**Comment by mkaykisiz** [comment]
curl https://bootstrap.pypa.io/get-pip.py | python
