### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by alxm31** [platformio/platformio-atom-ide#1555]
Error: Error: Error: Failed to download file http://dl.platformio.org/ide-data/platformio-examples.tar.gz: 
    at ProjectExamplesStage.<anonymous> (/Users/alex/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at Generator.throw (<anonymous>)
    at step (/Users/alex/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1366
