### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by StefanBasten** [platformio/platformio-atom-ide#1558]
Error: Traceback (most recent call last):
  File "c:\users\stefan\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\stefan\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\stefan\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\stefan\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\stefan\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\stefan\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\stefan\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\stefan\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\users\stefan\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 35, in __init__
    self._gather_tplvars()
  File "c:\users\stefan\.p

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please update `platformio-ide` package via `Settings > Updates`.
