### ISSUE TITLE
InstallationManager errors

### ISSUE THREAD

**Issue by pallazola** [platformio/platformio-atom-ide#1564]
error message after platformio-atom-ide install on high Sierra mac

Virtualenv Create: Traceback (most recent call last):
  File "/Users/mike/.platformio/.cache/tmp-94420vqwdYk0Jlbz8/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/mike/.platformio/.cache/tmp-94420vqwdYk0Jlbz8/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/mike/.platformio/.cache/tmp-94420vqwdYk0Jlbz8/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/Users/mike/.platformio/.cache/tmp-94420vqwdYk0Jlbz8/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/Users/mike/.platformio/.cache/tmp-94420vqwdYk0Jlbz8/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/mike/.platformio/penv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1

**Comment by ivankravets** [comment]
Please upgrade to `platformio-ide` 2.1.5, should be fixed. 
Please reopen if you still need help.
