### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by plorch** [platformio/platformio-atom-ide#1568]
Virtualenv Create: Traceback (most recent call last):
  File "U:\.platformio\.cache\tmp-74081vBPAF4f3R2C\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "U:\.platformio\.cache\tmp-74081vBPAF4f3R2C\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "U:\.platformio\.cache\tmp-74081vBPAF4f3R2C\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "U:\.platformio\.cache\tmp-74081vBPAF4f3R2C\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "U:\.platformio\.cache\tmp-74081vBPAF4f3R2C\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command U:\.platformio\penv\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please upgrade to `platformio-ide` 2.1.5, should be fixed. 
Please reopen if you still need help.
