### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by romaine09** [platformio/platformio-atom-ide#1569]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Romaine's PC\.platformio\.cache\tmp-16408AwREnlhxj75u\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Romaine's PC\.platformio\.cache\tmp-16408AwREnlhxj75u\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Romaine's PC\.platformio\.cache\tmp-16408AwREnlhxj75u\virtualenv-14.0.6\virtualenv.py", line 900, in create_environment
    home_dir, lib_dir, inc_dir, bin_dir = path_locations(home_dir)
  File "C:\Users\Romaine's PC\.platformio\.cache\tmp-16408AwREnlhxj75u\virtualenv-14.0.6\virtualenv.py", line 944, in path_locations
    mkdir(home_dir)
  File "C:\Users\Romaine's PC\.platformio\.cache\tmp-16408AwREnlhxj75u\virtualenv-14.0.6\virtualenv.py", line 317, in mkdir
    os.makedirs(path)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: "C:\\Users\\Romaine's PC\\.platformio\\penv"

**Comment by ivankravets** [comment]
Please remove `C:\Users\Romaine's PC\.platformio\penv` and restart IDE
