### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by alberto-araguas** [platformio/platformio-atom-ide#1574]
Cloning into 'C:\Users\Alberto\.platformio\packages\_tmp_installing-ht7enp-package'...
Submodule 'libraries/BLE' (https://github.com/nkolban/ESP32_BLE_Arduino.git) registered for path 'libraries/BLE'
Cloning into 'C:/Users/Alberto/.platformio/packages/_tmp_installing-ht7enp-package/libraries/BLE'...
Error: Traceback (most recent call last):
  File "c:\users\alberto\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\alberto\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 35, in __init__
    self._gather_tplvars()
  File "c:\users\alberto\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 152, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "c:\users\alberto\.platformio\penv\lib\site-packages\platformio\util.py", line 134, in __call__
    value = self.func(*args)
  File "c:\users\alberto\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 76, in get_project_build_data
    raise result.exception
WindowsError: [Error 32] El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso: 'C:\\Users\\Alberto\\.platformio\\packages\\framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6\\tools\\sdk\\ld\\esp32.common.ld'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please remove `C:\Users\Alberto\.platformio\packages\framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6` and restart IDE.
