### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by narfel** [platformio/platformio-atom-ide#1577]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Narfel\.platformio\.cache\tmp-12796OhdltH2p6qUR\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Narfel\.platformio\.cache\tmp-12796OhdltH2p6qUR\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Narfel\.platformio\.cache\tmp-12796OhdltH2p6qUR\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\Narfel\.platformio\.cache\tmp-12796OhdltH2p6qUR\virtualenv-14.0.6\virtualenv.py", line 1101, in install_python
    copy_required_modules(home_dir, symlink)
  File "C:\Users\Narfel\.platformio\.cache\tmp-12796OhdltH2p6qUR\virtualenv-14.0.6\virtualenv.py", line 1042, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "C:\Users\Narfel\.platformio\.cache\tmp-12796OhdltH2p6qUR\virtualenv-14.0.6\virtualenv.py", line 351, in copyfile
    copyfileordir(src, dest, symlink)
  File "C:\Users\Narfel\.platformio\.cache\tmp-12796OhdltH2p6qUR\virtualenv-14.0.6\virtualenv.py", line 323, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "C:\Python27\lib\shutil.py", line 191, in copytree
    os.makedirs(dst)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\Users\\Narfel\\.platformio\\penv\\lib\\encodings'

**Comment by ivankravets** [comment]
Please upgrade `platformio-ide` to 2.1.5
