### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by pixiandreas** [platformio/platformio-atom-ide#1587]
Virtualenv Create: Traceback (most recent call last):
  File "/home/andreas/.platformio/.cache/tmp-28976VcHx8QRJRSty/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/home/andreas/.platformio/.cache/tmp-28976VcHx8QRJRSty/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/home/andreas/.platformio/.cache/tmp-28976VcHx8QRJRSty/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/home/andreas/.platformio/.cache/tmp-28976VcHx8QRJRSty/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/home/andreas/.platformio/.cache/tmp-28976VcHx8QRJRSty/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/andreas/.platformio/penv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please upgrade to `platformio-ide` 2.1.5, should be fixed. 
Please reopen if you still need help.
