### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by benwk** [platformio/platformio-atom-ide#1613]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/benjamin/.platformio/.cache/tmp-86328EcRolKzzo1kv/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/benjamin/.platformio/.cache/tmp-86328EcRolKzzo1kv/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/benjamin/.platformio/.cache/tmp-86328EcRolKzzo1kv/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/benjamin/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/benjamin/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment]
Please upgrade `platformio-ide` to 2.1.5
