### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by IvanSova11** [platformio/platformio-atom-ide#1614]
Virtualenv Create: Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp-6460SmGPbeKr7eSC\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\.platformio\.cache\tmp-6460SmGPbeKr7eSC\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\.platformio\.cache\tmp-6460SmGPbeKr7eSC\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\.platformio\.cache\tmp-6460SmGPbeKr7eSC\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\.platformio\.cache\tmp-6460SmGPbeKr7eSC\virtualenv-14.0.6\virtualenv.py", line 747, in call_subprocess
    "Error %s while executing command %s" % (e, cmd_desc))
  File "C:\.platformio\.cache\tmp-6460SmGPbeKr7eSC\virtualenv-14.0.6\virtualenv.py", line 202, in fatal
    self.log(self.FATAL, msg, *args, **kw)
  File "C:\.platformio\.cache\tmp-6460SmGPbeKr7eSC\virtualenv-14.0.6\virtualenv.py", line 225, in log
    consumer.write(rendered+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0415' in position 52: ordinal not in range(128)

**Comment by ivankravets** [comment]
Please upgrade `platformio-ide` extension. Should be fixed.
