### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by jcole3303** [platformio/platformio-atom-ide#1633]
Error: Cannot read property 'getReferenceTarget' of null

    at file:///C:/Users/ColeJ/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/ColeJ/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by jcole3303** [comment]
the problem occurs when I opt to update platform-ide 2.
