### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by livioavalle** [platformio/platformio-atom-ide#1637]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\livio\.platformio\.cache\tmp-124320rq78iwpyeGY\virtualenv-14.0.6\virtualenv.py", line 30, in <module>
    from distutils.util import strtobool
  File "C:\Users\livio\.platformio\python27\lib\distutils\util.py", line 12, in <module>
    from distutils.spawn import spawn
  File "C:\Users\livio\.platformio\python27\lib\distutils\spawn.py", line 15, in <module>
    from distutils.debug import DEBUG
ImportError: cannot import name DEBUG

**Comment by ivankravets** [comment]
Fixed in v2.1.5. Please update and retest.
