### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by DinaEMusalam** [platformio/platformio-atom-ide#1640]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/dim/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at Generator.throw (<anonymous>)
    at step (/Users/dim/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1366
