### ISSUE TITLE
Failed to install platformio

### ISSUE THREAD

**Issue by FrzWilly** [platformio/platformio-atom-ide#1646]
Virtualenv Create: Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp-10348abGuP9A6ox7d\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\.platformio\.cache\tmp-10348abGuP9A6ox7d\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\.platformio\.cache\tmp-10348abGuP9A6ox7d\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\.platformio\.cache\tmp-10348abGuP9A6ox7d\virtualenv-14.0.6\virtualenv.py", line 846, in install_wheel
    cert_file = tempfile.NamedTemporaryFile(delete=False)
  File "C:\.platformio\python27\lib\tempfile.py", line 463, in NamedTemporaryFile
    dir = gettempdir()
  File "C:\.platformio\python27\lib\tempfile.py", line 275, in gettempdir
    tempdir = _get_default_tempdir()
  File "C:\.platformio\python27\lib\tempfile.py", line 217, in _get_default_tempdir
    ("No usable temporary directory found in %s" % dirlist))
IOError: [Errno 2] No usable temporary directory found in ['C:\\Users\\\xacI\xab\xaa\xba\xfb\\AppData\\Local\\Temp', 'C:\\Users\\\xacI\xab\xaa\xba\xfb\\AppData\\Local\\Temp', 'c:\\temp', 'c:\\tmp', '\\temp', '\\tmp', 'C:\\Users\\\xacI\xab\xaa\xba\xfb\\AppData\\Local\\atom\\app-1.25.0']

This issue occurred when I was trying to install platformio on Atom by installing package. I didn't install clang at first but installed it after my first try, and this continues to happen.

how should I solve this?

**Comment by ivankravets** [comment]
Please upgrade `platformio-ide` to 2.1.5
