### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by Roterfux** [platformio/platformio-atom-ide#1650]
Error: Couldn't clone https://github.com/platformio/platformio-atom-ide.git or git+ssh://git@github.com/platformio/platformio-atom-ide.git

    at file:///C:/Users/J/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/J/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by ivankravets** [comment]
Please manually upgrade `platformio-ide` to the latest release
