### ISSUE TITLE
InstallationManager Error

### ISSUE THREAD

**Issue by sdaitzman** [platformio/platformio-atom-ide#1659]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/sam/.platformio/.cache/tmp-72116Q9f1xEkea6Wa/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/sam/.platformio/.cache/tmp-72116Q9f1xEkea6Wa/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/sam/.platformio/.cache/tmp-72116Q9f1xEkea6Wa/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/sam/.platformio/.cache/tmp-72116Q9f1xEkea6Wa/virtualenv-14.0.6/virtualenv.py", line 1101, in install_python
    copy_required_modules(home_dir, symlink)
  File "/Users/sam/.platformio/.cache/tmp-72116Q9f1xEkea6Wa/virtualenv-14.0.6/virtualenv.py", line 1042, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/Users/sam/.platformio/.cache/tmp-72116Q9f1xEkea6Wa/virtualenv-14.0.6/virtualenv.py", line 348, in copyfile
    copyfileordir(src, dest, symlink)
  File "/Users/sam/.platformio/.cache/tmp-72116Q9f1xEkea6Wa/virtualenv-14.0.6/virtualenv.py", line 325, in copyfileordir
    shutil.copy2(src, dest)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/sam/.platformio/penv/lib/python2.7/stat.py'

**Comment by ivankravets** [comment]
Please upgrade `platformio-ide` to 2.1.5
