### ISSUE TITLE
Uncaught SyntaxError: Unexpected token L in JSON at position 0

### ISSUE THREAD

**Issue by fab33** [platformio/platformio-atom-ide#1669]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 17.10
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.3

### Stack Trace

Uncaught SyntaxError: Unexpected token L in JSON at position 0

```
At file:///usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token L in JSON at position 0
    at JSON.parse (<anonymous>)
    at /packages/platformio-ide/lib/installer/ide.js:80:65
    at Request._callback (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:552:12)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.15 
git-plus 7.10.2 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.3 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
tool-bar 1.1.4 
```

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please update `platformio-ide` package via `Settings > Updates`.
