### ISSUE TITLE
Could not start PIO Home server

### ISSUE THREAD

**Issue by mgx0** [platformio/platformio-atom-ide#1673]
Hello,

just got an error on my Mac when I try to install PlatformIO. First the original (worked yesterday) installation started throwing Server errors when trying to install librarier, viewing boards, nothing worked. so I removed ~/.atom and ~/.platformio folders and reinstalled from scratch. Same problem

am I doing anything wrong? I haven't changed anything, it just stopped working.
Is there any way to roll back to previous PIO version (just in case some update broke it?)

[Enter steps to reproduce:]

1. fresh install of Atom
2. fresh install of PlatformIO (currently version 3.5.3a6)

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.3

### Stack Trace

Uncaught Error: Could not start PIO Home server: Traceback (most recent call last):
  File "main.py", line 17, in init main
  File "cmd_home.py", line 507, in init cmd_home
  File "cmd_home.py", line 49, in cmd_home.memoized.__call__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'staticmethod' object has no attribute '__module__'

```
At /Users/mgtn/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1617

Error: Could not start PIO Home server: Traceback (most recent call last):
  File "main.py", line 17, in init main
  File "cmd_home.py", line 507, in init cmd_home
  File "cmd_home.py", line 49, in cmd_home.memoized.__call__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'staticmethod' object has no attribute '__module__'

    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1617:23
    at ChildProcess.onExit (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:538:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -0:23.9.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:23 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.18 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.3 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.8.1 
script 3.17.3 
tool-bar 1.1.7 
```

**Comment by mgx0** [comment]
I'm sorry for the confusion, I have resolved it by deleting folder ~/Library/Application Support/Atom/

now everything works fine, but I'm not sure why the "server error" appeared in the first place.
