### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by cainanalves** [platformio/platformio-atom-ide#1674]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: EACCES: permission denied, open '/home/cainan/.platformio/.cache/virtualenv.tar.gz'
    at _callee$ (/home/cainan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2668:19)
    at tryCatch (/home/cainan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/home/cainan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as throw] (/home/cainan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/home/cainan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:191)
    at /home/cainan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:402
    at <anonymous>

**Comment by ivankravets** [comment]
This is a known issue of PyPi service. Please start installing again.
