### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by git-tiger** [platformio/platformio-atom-ide#1693]
Error: Traceback (most recent call last):
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 92, in cli
    init_base_project(project_dir)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 144, in init_base_project
    config = util.load_project_config(project_dir)
  File "c:\users\tbs_engineer\.platformio\penv\lib\site-packages\platformio\util.py", line 334, in load_project_config
    cp.read(path)
  File "C:\Python27\Lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Python27\Lib\ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: C:\Users\TBS_Engineer\Google Drive\Work\Team BlackSheep\Philip Man\Software Development\esp_modules\platformio.ini
	[line 74]: '\tplatform = espressif8266\n'
	[line 75]: '\tboard = esp07\n'
	[line 76]: '\tframework = arduino\n'
	[line 77]: '\tupload_port = COM10\n'
	[line 78]: '\tupload_speed = 115200\n'
	[line 80]: '\tbuild_flags =\n'
	[line 81]: '\t\t-D TBS_ESCRCCAR\n'
	[line 82]: '\t\t-D VER_MAJOR=0\n'
	[line 83]: '\t\t-D VER_MINOR=1\n'
	[line 85]: '\t\t-D TBS_HAS_SMART_AUDIO\n'
	[line 86]: '\t\t-D SMARTAUDIO_PIN=5\n'
	[line 88]: '\t\t-D PWM_SERVO=0\n'
	[line 89]: '\t\t-D PWM_MOTOR=4\n'
	[line 91]: '\t\t-D GYRO_SDA=2\n'
	[line 92]: '\t\t-D GYRO_SCL=14\n'
	[line 94]: '\t\t-D LED_DIN=15\n'
	[line 95]: '\t\t-D NUM_LEDS=1\n'
	[line 97]: '\t\t-D TBS_HAS_STRIPLEDS\n'
	[line 98]: '\t\t-D STRIP_LED_DIN=13\n'
	[line 99]: '\t\t-D STRIP_NUM_LEDS=120\n'
	[line 101]: '\t\t-D I2C_SDA=2\n'
	[line 102]: '\t\t-D I2C_SCL=14\n'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by git-tiger** [comment]
Bad indent in ini file
