### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by usuf1** [platformio/platformio-atom-ide#1703]
Error: Can not find Python Interpreter
    at PlatformIOCoreStage._callee8$ (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2530:23)
    at tryCatch (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:836:40)
    at Generator.invoke [as _invoke] (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:888:21)
    at step (C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1877:191)
    at C:\Users\YUsuf\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1877:361
    at <anonymous>

**Comment by ivankravets** [comment]
Please install Python 2.7 manually and restart IDE https://www.python.org/downloads/release/python-2715/
