### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gregg-hoshovsky** [platformio/platformio-atom-ide#1705]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/Users/greggh/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2668:19)
    at tryCatch (/Users/greggh/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/Users/greggh/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/greggh/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/Users/greggh/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:191)
    at /Users/greggh/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:361
    at <anonymous>

**Comment by ivankravets** [comment]
Please try to uninstall and install extension again
