### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by zen** [platformio/platformio-atom-ide#1709]
Error: Traceback (most recent call last):
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 103, in cli
    pg.generate()
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 120, in generate
    self._render_tpl(tpl_path).encode("utf8"))
  File "/Users/zen/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 126, in _render_tpl
    return bottle.template(content, **self._tplvars)
  File "/Users/zen/.platformio/penv/bin/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/Users/zen/.platformio/penv/bin/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/Users/zen/.platformio/penv/bin/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "<string>", line 2, in <module>
AttributeError: 'NoneType' object has no attribute 'replace'

============================================================

**Comment by zen** [comment]
Closing as dupe
