### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by playaspec** [platformio/platformio-atom-ide#1714]
Upgrading from 7.3.1 to current. Appears to be working otherwise.

Virtualenv Create: Traceback (most recent call last):
  File "/Users/gduncan/.platformio/.cache/tmp-11239s6MI76UKrgb0/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/Users/gduncan/.platformio/.cache/tmp-11239s6MI76UKrgb0/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/Users/gduncan/.platformio/.cache/tmp-11239s6MI76UKrgb0/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/Users/gduncan/.platformio/.cache/tmp-11239s6MI76UKrgb0/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/Users/gduncan/.platformio/.cache/tmp-11239s6MI76UKrgb0/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/gduncan/.platformio/penv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please upgrade to `platformio-ide` 2.1.5, should be fixed. 
Please reopen if you still need help.
