### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Omega1102** [platformio/platformio-atom-ide#1718]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Omega1102\.platformio\.cache\tmp-10232qWwI2Fux59MH\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Omega1102\.platformio\.cache\tmp-10232qWwI2Fux59MH\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Omega1102\.platformio\.cache\tmp-10232qWwI2Fux59MH\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\Omega1102\.platformio\.cache\tmp-10232qWwI2Fux59MH\virtualenv-14.0.6\virtualenv.py", line 834, in install_wheel
    from urllib.parse import urljoin
  File "C:\Users\Omega1102\.platformio\python27\lib\urllib.py", line 26, in <module>
    import socket
  File "C:\Users\Omega1102\.platformio\python27\lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: %1 ist keine zul�ssige Win32-Anwendung.

Can someone help me, please? I'm trying to install Platformio on my Win10 System. Very other packeg until this one is working fine.

**Comment by ivankravets** [comment]
Please upgrade `platformio-ide` to 2.1.5
