### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by sandro197802** [platformio/platformio-atom-ide#1721]
Error: Traceback (most recent call last):
  File "c:\users\aless\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\aless\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\aless\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\aless\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\aless\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\aless\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\aless\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\aless\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\users\aless\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 35, in __init__
    self._gather_tplvars()
  File "c:\users\aless\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 151, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "c:\users\aless\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 75, in get_project_build_data
    raise result.exception
IOError: [Errno 2] No such file or directory: 'C:\\Users\\aless\\Desktop\\Ex ASUS\\Stampa 3D\\Firmware VARI\\Marlin-bugfix-2.0 MKS SBASE\\Marlin-bugfix-2.0.x (2)\\Marlin-bugfix-2.0.x\\.piolibdeps\\_tmp_installing-4k3szx-package\\LiquidTWI2-30aa480782053c7ffd301031e8809a98a2eb063f\\examples\\HelloWorld_i2c\\HelloWorld_i2c.ino'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Should be fixed in the latest release.
