### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by outlawza** [platformio/platformio-atom-ide#1727]
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (/home/twade/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at Generator.throw (<anonymous>)
    at step (/home/twade/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1366
