### ISSUE TITLE
Uninstall incompatible packages: autocomplete-clang,build

### ISSUE THREAD

**Issue by astonix** [platformio/platformio-atom-ide#1740]
Error: Failed to delete autocomplete-clang: Does not exist

    at /home/astonix/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:139:27
    at /home/astonix/.atom/packages/platformio-ide/lib/utils.js:52:7
    at ChildProcess.onExit (/home/astonix/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:538:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please restart IDE. Should be fixed in the latest release
