### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by SimenZhor** [platformio/platformio-atom-ide#1749]
Error: module.js:96
    throw e;
    ^

SyntaxError: Error parsing /opt/atom/resources/app/apm/node_modules/inherits/package.json: Unexpected end of JSON input
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:186:20)
    at Function.Module._resolveFilename (module.js:467:25)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/atom/resources/app/apm/node_modules/npm/lib/config/core.js:2:16)
    at Module._compile (module.js:570:32)

    at /home/simen/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (/home/simen/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)

**Comment by ivankravets** [comment]
Please manually upgrade `platformio-ide` to the latest release
