### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by TCJ-ZJ** [platformio/platformio-atom-ide#1773]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: Error: connect ETIMEDOUT 13.229.188.59:443
    at _callee$ (/Users/zhangjie46/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2679:19)
    at tryCatch (/Users/zhangjie46/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/Users/zhangjie46/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as throw] (/Users/zhangjie46/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/Users/zhangjie46/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2781:191)
    at /Users/zhangjie46/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2781:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by ivankravets** [comment]
Please try to uninstall and install extension again
