### ISSUE TITLE
InstallationError

### ISSUE THREAD

**Issue by Sin4wd** [platformio/platformio-atom-ide#1777]
I'm hardly trying to install platformio-ide on atom but always get error.
I tried uninstalling and installing again still it doesn't work. (even deleted every single thing related to atom and reinstall)
I'm using windows10 on surface pro4 with 8Gb ram but during installation I get this error:
`RangeError: Maximum call stack size exceeded
    at String.slice (native)
    at Object.resolve (path.js:290:29)
    at Object._makeLong (path.js:664:32)
    at fs.mkdirSync (fs.js:895:35)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at sync (C:\Users\war\.atom\packages\platformio-ide\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\war\.atom\packages\platformio-ide\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\war\.atom\packages\platformio-ide\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\war\.atom\packages\platformio-ide\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\war\.atom\packages\platformio-ide\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\war\.atom\packages\platformio-ide\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\war\.atom\packages\platformio-ide\node_modules\mkdirp\index.js:77:24)`

**Comment by ivankravets** [comment]
Please upgrade `platformio-ide` to the latest version. Should be fixed.
