### ISSUE TITLE
C/C++ project index rebuild failed : it is VERY VERY difficult to work with different library versions

### ISSUE THREAD

**Issue by gnkarn** [platformio/platformio-atom-ide#1778]
Error: Traceback (most recent call last):
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 35, in __init__
    self._gather_tplvars()
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 151, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "/Users/Gus-nuevo/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 75, in get_project_build_data
    raise result.exception
OSError: [Errno 13] Permission denied: '/Volumes/D5-INFO1/github/Multi-IrControl/.piolibdeps/IRremoteESP8266_ID1089'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

just changing a library location , all sorts of errors started , ( i have two project branches) , by making a change on one branch, then errors , started on both branches . After redoing and leaving everything as it was originally,  the error was not cleared , and remains  ( on both branches !) .

**Comment by gnkarn** [comment]
how to include  different library versions , on two different branches of the same project?

**Comment by ivankravets** [comment]
Please check your permissions. Also, try to remove `/Volumes/D5-INFO1/github/Multi-IrControl/.piolibdeps/` manually.
