### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by manchinesmith** [platformio/platformio-atom-ide#1800]
PIP: Traceback (most recent call last):
  File "C:\Users\jason\.platformio\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\jason\.platformio\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\jason\.platformio\penv\Scripts\pip.exe\__main__.py", line 5, in <module>
ImportError: No module named _internal

**Comment by ivankravets** [comment]
Fixed in v2.1.5. Please update and retest.
