### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by SergioSerrao** [platformio/platformio-atom-ide#1801]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\sserrao\.platformio\.cache\tmp-85120fO2iyOEyQnh\virtualenv-15.2.0\virtualenv.py", line 2349, in <module>
    main()
  File "C:\Users\sserrao\.platformio\.cache\tmp-85120fO2iyOEyQnh\virtualenv-15.2.0\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "C:\Users\sserrao\.platformio\.cache\tmp-85120fO2iyOEyQnh\virtualenv-15.2.0\virtualenv.py", line 953, in create_environment
    download=download,
  File "C:\Users\sserrao\.platformio\.cache\tmp-85120fO2iyOEyQnh\virtualenv-15.2.0\virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\sserrao\.platformio\.cache\tmp-85120fO2iyOEyQnh\virtualenv-15.2.0\virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\sserrao\.pl...v\Scripts\python.exe - setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please upgrade to `platformio-ide` 2.1.5, should be fixed. 
Please reopen if you still need help.
