### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mfonte** [platformio/platformio-atom-ide#1819]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/mmqmf/.platformio/.cache/tmp-9664NLklZg39MDyK/virtualenv-15.2.0/virtualenv.py", line 2349, in <module>
    main()
  File "/Users/mmqmf/.platformio/.cache/tmp-9664NLklZg39MDyK/virtualenv-15.2.0/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/Users/mmqmf/.platformio/.cache/tmp-9664NLklZg39MDyK/virtualenv-15.2.0/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/mmqmf/.platformio/.cache/tmp-9664NLklZg39MDyK/virtualenv-15.2.0/virtualenv.py", line 1239, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/opt/python/bin/python2.7'

**Comment by ivankravets** [comment]
Should be fixed in the latest release.
