### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Error: Detected unknown package 'tool-pioplus'

### ISSUE THREAD

**Issue by daveindustries** [platformio/platformio-atom-ide#1826]
Got an issue that stops the PlatformIO home tab from loading in Atom.
 
[Enter steps to reproduce:]

1. Open Atom
2. Menu: PlatformIO > PlatformIO Home.
3.Hang.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: Could not start PIO Home server: Error: Detected unknown package 'tool-pioplus'

```
At /Users/------------/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1

Error: Could not start PIO Home server: Error: Detected unknown package 'tool-pioplus'

    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:25227
    at ChildProcess.m (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:6013)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -0:23.7.0 platformio-ide:home (div.panels-item)
     -0:14.2.0 platformio-ide:maintenance.update-platformio (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.20 
git-plus 7.10.2 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.1 
platomformio 0.7.1 
tool-bar 1.1.7 
```

**Comment by daveindustries** [comment]
Was running an old version of PlatformIO *facepalm*
