### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by luxudng** [platformio/platformio-atom-ide#1836]
Error: Error: Error: Failed to download file https://github.com/IntoYun/intoyuniot-examples/tarball/master: Error: socket hang up
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Administrator/.atom/packages/intoyuniot-ide/lib/installer/stages/project-examples.js:157:13)
    at Generator.throw (<anonymous>)
    at step (C:\Users\apple\Desktop\LoRa\IntoYun\驱动及开发工具\开发工具\atom-x64-windows\.atom\packages\intoyuniot-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please upgrade Atom and this extension.
