### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by c1pher-cn** [platformio/platformio-atom-ide#1848]
Virtualenv Create: Traceback (most recent call last):
  File "C:\.platformio\.cache\tmp-6424DArICuS0kBqA\virtualenv-15.2.0\virtualenv.py", line 2349, in <module>
    main()
  File "C:\.platformio\.cache\tmp-6424DArICuS0kBqA\virtualenv-15.2.0\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "C:\.platformio\.cache\tmp-6424DArICuS0kBqA\virtualenv-15.2.0\virtualenv.py", line 953, in create_environment
    download=download,
  File "C:\.platformio\.cache\tmp-6424DArICuS0kBqA\virtualenv-15.2.0\virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\.platformio\.cache\tmp-6424DArICuS0kBqA\virtualenv-15.2.0\virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\.platformio\penv\Scripts\python.exe - setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please upgrade to `platformio-ide` 2.1.5, should be fixed. 
Please reopen if you still need help.
