### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Hiplce** [platformio/platformio-atom-ide#1873]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.2.0.tar.gz: Error: EPERM: operation not permitted, open 'C:\Users\Hiplce\.platformio\.cache\virtualenv.tar.gz'
    at C:\Users\Hiplce\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:10073
    at P (C:\Users\Hiplce\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:32023)
    at Generator._invoke (C:\Users\Hiplce\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:31811)
    at Generator.e.(anonymous function) [as throw] (C:\Users\Hiplce\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:32202)
    at n (C:\Users\Hiplce\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:11697)
    at C:\Users\Hiplce\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:11816
    at <anonymous>

**Comment by ivankravets** [comment]
Please upgrade Atom and this extension.
