### ISSUE TITLE
Could not upgrade PlatformIO IDE to the latest development version.

### ISSUE THREAD

**Issue by 2610** [platformio/platformio-atom-ide#1883]
Error: Couldn't clone https://github.com/platformio/platformio-atom-ide.git or git+ssh://git@github.com/platformio/platformio-atom-ide.git

    at utils.runAPMCommand.busyTitle (/Users/home/.atom/packages/platformio-ide/lib/installer/helpers.js:225:11)
    at onExit (/Users/home/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/home/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Users/home/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Users/home/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:280:15)
    at Socket.stream.on (/Users/home/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)

**Comment by ivankravets** [comment]
Please uninstall `platformio-ide` extension and install again.
