### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by zhora15** [platformio/platformio-atom-ide#1904]
Error: Traceback (most recent call last):
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 92, in cli
    init_base_project(project_dir)
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 143, in init_base_project
    lib_dir = util.get_projectlib_dir()
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 272, in get_projectlib_dir
    return get_project_optional_dir("lib_dir", join(get_project_dir(), "lib"))
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 197, in get_project_optional_dir
    config = load_project_config()
  File "/home/zhora/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 334, in load_project_config
    cp.read(path)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: /home/zhora/Documents/PlatformIO/Projects/feeder/platformio.ini
	[line 16]: 'Ds1307\n'
	[line 17]: '115\n'
	[line 18]: '38\n'
	[line 19]: '161;sd\n'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/commit/a9577bc0ba41bfe8fb82fe8d316d3f699017beaa
