### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: Error: Detected unknown package 'contrib-piohome'

### ISSUE THREAD

**Issue by Iochhi** [platformio/platformio-atom-ide#1923]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.4

### Stack Trace

Uncaught Error: Could not start PIO Home server: Error: Detected unknown package 'contrib-piohome'

```
At /Users/carlos/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1

Error: Could not start PIO Home server: Error: Detected unknown package 'contrib-piohome'

    at /packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:25227
    at ChildProcess.m (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:6013)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
compare-files 0.8.1 
file-icons 2.1.21 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.4 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.2 
split-diff 1.5.2 
tool-bar 1.1.7 
```

**Comment by Iochhi** [comment]
Thanks a lots

Atentamente
Carlos

El 20-06-2018, a la(s) 14:25, Ivan Kravets <notifications@github.com<mailto:notifications@github.com>> escribió:


Please upgrade platformio-ide to 2.1.5 and restart Atom
