### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jnherm** [platformio/platformio-atom-ide#1945]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.27.2
PIO IDE: v2.1.6
System: Darwin, 17.6.0, x64

# Exception
```
Virtualenv Create: Traceback (most recent call last):
  File "/Users/irmamontero/.platformio/.cache/tmp-881miT0SXD5LEcO/virtualenv-16.0.0/virtualenv.py", line 2343, in <module>
    main()
  File "/Users/irmamontero/.platformio/.cache/tmp-881miT0SXD5LEcO/virtualenv-16.0.0/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/Users/irmamontero/.platformio/.cache/tmp-881miT0SXD5LEcO/virtualenv-16.0.0/virtualenv.py", line 947, in create_environment
    download=download,
  File "/Users/irmamontero/.platformio/.cache/tmp-881miT0SXD5LEcO/virtualenv-16.0.0/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Users/irmamontero/.platformio/.cache/tmp-881miT0SXD5LEcO/virtualenv-16.0.0/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/irmamontero/....rmio/penv/bin/python - setuptools pip wheel failed with error code 1

```

**Comment by ivankravets** [comment]
Please upgrade to v2.1.7 via Atom > Settings > Updates. Should be fixed.
