### ISSUE TITLE
Could not upgrade PlatformIO IDE to the latest development version.

### ISSUE THREAD

**Issue by 2610** [platformio/platformio-atom-ide#1948]
Error: Couldn't clone https://github.com/platformio/platformio-atom-ide.git or git+ssh://git@github.com/platformio/platformio-atom-ide.git

    at utils.runAPMCommand.busyTitle (/Users/home/.atom/packages/platformio-ide/lib/installer/helpers.js:225:11)
    at onExit (/Users/home/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/home/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Users/home/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (/Users/home/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please navigate to Atom > Settings > Packages and search for `platformio-ide`. Uninstall it and install again.
