### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by SmallmanProject** [platformio/platformio-atom-ide#1949]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.6
System: Windows_NT, 10.0.17134, x64

# Exception
```
Error: 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp http 200 https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp http GET https://atom.io/download/electron/v2.0.3/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v2.0.3/win-x64/iojs.lib
gyp http GET https://atom.io/download/electron/v2.0.3/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.3/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v2.0.3/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v2.0.3/win-x86/iojs.lib
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\005263\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\005263\\AppData\\Local\\atom\\app-1.28.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=2.0.3" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\005263\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 


    at file:///C:/Users/005263/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/005263/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment]
Please upgrade PIO IDE via Atom > Settings > Updates
