### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by AllStuffLinux** [platformio/platformio-atom-ide#1958]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Traceback (most recent call last):
  File "main.py", line 16, in init main
  File "cmd_debug.py", line 24, in init cmd_debug
  File "C:\Users\wjcau\.platformio\packages\contrib-pysite\twisted\internet\protocol.py", line 17, in <module>
    from twisted.python import log, failure, components
  File "C:\Users\wjcau\.platformio\packages\contrib-pysite\twisted\python\log.py", line 26, in <module>
    from twisted.logger import (
  File "C:\Users\wjcau\.platformio\packages\contrib-pysite\twisted\logger\__init__.py", line 89, in <module>
    from ._levels import InvalidLogLevelError, LogLevel
  File "C:\Users\wjcau\.platformio\packages\contrib-pysite\twisted\logger\_levels.py", line 9, in <module>
    from constantly import NamedConstant, Names
ImportError: No module named constantly

```

**Comment by ivankravets** [comment]
Please remove `C:\Users\wjcau\.platformio\packages\contrib-pysite\` folder and restart IDE
