### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by jagdeepnaik** [platformio/platformio-atom-ide#1968]
Error: Request for package information failed: getaddrinfo ENOTFOUND atom.io atom.io:443

    at file:///C:/Users/Jagdeep/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/Jagdeep/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ivankravets** [comment]
Please upgrade manually from Atom > Settings > Updates
