### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by abedGNU** [platformio/platformio-atom-ide#1970]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Linux, 4.13.0-45-generic, x64

# Exception
```
Traceback (most recent call last):
  File "/home/abed/.platformio/penv/bin/platformio", line 11, in <module>
    load_entry_point('platformio==3.6.0a4', 'console_scripts', 'platformio')()
  File "/home/abed/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 123, in main
    maintenance.on_platformio_exception(e)
  File "/home/abed/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 64, in on_platformio_exception
    telemetry.on_exception(e)
  File "/home/abed/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 354, in on_exception
    mp = MeasurementProtocol()
  File "/home/abed/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 67, in __init__
    self['cid'] = app.get_cid()
  File "/home/abed/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 369, in get_cid
    set_state_item("cid", cid)
  File "/home/abed/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 300, in set_state_item
    data[name] = value
  File "/home/abed/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 116, in __exit__
    raise exception.HomeDirPermissionsError(util.get_home_dir())
platformio.exception.HomeDirPermissionsError: The directory `/home/abed/.platformio` or its parent directory is not owned by the current user and PlatformIO can not store configuration data.
Please check the permissions and owner of that directory.
Otherwise, please remove manually `/home/abed/.platformio` directory and PlatformIO will create new from the current user.

```

**Comment by ivankravets** [comment]
Please remove `/home/abed/.platformio` folder and restart IDE without ROOT
