### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by h124551753** [platformio/platformio-atom-ide#1972]
Error: Error: Error: Failed to download file https://github.com/IntoYun/intoyuniot-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/home/hhe/.atom/packages/intoyuniot-ide/lib/installer/stages/project-examples.js:157:13)
    at Generator.throw (<anonymous>)
    at step (/home/hhe/.atom/packages/intoyuniot-ide/lib/installer/stages/project-examples.js:13:273)
    at <anonymous>

**Comment by ivankravets** [comment]
Please upgrade Atom and this extension
