### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Batigolle** [platformio/platformio-atom-ide#1978]
# Description of problem
When I open the program, the error appears

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Error: Traceback (most recent call last):
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 92, in cli
    init_base_project(project_dir)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 149, in init_base_project
    init_lib_readme(lib_dir)
  File "c:\users\batigolle\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 157, in init_lib_readme
    with open(join(lib_dir, "readme.txt"), "w") as f:
IOError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Arduino\\libraries\\readme.txt'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================


```

**Comment by ivankravets** [comment]
Please check permissions
