### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by AiGreek** [platformio/platformio-atom-ide#1985]
# Description of problem
launc PlatformIO this morning and i don't know why, i have this error >_o

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Darwin, 17.6.0, x64

# Exception
```
Error: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/Library/Python/2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/platformio/commands/home.py", line 32, in cli
    pioplus_call(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/platformio/managers/core.py", line 106, in pioplus_call
    pioplus_path = join(get_core_package_dir("tool-pioplus"), "pioplus")
  File "/Library/Python/2.7/site-packages/platformio/managers/core.py", line 82, in get_core_package_dir
    pkg_dir = pm.get_package_dir(name, requirements)
  File "/Library/Python/2.7/site-packages/platformio/managers/package.py", line 380, in get_package_dir
    manifest = self.get_package(name, requirements, url)
  File "/Library/Python/2.7/site-packages/platformio/managers/package.py", line 348, in get_package
    for manifest in self.get_installed():
  File "/Library/Python/2.7/site-packages/platformio/managers/package.py", line 338, in get_installed
    manifest = self.load_manifest(pkg_dir)
  File "/Library/Python/2.7/site-packages/platformio/managers/package.py", line 300, in load_manifest
    src_manifest_path = self.get_src_manifest_path(pkg_dir)
  File "/Library/Python/2.7/site-packages/platformio/managers/package.py", line 271, in get_src_manifest_path
    for item in os.listdir(pkg_dir):
OSError: [Errno 13] Permission denied: '/Users/edouard/.platformio/packages/tool-avrdude'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================


```

**Comment by ivankravets** [comment]
Please remove this folder /Users/edouard/.platformio/packages/tool-avrdude and restart IDE
