### ISSUE TITLE
PlatformIO Fails to open project folders

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platformio-atom-ide#1996]
PlatformiO (in ATOM) on relaunch didn't display folders that had been there previously, and when a project folder is loaded, this is the error I receive:

Error: Traceback (most recent call last): File "c:\users\wegun.platformio\penv\lib\site-packages\platformio__main__.py", line 120, in main cli(None, None, None) File "c:\users\wegun.platformio\penv\lib\site-packages\click\core.py", line 700, in call return self.main(args, kwargs) File "c:\users\wegun.platformio\penv\lib\site-packages\click\core.py", line 680, in main rv = self.invoke(ctx) File "c:\users\wegun.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\users\wegun.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke return ctx.invoke(self.callback, ctx.params) File "c:\users\wegun.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke return callback(args, kwargs) File "c:\users\wegun.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func return f(get_current_context(), *args, kwargs) File "c:\users\wegun.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli pg = ProjectGenerator(project_dir, ide, env_name) File "c:\users\wegun.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 35, in init self._gather_tplvars() File "c:\users\wegun.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 151, in _gather_tplvars self._tplvars.update(self.get_project_build_data()) File "c:\users\wegun.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 75, in get_project_build_data raise result.exception ValueError: invalid literal for int() with base 10: ''

============================================================

An unexpected error occurred. Further steps:

Verify that you have the latest version of PlatformIO using pip install -U platformio command
Try to find answer in FAQ Troubleshooting section http://docs.platformio.org/page/faq.html
Report this problem to the developers https://github.com/platformio/platformio-core/issues
============================================================

**Comment by wegunterjr** [comment]
data corrupted.
I verified that I have the latest, but still unable to open existing projects.
WOW!  this isn't good.  Suggestions?

**Comment by wegunterjr** [comment]
I did this

> Please remove /Users/Juan/.platformio folder and restart Atom

**Comment by wegunterjr** [comment]
I had to create a new project.  The original was lost.   So, not sure if i resolved it direclty, but i have since updated and my current files have not had this problem.
