### ISSUE TITLE
Uncaught SyntaxError: Unexpected token * in JSON at position 0

### ISSUE THREAD

**Issue by felipengeletrica** [platformio/platformio-atom-ide#2003]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.13.5
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.7

### Stack Trace

Uncaught SyntaxError: Unexpected token * in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token * in JSON at position 0
    at JSON.parse (<anonymous>)
    at /packages/platformio-ide/lib/serial-monitor/command.js:65:22
    at ChildProcess.m (/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:6586)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -2:40.3.0 platformio-ide:target:upload-/Users/felipevargas/Documents/PlatformIO/Projects/TesteSerialJSONParser (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:33.5.0 platformio-ide:maintenance.serial-monitor (input.hidden-input)
     -1:59.5.0 platformio-ide:target:build (input.hidden-input)
     -1:59.5.0 platformio-ide:target:build-/Users/felipevargas/Documents/PlatformIO/Projects/TesteSerialJSONParser (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:56.9.0 platformio-ide:target:upload (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:56.9.0 platformio-ide:target:upload-/Users/felipevargas/Documents/PlatformIO/Projects/TesteSerialJSONParser (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:50.3.0 platformio-ide:maintenance.serial-monitor (input.hidden-input)
     -1:20.9.0 tabs:close-other-tabs (div.title.icon.cpp-icon.medium-blue)
     -1:19.1.0 platformio-ide:target:build (ul.list-inline.tab-bar.inset-panel)
     -1:19.1.0 platformio-ide:target:build-/Users/felipevargas/Documents/PlatformIO/Projects/TesteSerialJSONParser (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:16.2.0 platformio-ide:target:upload (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:16.2.0 platformio-ide:target:upload-/Users/felipevargas/Documents/PlatformIO/Projects/TesteSerialJSONParser (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:11.7.0 platformio-ide:maintenance.serial-monitor (div.build.tool-panel.native-key-bindings)
     -0:06.5.0 core:copy (input.hidden-input)
     -0:05.0 core:paste (input.hidden-input)
     -0:04.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-html-preview 0.2.5 
atom-python-virtualenv 1.0.2 
autocomplete-clang 0.11.5 
browser-plus 0.0.98 
build 0.70.0 
busy-signal 1.4.3 
console-panel 0.3.0 
file-icons 2.1.22 
gpp-compiler 3.0.7 
ide-java 0.8.3 
ide-python 1.0.0 
intentions 1.1.5 
language-ini 1.20.0 
language-sql-mysql 0.3.1 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
markdown-preview-plus 3.3.2 
node-debugger 1.10.1 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
python-indent 1.1.5 
script 3.18.1 
tool-bar 1.1.7 
tree-view-git-status 1.5.0 
```

**Comment by ivankravets** [comment]
Please update to 2.1.8
