### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by Kermit66** [platformio/platformio-atom-ide#2013]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.7
System: Windows_NT, 10.0.16299, x64

# Exception
```
Error: Traceback (most recent call last):
  File "main.py", line 130, in main.main
  File "c:\users\giova\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\giova\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\giova\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\giova\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\giova\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "cmd_home.py", line 801, in cmd_home.cli
  File "C:\Users\giova\.platformio\packages\contrib-pysite\twisted\internet\posixbase.py", line 495, in listenTCP
    p.startListening()
  File "C:\Users\giova\.platformio\packages\contrib-pysite\twisted\internet\tcp.py", line 980, in startListening
    raise CannotListenError(self.interface, self.port, le)
CannotListenError: Couldn't listen on 127.0.0.1:8010: [Errno 10048] Di norma � consentito un solo utilizzo di ogni indirizzo di socket (protocollo/indirizzo di rete/porta).

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to support@pioplus.com

============================================================


```

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart IDE. Everything should work now.
