### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by belalmc** [platformio/platformio-atom-ide#2040]
Error: Unable to download https://www.atom.io/api/packages/platformio-ide/versions/2.1.11/tarball: self signed certificate in certificate chain

    at file:///C:/Users/Omar/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/Omar/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ivankravets** [comment]
Please update Atom + PlatformIO IDE package to the latest version. Everything should work well.
