### ISSUE TITLE
Uncaught channel closed

### ISSUE THREAD

**Issue by akashpaira** [platformio/platformio-atom-ide#2055]
Please help me to resolve this issue. When i installed platformio-terminal and tried to run then i got this below issue. I try to solve it from the related post(i.e. post #556) but unable to figure it out.
i am using atom version 1.29.0. i have already done uninstall and reinstall several times.
 
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.4

### Stack Trace

Uncaught channel closed

```
At events.js:183

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.29.0/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.23 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.8.4 
script 3.18.1 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platformio-atom-ide-terminal
