### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/git\canon-80d-esp8266\canon-80d-esp82...

### ISSUE THREAD

**Issue by arunsoman** [platformio/platformio-atom-ide#2057]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.1.13

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Arun Soman\git\canon-80d-esp8266\canon-80d-esp8266\src\Connector.cpp'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Arun Soman\git\canon-80d-esp8266\canon-80d-esp8266\src\Connector.cpp'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at /packages/platformio-ide/lib/project/helpers.js:32:25
    at getActivePioProject (/packages/platformio-ide/lib/project/helpers.js:36:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:94:13)
    at doHighlight (/packages/platformio-ide/lib/main.js:247:43)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace.js:493:26)
```

### Commands

```
     -5:11.8.0 core:move-down (input.hidden-input)
     -5:11.2.0 core:move-right (input.hidden-input)
  3x -5:10.6.0 core:backspace (input.hidden-input)
     -5:08.5.0 core:move-right (input.hidden-input)
     -4:57.4.0 core:move-down (input.hidden-input)
  5x -4:56.6.0 core:backspace (input.hidden-input)
     -4:52 autocomplete-plus:confirm (input.hidden-input)
     -4:51.3.0 editor:newline (input.hidden-input)
     -2:56.1.0 core:move-left (input.hidden-input)
  2x -2:55.7.0 editor:newline (input.hidden-input)
     -2:44.8.0 core:backspace (input.hidden-input)
  5x -2:19.7.0 core:move-left (input.hidden-input)
  5x -2:16 core:move-right (input.hidden-input)
     -2:11.5.0 editor:newline (input.hidden-input)
     -1:52.9.0 core:backspace (input.hidden-input)
     -0:43.9.0 header-implementation:generate (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.24 
header-implementation 0.4.1 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.13 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment]
Please update Atom + PlatformIO IDE package to the latest version. Everything should work well.
