### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by MacPit69** [platformio/platformio-atom-ide#2065]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/Users/peter/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2654:19)
    at tryCatch (/Users/peter/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:832:40)
    at Generator.invoke [as _invoke] (/Users/peter/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1066:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/peter/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:884:21)
    at step (/Users/peter/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2756:191)
    at /Users/peter/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2756:361
    at <anonymous>

**Comment by ivankravets** [comment]
Fixed in the latest version 2.2.2. Please update via Atom > Settings > Updates
