### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by singaramv** [platformio/platformio-atom-ide#2076]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.27.2
PIO IDE: v2.1.8
System: Linux, 4.4.0-134-generic, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv
    at t.<anonymous> (/home/singa/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:21112)
    at P (/home/singa/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:33993)
    at Generator._invoke (/home/singa/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:33781)
    at Generator.e.(anonymous function) [as throw] (/home/singa/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:34172)
    at n (/home/singa/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:13752)
    at /home/singa/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:13871
    at <anonymous>
```

**Comment by ivankravets** [comment]
Please create it manually -> http://bit.ly/pio-core-virtualenv
