### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by yaquesfr** [platformio/platformio-atom-ide#2078]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/Users/YAQUESFR/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2668:19)
    at tryCatch (/Users/YAQUESFR/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/Users/YAQUESFR/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/YAQUESFR/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/Users/YAQUESFR/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:191)
    at /Users/YAQUESFR/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:361

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode => https://platformio.org/platformio-ide
