### ISSUE TITLE
ValueError: failed to parse CPython sys.version

### ISSUE THREAD

**Issue by alexhoffenreich** [platformio/platformio-atom-ide#2080]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.31.0
PIO IDE: v2.2.2
System: Windows_NT, 10.0.17134, x64

# Exception
```
Traceback (most recent call last):
  File "main.py", line 13, in init main
  File "C:\Users\alex-lenovi\.platformio\penv\lib\site-packages\platformio\app.py", line 25, in <module>
    import requests
  File "C:\Users\alex-lenovi\.platformio\penv\lib\site-packages\requests\__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "C:\Users\alex-lenovi\.platformio\penv\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\OpenSSL\crypto.py", line 12, in <module>
    from cryptography import x509
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\cryptography\x509\extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Users\alex-lenovi\.platformio\packages\contrib-pysite\asn1crypto\_int.py", line 52, in <module>
    if platform.python_implementation() == 'PyPy':
  File "C:\Users\alex-lenovi\.platformio\penv\lib\platform.py", line 1460, in python_implementation
    return _sys_version()[0]
  File "C:\Users\alex-lenovi\.platformio\penv\lib\platform.py", line 1422, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]'

```

**Comment by ivankravets** [comment]
1. Control Panel > Programs > Uninstall all Pythons from a system
2. Remove `C:\Users\alex-lenovi\.platformio\penv` folder
3. Install the latest Python 2.7.x => http://docs.platformio.org/en/latest/faq.html#install-python-interpreter

Restart IDE. Does it work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help
