### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by abduIkadir** [platformio/platformio-atom-ide#2081]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (C:\Users\Developer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2668:19)
    at tryCatch (C:\Users\Developer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:836:40)
    at Generator.invoke [as _invoke] (C:\Users\Developer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Developer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:888:21)
    at step (C:\Users\Developer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2770:191)
    at C:\Users\Developer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2770:361
    at <anonymous>

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode => https://platformio.org/platformio-ide
