### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by SchmidtGITHUB** [platformio/platformio-atom-ide#2097]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.32.0
PIO IDE: v2.2.2
System: Windows_NT, 10.0.17134, x64

# Exception
```
Traceback (most recent call last):
  File "C:\Users\Medion\.platformio\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Medion\.platformio\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Medion\.platformio\penv\Scripts\platformio.exe\__main__.py", line 5, in <module>
ImportError: No module named platformio.__main__

```

**Comment by ivankravets** [comment]
Please remove `C:\Users\Medion\.platformio\penv` folder and restart Atom
