### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by eugenelai** [platformio/platformio-atom-ide#2109]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.32.1
PIO IDE: v2.3.0
System: Darwin, 17.7.0, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "/Users/eugenelai/.platformio/.cache/tmp-22417P0Gze99gQR66/virtualenv-16.1.0/src/virtualenv.py", line 2462, in <module>
    main()
  File "/Users/eugenelai/.platformio/.cache/tmp-22417P0Gze99gQR66/virtualenv-16.1.0/src/virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "/Users/eugenelai/.platformio/.cache/tmp-22417P0Gze99gQR66/virtualenv-16.1.0/src/virtualenv.py", line 998, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/Users/eugenelai/.platformio/.cache/tmp-22417P0Gze99gQR66/virtualenv-16.1.0/src/virtualenv.py", line 1219, in install_python
    copy_required_modules(home_dir, symlink)
  File "/Users/eugenelai/.platformio/.cache/tmp-22417P0Gze99gQR66/virtualenv-16.1.0/src/virtualenv.py", line 1148, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/Users/eugenelai/.platformio/.cache/tmp-22417P0Gze99gQR66/virtualenv-16.1.0/src/virtualenv.py", line 411, in copyfile
    copyfileordir(src, dest, symlink)
  File "/Users/eugenelai/.platformio/.cache/tmp-22417P0Gze99gQR66/virtualenv-16.1.0/src/virtualenv.py", line 387, in copyfileordir
    shutil.copy2(src, dest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ntpath.py` and `/Users/eugenelai/.platformio/penv/lib/python2.7/ntpath.py` are the same file


    at t.value (/Users/eugenelai/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:25327)
    at <anonymous>
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
