### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by bisegni** [platformio/platformio-atom-ide#2112]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.32.2
PIO IDE: v2.3.0
System: Darwin, 18.2.0, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "/Users/bisegni/.platformio/.cache/tmp-66636Wsfe7eEciRdv/virtualenv-16.1.0/src/virtualenv.py", line 2462, in <module>
    main()
  File "/Users/bisegni/.platformio/.cache/tmp-66636Wsfe7eEciRdv/virtualenv-16.1.0/src/virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "/Users/bisegni/.platformio/.cache/tmp-66636Wsfe7eEciRdv/virtualenv-16.1.0/src/virtualenv.py", line 998, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/Users/bisegni/.platformio/.cache/tmp-66636Wsfe7eEciRdv/virtualenv-16.1.0/src/virtualenv.py", line 1197, in install_python
    mkdir(lib_dir)
  File "/Users/bisegni/.platformio/.cache/tmp-66636Wsfe7eEciRdv/virtualenv-16.1.0/src/virtualenv.py", line 378, in mkdir
    os.makedirs(path)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/bisegni/.platformio/penv/lib/python2.7'


    at t.value (/Users/bisegni/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:25327)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
