### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by guigithubcode** [platformio/platformio-atom-ide#2119]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.26.1
PIO IDE: v2.3.1
System: Linux, 4.4.0-139-generic, ia32

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "/home/g/.platformio/.cache/tmp-4054R4KD3az037W7/virtualenv-16.1.0/src/virtualenv.py", line 2462, in <module>
    main()
  File "/home/g/.platformio/.cache/tmp-4054R4KD3az037W7/virtualenv-16.1.0/src/virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "/home/g/.platformio/.cache/tmp-4054R4KD3az037W7/virtualenv-16.1.0/src/virtualenv.py", line 998, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/home/g/.platformio/.cache/tmp-4054R4KD3az037W7/virtualenv-16.1.0/src/virtualenv.py", line 1225, in install_python
    mkdir(join(lib_dir, "site-packages"))
  File "/home/g/.platformio/.cache/tmp-4054R4KD3az037W7/virtualenv-16.1.0/src/virtualenv.py", line 378, in mkdir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/g/.platformio/penv/lib/python2.7/site-packages'


    at t.value (/home/g/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:25327)
    at <anonymous>
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
