### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by berrrrrrro** [platformio/platformio-atom-ide#2120]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.33.0
PIO IDE: v2.3.1
System: Windows_NT, 6.1.7601, x64

# Exception
```
Error: PIP Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while. 
 C:\Users\Ibrahim Shikdaher\AppData\Roaming\SPB_Data\.platformio\penv\Scripts\python.exe: No module named pip

    at i.runCommand (C:\Users\Ibrahim Shikdaher\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:26217)
    at ChildProcess.h (C:\Users\Ibrahim Shikdaher\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5916)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\Ibrahim Shikdaher\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
