### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.33.0\@EmaMak...

### ISSUE THREAD

**Issue by u-siri-ous** [platformio/platformio-atom-ide#2124]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Paolne\AppData\Local\atom\app-1.33.0\@EmaMaker:SPQR-Team-2019'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Paolne\AppData\Local\atom\app-1.33.0\@EmaMaker:SPQR-Team-2019'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at /packages/platformio-ide/lib/main.js:255:25)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:349858)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:348333)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:130:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:109:12)
```

### Commands

```
  2x -9:54.6.0 core:backspace (input.hidden-input)
     -7:19.5.0 core:move-right (input.hidden-input)
     -7:17.3.0 core:move-up (input.hidden-input)
     -7:14 core:move-right (input.hidden-input)
     -7:12.7.0 core:move-left (input.hidden-input)
     -3:44.3.0 core:backspace (input.hidden-input)
  3x -3:32.7.0 platformio-ide:target:build (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.27 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
teletype 0.13.3 
tool-bar 1.1.11 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
