### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by SteamingCoax** [platformio/platformio-atom-ide#2125]
# Description of problem
After upgrading to the latest version of PlatformIO, I get an error when i open the PlatformIO home page in Atom. Any way to get around this?

<img width="1552" alt="screen shot 2018-12-19 at 11 43 02 am" src="https://user-images.githubusercontent.com/38991448/50234257-471a0f00-0383-11e9-8cb6-9effb8dbc137.png">

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.33.0
PIO IDE: v2.3.1
System: Darwin, 18.2.0, x64

# Exception
```
Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 38, in <module>
  File "<string>", line 35, in <module>
  File "<string>", line 15, in load_module
  File "<string>", line 8, in <module>
ImportError: No module named serial

    at /Users/bob/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:14992
    at ChildProcess.h (/Users/bob/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5916)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
