### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by folfger** [platformio/platformio-atom-ide#2131]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.33.1
PIO IDE: v2.2.2
System: Windows_NT, 6.1.7601, x64

# Exception
```
Error: Can not find Python Interpreter
    at t.<anonymous> (C:\Users\folfger\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:33990)
    at x (C:\Users\folfger\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:20834)
    at Generator._invoke (C:\Users\folfger\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:20622)
    at Generator.e.(anonymous function) [as next] (C:\Users\folfger\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:21013)
    at n (C:\Users\folfger\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:32216)
    at C:\Users\folfger\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1:32310
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
