### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by yasmi22r** [platformio/platformio-atom-ide#2137]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.30.0
PIO IDE: v2.1.11
System: Darwin, 17.7.0, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv
    at t.<anonymous> (/Users/ruthbayasmin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:28854)
    at P (/Users/ruthbayasmin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:15208)
    at Generator._invoke (/Users/ruthbayasmin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:14996)
    at Generator.e.(anonymous function) [as throw] (/Users/ruthbayasmin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:15387)
    at n (/Users/ruthbayasmin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:21494)
    at /Users/ruthbayasmin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:21613
    at <anonymous>
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
