### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by ie777** [platformio/platformio-atom-ide#2139]
# Description of problem
I can not log into the account. I use VSCode and Atom, Windows 10 system. When I try to log in to PIO Home, either Open, or PIO Account, or Libraries, it does not load the page, the Loading ... message hangs and the following error appears.
Previously, everything worked. But at some point it was resched. Disable all firewalls and antivirus programs. Loaded in safe mode. Distributed the Internet via a smartphone instead of a network cable. Also I reinstalled editors and PIO packages, no effect, the same error.
It is interesting that on a laptop with Windows 7 everything works well.
What could be the cause? Blocking traffic?

Error: Error: Traceback (most recent call last): File "c:.platformio\penv\lib\site-packages\platformio__main__.py", line 120, in main cli(None, None, None) File "c:.platformio\penv\lib\site-packages\click\core.py", line 700, in call return self.main(args, kwargs) File "c:.platformio\penv\lib\site-packages\click\core.py", line 680, in main rv = self.invoke(ctx) File "c:.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke return ctx.invoke(self.callback, ctx.params) File "c:.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke return callback(args, kwargs) File "c:.platformio\penv\lib\site-packages\platformio\commands\home.py", line 31, in cli pioplus_call(sys.argv[1:]) File "c:.platformio\penv\lib\site-packages\platformio\managers\core.py", line 132, in pioplus_call code = subprocess.call([pioplus_path] + args, kwargs) File "C:.platformio\python27\Lib\subprocess.py", line 168, in call return Popen(*popenargs, **kwargs).wait() File "C:.platformio\python27\Lib\subprocess.py", line 390, in init errread, errwrite) File "C:.platformio\python27\Lib\subprocess.py", line 640, in _execute_child startupinfo) WindowsError: [Error 193] %1 �� �������� ����������� Win32

# Configuration
Atom: 1.34.0
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17134, x64

# Exception
```
Error: Could not start PIO Home server: Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:58498)
    at l.default.waitUntilUsed.then.e (C:\Users\Администратор\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:15068)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ie777** [comment]
Solved problem - renamed folder C:\.platformio and reload editor
