### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by EisukeKato** [platformio/platformio-atom-ide#2146]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.30.0
PIO IDE: v2.3.1
System: Darwin, 18.2.0, x64

# Exception
```
Error: Conda Virtualenv: ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::ca-certificates-2018.12.5-0'.
AssertionError()
Attempting to roll back.


AssertionError()



    at i.runCommand (/Users/katoueisuke/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:23384)
    at ChildProcess.h (/Users/katoueisuke/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5916)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
