### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by pyjhhh** [platformio/platformio-atom-ide#2147]
Virtualenv Create: Traceback (most recent call last):
  File "D:\AICHI_ISO\MSYS2\home\home_all\.platformio\.cache\tmp-13692656tNMCEeyEh\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "D:\AICHI_ISO\MSYS2\home\home_all\.platformio\.cache\tmp-13692656tNMCEeyEh\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "D:\AICHI_ISO\MSYS2\home\home_all\.platformio\.cache\tmp-13692656tNMCEeyEh\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "D:\AICHI_ISO\MSYS2\home\home_all\.platformio\.cache\tmp-13692656tNMCEeyEh\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "D:\AICHI_ISO\Python\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'D:\\AICHI_ISO\\MSYS2\\home\\home_all\\.platformio\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
> IOError: [Errno 13] Permission denied: 

It seems like antivirus tools block PlatformIO installer.
