### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by robouden** [platformio/platformio-atom-ide#2148]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.34.0
PIO IDE: v2.3.1
System: Darwin, 18.2.0, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "/Users/rob/.platformio/.cache/tmp-6148T6XIS4pqNqdV/virtualenv-16.1.0/src/virtualenv.py", line 2462, in <module>
    main()
  File "/Users/rob/.platformio/.cache/tmp-6148T6XIS4pqNqdV/virtualenv-16.1.0/src/virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "/Users/rob/.platformio/.cache/tmp-6148T6XIS4pqNqdV/virtualenv-16.1.0/src/virtualenv.py", line 998, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/Users/rob/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/rob/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

Please use the *system* python to run this script

    at t.value (/Users/rob/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:25327)
    at <anonymous>
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
