### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents/PlatformIO/Projects/test'

### ISSUE THREAD

**Issue by BarryAlvord** [platformio/platformio-atom-ide#2154]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.2
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/barryallen/Documents/PlatformIO/Projects/test'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/home/barryallen/Documents/PlatformIO/Projects/test'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:93:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:312:43)
    at Function.simpleDispatch (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/snap/atom/212/usr/share/atom/resources/app/static/<embedded>:11:425672)
```

### Commands

```
```

### Non-Core Packages

```
atom-ftp-editor 0.5.0 
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 2.0.0 
dbg 1.6.3 
file-icons 2.1.29 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
output-panel 0.3.4 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.0 
tool-bar 1.1.11 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
