### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by chriscairns** [platformio/platformio-atom-ide#2155]
# Description of problem

Any ideas on how to resolve the following - is the host currently down?

Many thanks...

# Configuration
Atom: 1.34.0
PIO IDE: v2.3.1
System: Darwin, 17.7.0, x64

# Exception
```
Error: PIP Core:   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10e6d6090>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10e6d61d0>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10e6d6310>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10e6d6450>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10e6d6590>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/
  Could not find a version that satisfies the requirement platformio (from versions: )
No matching distribution found for platformio

    at i.runCommand (/Users/CCTV_MacPro/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:26217)
    at ChildProcess.h (/Users/CCTV_MacPro/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5916)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by chriscairns** [comment]
Little Snitch was preventing outgoing connection from  Atom!
