### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by hanif85** [platformio/platformio-atom-ide#2158]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.34.0
PIO IDE: v2.3.1
System: Linux, 4.18.0-15-generic, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "/home/hanif/.platformio/.cache/tmp-109612xmjEhhRtkv8/virtualenv-16.1.0/src/virtualenv.py", line 18, in <module>
    import base64
  File "/usr/local/lib/python2.7/base64.py", line 9, in <module>
    import struct
  File "/usr/local/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct


    at t.value (/home/hanif/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:25327)
    at <anonymous>
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
