### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.34.0\@incogn...

### ISSUE THREAD

**Issue by luisgarcia95** [platformio/platformio-atom-ide#2160]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Luis Antonio Garcia\AppData\Local\atom\app-1.34.0\@incognitosenpai:Sample'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Luis Antonio Garcia\AppData\Local\atom\app-1.34.0\@incognitosenpai:Sample'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:93:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:312:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:425634)
```

### Commands

```
 12x -9:20.8.0 core:backspace (input.hidden-input)
     -9:02.2.0 editor:newline (input.hidden-input)
  4x -7:55.8.0 core:move-up (input.hidden-input)
  3x -7:54.4.0 core:delete (input.hidden-input)
     -7:49.4.0 core:move-up (input.hidden-input)
     -0:17.7.0 core:select-all (input.hidden-input)
     -0:17.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 2.0.0 
file-icons 2.1.30 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
teletype 0.13.3 
tool-bar 1.1.11 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
