### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by Moulik21** [platformio/platformio-atom-ide#2161]
# Description of problem
Hi - I am getting this error when trying to install platformio-ide for atom. Upon restart after the installation, I am getting this error below.

# Configuration
Atom: 1.35.0-beta0
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17763, x64

# Exception
```
Error: Error: Traceback (most recent call last):
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\platformio\commands\home.py", line 31, in cli
    pioplus_call(sys.argv[1:])
  File "c:\users\moulik-laptop\.platformio\penv\lib\site-packages\platformio\managers\core.py", line 132, in pioplus_call
    code = subprocess.call([pioplus_path] + args, **kwargs)
  File "c:\users\moulik-laptop\.platformio\penv\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\users\moulik-laptop\.platformio\penv\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "c:\users\moulik-laptop\.platformio\penv\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================


    at C:\Users\Moulik-Laptop\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:14992
    at ChildProcess.h (C:\Users\Moulik-Laptop\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5916)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\Moulik-Laptop\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
