### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by WileCyot** [platformio/platformio-atom-ide#2167]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.35.1
PIO IDE: v2.3.1
System: Windows_NT, 10.0.15063, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Failed to download file https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz: Error: self signed certificate in certificate chain
    at t.value (C:\Users\mintzjb\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:25327)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode =>  https://platformio.org/platformio-ide

Does it work here?
