### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by phaalonso** [platformio/platformio-atom-ide#2170]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.27.1
PIO IDE: v2.3.1
System: Linux, 4.15.0-46-generic, x64

# Exception
```
Error: Error: Traceback (most recent call last):
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/home.py", line 31, in cli
    pioplus_call(sys.argv[1:])
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/core.py", line 125, in pioplus_call
    pioplus_path = join(get_core_package_dir("tool-pioplus"), "pioplus")
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/core.py", line 86, in get_core_package_dir
    pkg_dir = pm.get_package_dir(name, requirements)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 446, in get_package_dir
    manifest = self.get_package(name, requirements, url)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 414, in get_package
    for manifest in self.get_installed():
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 404, in get_installed
    manifest = self.load_manifest(pkg_dir)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 364, in load_manifest
    src_manifest_path = self.get_src_manifest_path(pkg_dir)
  File "/home/pedroalonso/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 335, in get_src_manifest_path
    for item in os.listdir(pkg_dir):
OSError: [Errno 13] Permission denied: '/home/pedroalonso/.platformio/packages/framework-arduinoavr'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================


    at /home/pedroalonso/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:14992
    at ChildProcess.h (/home/pedroalonso/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5916)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
