### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, 

### ISSUE THREAD

**Issue by chonuchan** [platformio/platformio-atom-ide#2175]
No practical problem, it just report an error. 

[Enter steps to reproduce:]

1. Have a file that exists in branch B opened in Atom
2. Use the Atom built-in Git to checkout at branch A, in which that file does not exist.

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'D:\Users\zeiss\Documents\PlatformIO\Tissue-force-microscopy\Force_modulator\mfile\PID_arduino.m'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'D:\Users\zeiss\Documents\PlatformIO\Tissue-force-microscopy\Force_modulator\mfile\PID_arduino.m'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:93:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:312:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1173795)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:425634)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 2.0.1 
chester-atom-syntax 0.3.2 
export-html 3.1.0 
file-icons 2.1.31 
find-list 0.3.0 
fonts 3.4.0 
goto-definition 1.3.4 
highlight-selected 0.16.0 
intentions 1.1.5 
language-ini 1.20.0 
language-latex 1.2.0 
language-matlab 0.2.1 
linter 2.3.0 
linter-gcc 0.7.1 
linter-matlab 1.1.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-autohider 1.6.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
nucleus-dark-ui 0.12.3 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
restart-atom 0.2.0 
script 3.18.1 
scroll-searcher 5.2.0 
split-diff 1.6.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
tool-bar 1.1.11 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
