### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.35.1\@mgmold...

### ISSUE THREAD

**Issue by JohnyLex** [platformio/platformio-atom-ide#2180]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Admin\AppData\Local\atom\app-1.35.1\@mgmoldova:Downloads'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Admin\AppData\Local\atom\app-1.35.1\@mgmoldova:Downloads'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:93:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:312:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1173795)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:425634)
```

### Commands

```
  2x -1:41.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.31 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
teletype 0.13.3 
tool-bar 1.1.11 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
