### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by danielPerez97** [platformio/platformio-atom-ide#2183]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.34.0
PIO IDE: v2.3.1
System: Linux, 4.14.102-1-MANJARO, x64

# Exception
```
Error: Error: Detected unknown package 'contrib-pysite'

    at /home/daniel/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:15270
    at ChildProcess.h (/home/daniel/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5904)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2341
