### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by pablo709** [platformio/platformio-atom-ide#2192]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.36.1
PIO IDE: v2.3.1
System: Linux, 4.15.0-48-generic, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: 'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "/home/pablo/.platformio/penv/lib/python2.7/site.py", line 773, in <module>
    main()
  File "/home/pablo/.platformio/penv/lib/python2.7/site.py", line 763, in main
    execsitecustomize()
  File "/home/pablo/.platformio/penv/lib/python2.7/site.py", line 553, in execsitecustomize
    import sitecustomize
  File "/usr/lib/python2.7/sitecustomize.py", line 11, in <module>
    site.USER_SITE = site.getusersitepackages()
AttributeError: 'module' object has no attribute 'getusersitepackages'

New python executable in /home/pablo/.platformio/penv/bin/python2.7
Also creating executable in /home/pablo/.platformio/penv/bin/python
ERROR: The executable /home/pablo/.platformio/penv/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/home/pablo' (should be u'/home/pablo/.platformio/penv')
ERROR: virtualenv is not compatible with this system or executable

    at t.value (/home/pablo/.var/app/io.atom.Atom/data/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:25605)
    at <anonymous>
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
