### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mannsorrow** [platformio/platformio-atom-ide#2200]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\10130\.intoyuniot\.cache-ide\tmp-12404NFhAy1wuW2Fe\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\10130\.intoyuniot\.cache-ide\tmp-12404NFhAy1wuW2Fe\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\10130\.intoyuniot\.cache-ide\tmp-12404NFhAy1wuW2Fe\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\10130\.intoyuniot\.cache-ide\tmp-12404NFhAy1wuW2Fe\virtualenv-14.0.6\virtualenv.py", line 1114, in install_python
    writefile(join(site_dir, 'orig-prefix.txt'), prefix)
  File "C:\Users\10130\.intoyuniot\.cache-ide\tmp-12404NFhAy1wuW2Fe\virtualenv-14.0.6\virtualenv.py", line 357, in writefile
    f.write(content.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 3: ordinal not in range(128)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
