### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by symonty** [platformio/platformio-atom-ide#2205]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.37.0
PIO IDE: v2.3.1
System: Darwin, 18.6.0, x64

# Exception
```
Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 38, in <module>
  File "<string>", line 39, in <module>
  File "<string>", line 18, in load_module
  File "<string>", line 23, in <module>
ImportError: cannot import name get_project_test_dir

    at /Users/symonty/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:14992
    at ChildProcess.h (/Users/symonty/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5916)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by symonty** [comment]
platform io upgrade fixed it for me.
![image](https://user-images.githubusercontent.com/1103948/58536635-ffa37480-81a5-11e9-9718-0b6662ff337c.png)
