### ISSUE TITLE
Installation failed due to missing file

### ISSUE THREAD

**Issue by pyr0ball** [platformio/platformio-atom-ide#2208]
# Description of problem
Unable to install the plaformio core on both Atom and VSCode (same exact error occurs on both)

I have tried removing the .platformio folder from the user folder, installed latest python 2.7 with path, and updated system pip to 19.x
![image](https://user-images.githubusercontent.com/8482805/58670410-ce38bf00-82f3-11e9-979a-2082e029e1ab.png)

# Configuration
Atom: 1.37.0
PIO IDE: v2.3.1
System: Windows_NT, 10.0.16299, x64

# Exception
```
Error: PIP Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while. 
 Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\users\\{username}\\.platformio\\penv\\lib\\site-packages\\pip-19.1.1.dist-info\\METADATA'


    at i.runCommand (C:\Users\alan weinstock\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:26495)
    at ChildProcess.h (C:\Users\alan weinstock\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5904)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\alan weinstock\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
