### ISSUE TITLE
Can not fetch embedded boards

### ISSUE THREAD

**Issue by ESCracker** [platformio/platformio-atom-ide#2209]
Error: Error: Traceback (most recent call last):
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\platformio\__main__.py", line 104, in main
    cli(None, None, None)
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\platformio\commands\boards.py", line 29, in cli
    return _print_boards_json(query, installed)
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\platformio\commands\boards.py", line 99, in _print_boards_json
    boards = _get_boards(installed)
  File "c:\users\escra\.intoyuniot\penv\lib\site-packages\platformio\commands\boards.py", line 88, in _get_boards
    key = "%s:%s" % (board['platform'], board['id'])
TypeError: string indices must be integers

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of intoyuniot using
  `pip install -U intoyuniot` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.intoyuniot.com/page/faq.html

* Report this problem to the developers
  https://github.com/intoyun/intoyuniot-core/issues

============================================================

    at utils.runPIOCommand.cacheValid (file:///C:/Users/ESCra/.atom/packages/intoyuniot-ide/lib/platform/helpers.js:20:25)
    at file:///C:/Users/ESCra/.atom/packages/intoyuniot-ide/lib/utils.js:89:46
    at Array.map (<anonymous>)
    at onExit (file:///C:/Users/ESCra/.atom/packages/intoyuniot-ide/lib/utils.js:89:36)
    at exit (file:///C:/Users/ESCra/.atom/packages/intoyuniot-ide/lib/utils.js:102:21)
    at n (C:\Users\ESCra\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:14:1043822)
    at ChildProcess.o.process.on.e (C:\Users\ESCra\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:14:1044028)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
