### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jmallegue** [platformio/platformio-atom-ide#2211]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.37.0
PIO IDE: v2.3.1
System: Windows_NT, 10.0.18362, x64

# Exception
```
Error: Conda Virtualenv: 
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: sentinelhub
  channel url: https://conda.anaconda.org/sentinelhub
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.



    at i.runCommand (C:\Users\jmall\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:23662)
    at ChildProcess.h (C:\Users\jmall\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5904)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\jmall\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
