### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by billettc** [platformio/platformio-atom-ide#2225]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.38.2
PIO IDE: v2.3.1
System: Darwin, 19.0.0, x64

# Exception
```
Error
    at /Users/cbillett/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:15270
    at ChildProcess.h (/Users/cbillett/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:5904)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
