### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by makihito** [platformio/platformio-atom-ide#2226]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/Users/maetaakihito/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2679:19)
    at tryCatch (/Users/maetaakihito/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/Users/maetaakihito/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/maetaakihito/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/Users/maetaakihito/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2781:191)
    at /Users/maetaakihito/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2781:361
    at <anonymous>

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode =>  https://platformio.org/platformio-ide

Does it work here?
