### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '$ATOM_HOME/init.coffee'

### ISSUE THREAD

**Issue by SGHphoto** [platformio/platformio-atom-ide#2230]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: "Manjaro Linux"
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.3.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/sgh/.atom/init.coffee'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/home/sgh/.atom/init.coffee'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:93:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:312:43)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1208024)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/usr/share/atom/resources/app/static/<embedded>:11:424362)
```

### Commands

```
```

### Non-Core Packages

```
arduino-atom 0.1.0 
arduino-toolbelt 0.1.1 
arduino-upload 1.5.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-clang 0.12.0 
build 0.70.0 
busy 0.7.0 
busy-signal 2.0.1 
console-panel 0.3.1 
file-icons 2.1.33 
intentions 1.1.5 
language-arduino 0.4.3 
language-ini 1.21.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
microbit-micropython 0.3.2 
microbit-python 0.1.6 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
platomformio 0.7.1 
stlink 0.1.1 
termination 0.7.1 
tool-bar 1.1.12 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
