### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ringmor** [platformio/platformio-atom-ide#2232]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.38.2
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17134, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src\virtualenv.py", line 2462, in <module>
    main()
  File "C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src\virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src\virtualenv.py", line 1015, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src\virtualenv.py", line 968, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src\virtualenv.py", line 854, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command C:\Users\Administrat...v\Scripts\python.exe - setuptools pip wheel failed with error code 1

New python executable in C:\Users\Administrator\.platformio\penv\Scripts\python.exe
Installing setuptools, pip, wheel...

  Complete output from command C:\Users\Administrat...v\Scripts\python.exe - setuptools pip wheel:
  Looking in links: C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src, C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src\virtualenv_support, C:\Users\Administrator\.platformio\.cache\tmp-8068TbccZefj3G1z\virtualenv-16.1.0\src\virtualenv_support
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

----------------------------------------
...Installing setuptools, pip, wheel...done.

    at t.value (C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:25605)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
