### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by HelenZhangLP** [platformio/platformio-atom-ide#2236]
at o.runCommand (C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:32049)
at ChildProcess.h (C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:6019)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
