### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:/MarlinFirmware\.pioenvs'

### ISSUE THREAD

**Issue by gandalf0098** [platformio/platformio-atom-ide#2237]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise 2016 LTSB
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.4.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\MarlinFirmware\.pioenvs'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat 'C:\MarlinFirmware\.pioenvs'
    at Proxy.realpathSync (fs.js:1744:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:1208969)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:425033)
```

### Commands

```
     -4:26 platformio-ide:target:build (input.hidden-input)
     -4:26 platformio-ide:target:build-C:\MarlinFirmware (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:44.4.0 core:copy (span.syntax--constant.syntax--other)
     -1:50.4.0 intentions:highlight (input.hidden-input)
     -1:50.1.0 core:paste (input.hidden-input)
     -1:47.2.0 platformio-ide:target:build (input.hidden-input)
     -1:47.2.0 platformio-ide:target:build-C:\MarlinFirmware (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:45.6.0 build:refresh-targets (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:08.9.0 core:cut (div.tool-panel.tree-view)
     -1:02.2.0 tree-view:remove (div.header.list-item)
     -0:54.7.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -0:54.7.0 platformio-ide:target:build-C:\MarlinFirmware (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:40.5.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:20.4.0 platformio-ide:target:build (input.hidden-input)
     -0:20.4.0 platformio-ide:target:build-C:\MarlinFirmware (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.33 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.2 
tool-bar 1.1.12 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
