### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by pestdad** [platformio/platformio-atom-ide#2240]
Error: Error: Could not find a version that satisfies the requirement '~2.34.190418' for your system 'darwin_x86_64'

at /Users/dwaynecrawford/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:17211
at ChildProcess.h (/Users/dwaynecrawford/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:6019)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
