### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by CoreCPU** [platformio/platformio-atom-ide#2248]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.39.1
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17763, x64

# Exception
```
Error: Error: Detected unknown package 'tool-pioplus'

    at C:\Users\P61684\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:15270
    at ChildProcess.h (C:\Users\P61684\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5904)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.cp.emit (C:\Users\P61684\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
