### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by BogusException** [platformio/platformio-atom-ide#2249]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/closet/home/pat/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2660:19)
    at tryCatch (/closet/home/pat/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/closet/home/pat/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/closet/home/pat/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/closet/home/pat/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2762:191)
    at /closet/home/pat/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2762:361

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
