### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by urevoleg** [platformio/platformio-atom-ide#2257]
PIP:   Cache entry deserialization failed, entry ignored
c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Exception:
Traceback (most recent call last):
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\wheel.py", line 747, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\req\req_set.py", line 359, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\req\req_set.py", line 576, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\download.py", line 809, in unpack_url
    hashes=hashes
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\download.py", line 648, in unpack_http_url
    hashes)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\download.py", line 841, in _download_http_url
    stream=True,
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\download.py", line 377, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
c:\users\urev\.platformio\penv\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
