### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\PlatformIO\Projects\190826-...

### ISSUE THREAD

**Issue by andre-eng** [platformio/platformio-atom-ide#2258]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.4.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Administrador\Documents\PlatformIO\Projects\190826-105336-arduino-blink'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat 'C:\Users\Administrador\Documents\PlatformIO\Projects\190826-105336-arduino-blink'
    at Object.realpathSync (fs.js:1744:7)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at /packages/platformio-ide/lib/services/build.js:22:26)
    at /packages/build/lib/target-manager.js:67:22
    at Array.map (<anonymous>)
    at /packages/build/lib/target-manager.js:67:10
    at Array.map (<anonymous>)
    at TargetManager.refreshTargets (/packages/build/lib/target-manager.js:58:39)
    at TargetManager.getTargets (/packages/build/lib/target-manager.js:220:19)
    at Object.startNewBuild (/packages/build/lib/build.js:111:40)
    at /packages/build/lib/build.js:270:14
    at saveAndContinue (/packages/build/lib/build.js:277:7)
    at Object.doSaveConfirm (/packages/build/lib/build.js:281:7)
    at Object.build (/packages/build/lib/build.js:264:10)
    at /packages/build/lib/build.js:64:62)
    at TargetManager.emit (events.js:182:13)
    at /packages/build/lib/target-manager.js:114:127)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at Object.runAtomCommand (/packages/platformio-ide/lib/utils.js:52:24)
    at /packages/platformio-ide/lib/main.js:258:30)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:134:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
     -7:32.2.0 tree-view:remove (div.header.list-item.project-root-header)
  4x -7:23.7.0 build:select-active-target (div.tool-panel.tree-view)
     -7:03.2.0 build:trigger (div.tool-panel.tree-view)
  2x -6:29 tree-view:remove (span.name.icon.icon-file-directory)
  2x -6:23.3.0 tree-view:open-selected-entry (div.tool-panel.tree-view)
     -6:15.7.0 platformio-ide:target:clean (div.tool-panel.tree-view)
     -6:05.5.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -6:05.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:00.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -6:00.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:53.8.0 tree-view:remove-project-folder (span.name.icon.atom-icon)
     -5:53.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:46.7.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -5:19.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34.2.0 platformio-ide:target:build (div.build.tool-panel.native-key-bindings)
     -0:34.2.0 platformio-ide:target:build-C:\Users\Administrador\Documents\PlatformIO\Projects\190826-154805-arduino-blink (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
build-platformio 1.2.4 
busy-signal 2.0.1 
file-icons 2.1.35 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-aia 0.0.5 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
tool-bar 1.1.12 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
