### ISSUE TITLE
LDC12

### ISSUE THREAD

**Issue by LDC12** [platformio/platformio-atom-ide#2262]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dataset' of null

```
At C:\Users\hands\.atom\packages\platformio-ide\lib\maintenance.js:109

TypeError: Cannot read property 'dataset' of null
    at /packages/platformio-ide/lib/maintenance.js:109:57
    at Array.forEach (<anonymous>)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:105:8)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:425706)
```

### Commands

```
     -8:58.3.0 build:toggle-panel (div.tool-panel.tree-view)
     -2:16.6.0 platformio-ide:home (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.35 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-ui-default 1.8.0 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
process-palette 0.17.0 
tool-bar 1.1.12 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
