### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'G:/big tree tech\marlin\Marlin-bugfix-2...

### ISSUE THREAD

**Issue by jklworkz** [platformio/platformio-atom-ide#2263]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.4.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'G:\big tree tech\marlin\Marlin-bugfix-2.0.x\Marlin\Configuration.h'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat 'G:\big tree tech\marlin\Marlin-bugfix-2.0.x\Marlin\Configuration.h'
    at Proxy.realpathSync (fs.js:1744:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at /packages/platformio-ide/lib/main.js:249:25)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:134:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
undefined -6:26.7.0 intentions:highlight (input.hidden-input)
  2x -6:22.9.0 core:undo (input.hidden-input)
  7x -6:16.1.0 intentions:highlight (input.hidden-input)
     -6:15.4.0 core:paste (input.hidden-input)
  9x -6:11.2.0 core:backspace (input.hidden-input)
     -5:55.4.0 platformio-ide:target:build (input.hidden-input)
     -5:55.4.0 platformio-ide:target:build-G:\big tree tech\marlin\Marlin-bugfix-2.0.x (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:50.9.0 build:refresh-targets (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:44.7.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -4:44.7.0 platformio-ide:target:build-G:\big tree tech\marlin\Marlin-bugfix-2.0.x (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:34.2.0 platformio-ide:target:build (div.build.tool-panel.native-key-bindings)
     -1:34.2.0 platformio-ide:target:build-G:\big tree tech\marlin\Marlin-bugfix-2.0.x (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:23 build:trigger (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:13.8.0 platformio-ide:target:build (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:13.8.0 platformio-ide:target:build-G:\big tree tech\marlin\Marlin-bugfix-2.0.x (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:15.4.0 platformio-ide:target:build (div.tool-panel.tree-view)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.35 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-ui-default 1.8.0 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
tool-bar 1.1.12 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
