### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by aslu25** [platformio/platformio-atom-ide#2264]
at t.value (C:\Users\msmas.DESKTOP-036PT7J\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:31332)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
