### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.40.1\@khaluk...

### ISSUE THREAD

**Issue by uguroztrk** [platformio/platformio-atom-ide#2270]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.4.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\ugur\AppData\Local\atom\app-1.40.1\@khaluk:LYK_ULTRASONIC'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat 'C:\Users\ugur\AppData\Local\atom\app-1.40.1\@khaluk:LYK_ULTRASONIC'
    at Proxy.realpathSync (fs.js:1744:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:425706)
```

### Commands

```
     -9:11.4.0 editor:newline (input.hidden-input)
 12x -8:58.4.0 core:backspace (input.hidden-input)
     -7:10.7.0 intentions:highlight (input.hidden-input)
     -7:10.5.0 core:save (input.hidden-input)
     -6:22.3.0 core:paste (input.hidden-input)
  6x -5:40 core:backspace (input.hidden-input)
     -4:53.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -4:52.9.0 core:backspace (input.hidden-input)
     -4:20.4.0 editor:select-to-first-character-of-line (input.hidden-input)
     -4:19.6.0 core:backspace (input.hidden-input)
     -3:48 editor:select-to-first-character-of-line (input.hidden-input)
 18x -3:47.3.0 core:backspace (input.hidden-input)
     -2:36.4.0 editor:select-to-first-character-of-line (input.hidden-input)
     -2:35.9.0 core:backspace (input.hidden-input)
     -1:02.8.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:02.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.35 
git-plus 8.7.1 
intentions 1.1.5 
language-ini 1.22.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-ui-default 1.8.0 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
script 3.18.1 
teletype 0.13.4 
tool-bar 1.1.12 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
