### ISSUE TITLE
Uncaught TypeError: i.default.isFileSync is not a function

### ISSUE THREAD

**Issue by hobgoblin-sudo** [platformio/platformio-atom-ide#2292]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.4.1

### Stack Trace

Uncaught TypeError: i.default.isFileSync is not a function

```
At C:\Users\hobgo\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1

TypeError: i.default.isFileSync is not a function
    at Object.t.isPIOProject (/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4689)
    at /packages/platformio-ide/lib/utils.js:87:38
    at Array.filter (<anonymous>)
    at getPioProjects (/packages/platformio-ide/lib/utils.js:87:6)
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:92:17)
    at /packages/platformio-ide/lib/main.js:249:25)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:139:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
     -0:13.5.0 platformio-ide:target:build (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
build-platformio 1.2.4 
build-processing 0.1.2 
busy-signal 2.0.1 
file-icons 2.1.36 
ide-clangd 0.4.0 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-ui-default 1.8.0 
platformio-aia 0.0.5 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
platomformio 0.7.1 
process-palette 0.17.0 
search-platform-dependent-characters 0.3.0 
tool-bar 1.2.0 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
