### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by farriermatt** [platformio/platformio-atom-ide#2293]
eternal spinner/disc
i am following a utube video and so far have not got further than this error.
Start PIO Home Server

Error: Error: Detected unknown package 'contrib-pysite'

at /Users/Administrator/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:17820
at ChildProcess.h (/Users/Administrator/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:6292)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Start PIO Home Server

Error: Error: Detected unknown package 'contrib-pysite'

at /Users/Administrator/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:17820
at ChildProcess.h (/Users/Administrator/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:6292)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
Any ideas please?

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
