### ISSUE TITLE
Start PIO Home Server - can't install contrib-piohome with version requirements

### ISSUE THREAD

**Issue by colinl** [platformio/platformio-atom-ide#2294]
Trying to use platformio-ide with atom,  on new system with Ubuntu 19.10 (just released). After the restart following installing the package I get
```
Error: Error: Could not install 'contrib-piohome' with version requirements '^2.3.2' for your system 'linux_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

at /home/colinl/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:17820
at ChildProcess.h (/home/colinl/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:6292)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Socket.stream.socket.on (internal/child_process.js:380:11)
at Socket.emit (events.js:182:13)
at Pipe._handle.close [as _onclose] (net.js:596:12)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
