### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mountaindude** [platformio/platformio-atom-ide#230]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/b1/d_tydw054s13bhlq4cwn99hh0000gn/T/tmp-83814XxPqm8Qq93xs/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/var/folders/b1/d_tydw054s13bhlq4cwn99hh0000gn/T/tmp-83814XxPqm8Qq93xs/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/var/folders/b1/d_tydw054s13bhlq4cwn99hh0000gn/T/tmp-83814XxPqm8Qq93xs/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/goran/.atom/packages/platformio-ide/penv/bin/../lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/Users/goran/.atom/packages/platformio-ide/penv/bin/../lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment]
Please provide next information:

1. macOS version
2. Python version: `$ python --version`
3. Python location: `$ which python`

**Comment by mountaindude** [comment]
macOS Sierra 10.12.1
python 2.7.13
/usr/local/bin/python

After a restart of Atom all seems to be ok though - maybe it was just a installation issue that sorted itself...

**Comment by ivankravets** [comment]
Please reopen if you will see this issue in future.
