### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by drkline** [platformio/platformio-atom-ide#2306]
Hello,
I can't get rid of this error...
Error: Error: Detected unknown package 'contrib-pysite'
at C:\Users\Dave\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:17820
at ChildProcess.h (C:\Users\Dave\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:6292)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\Dave\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

I'm new to Atom and am having problems finding answers for this online.  Any help would be appreciated.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
