### ISSUE TITLE
Uncaught Fehler: ENOENT: keine solche Datei oder Verzeichnis, lstat '/Desktop'Marlin'BIGTREETECH-SKR-PRO-V1...

### ISSUE THREAD

**Issue by matloch15** [platformio/platformio-atom-ide#2309]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: DESKTOP-SUUPF45
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.5.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Waldemar Matloch\Desktop\Marlin\BIGTREETECH-SKR-PRO-V1.1-master\firmware\Marlin-2.0.x-SKR-Pro\.pio\build\BIGTREE_SKR_PRO\firmware.bin'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\Waldemar Matloch\Desktop\Marlin\BIGTREETECH-SKR-PRO-V1.1-master\firmware\Marlin-2.0.x-SKR-Pro\.pio\build\BIGTREE_SKR_PRO\firmware.bin'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:425990)
```

### Commands

```
  2x -9:54.7.0 tree-view:copy (span.name.icon.binary-icon)
     -4:24.3.0 tree-view:duplicate (span.name.icon.binary-icon)
     -3:51.1.0 tree-view:open-selected-entry-left (span.name.icon.binary-icon)
     -3:32.1.0 process-palette:PIO Upload (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-auto-programming 0.1.2 
autocomplete-clang 0.12.0 
build 0.70.0 
build-platformio 1.2.4 
busy-signal 2.0.1 
file-icons 2.1.36 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-gcc2 0.8.7 
linter-ui-default 1.8.0 
platformio-aia 0.0.5 
platformio-ide 2.5.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
platomformio 0.7.1 
process-palette 0.17.0 
template-syntax 0.3.0 
tool-bar 1.2.0 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
