### ISSUE TITLE
Uncaught TypeError: event.stopPropagation is not a function

### ISSUE THREAD

**Issue by mashu** [platformio/platformio-atom-ide#231]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Debian GNU/Linux
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-alpha.6

### Stack Trace

Uncaught TypeError: event.stopPropagation is not a function

```
At /home/mateusz/.atom/packages/platformio-ide/lib/libraries/components/storage-view.js:66

TypeError: event.stopPropagation is not a function
    at LibStorageView.onDidReveal (/packages/platformio-ide/lib/libraries/components/storage-view.js:66:11)
    at HTMLAnchorElement.onclick (/packages/platformio-ide/lib/libraries/components/storage-view.js:84:90)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.10.0 
build 0.67.0 
busy 0.7.0 
file-icons 2.0.15 
language-ini 1.18.0 
linter 1.11.23 
linter-gcc 0.7.1 
minimap 4.26.8 
platformio-aia 0.0.5 
platformio-ide 2.0.0-alpha.6 
platformio-ide-terminal 2.3.0 
tool-bar 1.0.1 
```

**Comment by ivankravets** [comment]
Thanks a lot for the report!
