### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by biazzotto** [platformio/platformio-atom-ide#232]
User's Virtualenv: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>

    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main

    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment

    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess

    % (cmd_desc, proc.returncode))
OSError: Command /home/biazzotto/.ato...e/penv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1

**Comment by ivankravets** [comment]
Please test it with
```
apm uninstall platformio-ide
apm install --production platformio/platformio-atom-ide
```
