### ISSUE TITLE
Uninstall incompatible packages: platformio-ide-terminal

### ISSUE THREAD

**Issue by kanatos-kun** [platformio/platformio-atom-ide#2326]
hi i've got this message : 
`
Error: Failed to delete platformio-ide-terminal: No package.json found at C:\Users\Geoffrey.atom\packages\platformio-ide-terminal\package.json`

```

at file:///C:/Users/Geoffrey/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:139:25
at file:///C:/Users/Geoffrey/.atom/packages/platformio-ide/lib/utils.js:67:7
at ChildProcess.h (C:\Users\Geoffrey\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:6292)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\Geoffrey\.atom\packages\prettier-atom\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

i can't uninstall platform-ide-terminal

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
