### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by josegordon** [platformio/platformio-atom-ide#2328]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/Volumes/Macintosh Datos/Users/jgordon/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2668:19)
    at tryCatch (/Volumes/Macintosh Datos/Users/jgordon/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/Volumes/Macintosh Datos/Users/jgordon/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/Volumes/Macintosh Datos/Users/jgordon/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/Volumes/Macintosh Datos/Users/jgordon/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:191)
    at /Volumes/Macintosh Datos/Users/jgordon/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:361
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
