### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by willyflies1** [platformio/platformio-atom-ide#2334]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (C:\Users\willi\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2668:19)
    at tryCatch (C:\Users\willi\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:836:40)
    at Generator.invoke [as _invoke] (C:\Users\willi\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\willi\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:888:21)
    at step (C:\Users\willi\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2770:191)
    at C:\Users\willi\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:2770:361
    at <anonymous>

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
