### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by CKMartens** [platformio/platformio-atom-ide#2343]
PlatformIO Core didn't install

I use Windows 10 1903 Build 18362.472. Atom 1.41.0 for x64 systems. Phyton 3.8 for win

```
at s.runCommand (C:\Users\carst\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:35177)
at ChildProcess.d (C:\Users\carst\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:8308)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\carst\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
