### ISSUE TITLE
Installing platform-ide or platform-ide-terminal causes indefinite installation.

### ISSUE THREAD

**Issue by brianscottwilson** [platformio/platformio-atom-ide#2345]
I'm new to Atom, but my department's team uses it and likes it.  I'm trying to install the platform-ide plugins on a Mac (Mojave) workstation and this appears to install the platform-ide-terminal plugin.  Unfortunately, the platform-ide-terminal installation hangs indefinitely and makes Atom hang on startup.

When I tried to install manually, I get the following error on trying to install the platform-ide-terminal.  It seems there is a **self signed certificate** being used as part of the process and that isn't working.

The other dependencies all seem to install with no issues as do other plugins, only the platform-ide-terminal seems to have a problem.  

The work around I've found for the moment is to go to the ~/.atom/packages directory and remove the platform-ide* subdirectories.  While this allows me to use Atom, I have no terminal commands available and that's a bit of a pain in the anatomy.  **Does anyone have a better work around?**

```
$ apm install platformio-ide-debugger
Installing platformio-ide-debugger to /Users/bxw85a3/.atom/packages ✓
$ apm install autocomplete-clang
Installing autocomplete-clang to /Users/bxw85a3/.atom/packages ✓
$ apm install linter-ui-default
Installing linter-ui-default to /Users/bxw85a3/.atom/packages ✓
$ apm install intentions
Installing intentions to /Users/bxw85a3/.atom/packages ✓
$ apm install intentions
Installing intentions to /Users/bxw85a3/.atom/packages ✓
$ apm install linter
Installing linter to /Users/bxw85a3/.atom/packages ✓
$ apm install linter-gcc
Installing linter-gcc to /Users/bxw85a3/.atom/packages ✓
$ apm install language-ini
Installing language-ini to /Users/bxw85a3/.atom/packages ✓
$ apm install tool-bar
Installing tool-bar to /Users/bxw85a3/.atom/packages ✓
$ apm install file-icons
Installing file-icons to /Users/bxw85a3/.atom/packages ✓
$ apm install build-platformio
Installing build-platformio to /Users/bxw85a3/.atom/packages ✓
$ apm install build
Installing build to /Users/bxw85a3/.atom/packages ✓
$ apm install platformio-ide-terminal
Installing platformio-ide-terminal to /Users/bxw85a3/.atom/packages ✗

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /private/var/folders/1l/41j8fsys3ds6f5356d08fv5h0000gn/T/apm-install-dir-1191111-19511-1lat50k.cidpj/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

prebuild-install WARN install self signed certificate in certificate chain
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:635:8)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/private/var/folders/1l/41j8fsys3ds6f5356d08fv5h0000gn/T/AppTranslocation/355F5BE1-C904-4684-BA03-3A16D18D2E49/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/1l/41j8fsys3ds6f5356d08fv5h0000gn/T/AppTranslocation/355F5BE1-C904-4684-BA03-3A16D18D2E49/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/1l/41j8fsys3ds6f5356d08fv5h0000gn/T/apm-install-dir-1191111-19511-1lat50k.cidpj/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/1l/41j8fsys3ds6f5356d08fv5h0000gn/T/apm-install-dir-1191111-19511-1lat50k.cidpj/package.json'
npm WARN apm-install-dir-1191111-19511-1lat50k.cidpj No description
npm WARN apm-install-dir-1191111-19511-1lat50k.cidpj No repository field.
npm WARN apm-install-dir-1191111-19511-1lat50k.cidpj No README data
npm WARN apm-install-dir-1191111-19511-1lat50k.cidpj No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bxw85a3/.atom/.apm/_logs/2019-12-11T15_20_50_185Z-debug.log
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
