### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Tasmota/tasmota/user_config_override.h'

### ISSUE THREAD

**Issue by kskenyon** [platformio/platformio-atom-ide#2346]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/private/Tasmota/tasmota/user_config_override.h'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/Users/private/Tasmota/tasmota/user_config_override.h'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:425990)
```

### Commands

```
     -6:08.3.0 tree-view:duplicate (span.name.icon.c-icon)
  7x -6:04.9.0 core:backspace (input.hidden-input)
     -6:01.9.0 core:confirm (input.hidden-input)
     -4:55.9.0 autocomplete-plus:confirm (input.hidden-input)
     -4:55 core:save (input.hidden-input)
     -4:37.3.0 platformio-ide:target:clean (div.tool-panel.tree-view)
     -4:37.3.0 platformio-ide:target:clean-/Users/private/Tasmota (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -2:47.2.0 tree-view:remove (span.name.icon.c-icon)
     -0:12.3.0 tree-view:duplicate (span.name.icon.c-icon)
     -0:08.1.0 core:move-left (input.hidden-input)
  7x -0:07.6.0 core:backspace (input.hidden-input)
     -0:05.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-clang 0.12.1 
build 0.70.0 
busy 0.7.0 
busy-signal 2.0.1 
file-icons 2.1.36 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-gcc2 0.8.7 
linter-ui-default 1.8.0 
minimap 4.29.9 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.0 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
