### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by micromender** [platformio/platformio-atom-ide#2365]
Error: PIP Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while. ERROR: Error [WinError 87] The parameter is incorrect while executing command python setup.py egg_info ERROR: Could not install packages due to an EnvironmentError: [WinError 87] The parameter is incorrect

WARNING: You are using pip version 19.2.3, however version 20.0.2 is available. You should consider upgrading via the 'python -m pip install --upgrade pip' command.

at s.runCommand (C:\Users\Win7-Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:35177)
at ChildProcess.d (C:\Users\Win7-Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:8308)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\Win7-Administrator\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
