### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/mnt/big$ATOM_HOME/styles.less'

### ISSUE THREAD

**Issue by josefpavlik** [platformio/platformio-atom-ide#2366]
[Enter steps to reproduce:]

1. open welcome guide panel
2. press button [open your stylesheet]

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/mnt/big/home/xxx/.atom/styles.less'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/mnt/big/home/jet/.atom/styles.less'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1214427)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/usr/share/atom/resources/app/static/<embedded>:11:425888)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-clang 0.12.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.39 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.0 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
