### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\Marlin-bugfix-2.0.x hopeful...

### ISSUE THREAD

**Issue by JXMIEZ** [platformio/platformio-atom-ide#2372]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\fcast\Documents\Marlin-bugfix-2.0.x hopefully the last one\Marlin'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\fcast\Documents\Marlin-bugfix-2.0.x hopefully the last one\Marlin'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at /packages/platformio-ide/lib/main.js:249:25)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:347765)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:139:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
  4x -9:35.8.0 build:toggle-panel (input.hidden-input)
     -8:53.2.0 core:paste (input.hidden-input)
     -8:30.5.0 intentions:highlight (input.hidden-input)
     -8:30.3.0 core:paste (input.hidden-input)
     -8:26.3.0 platformio-ide:target:build (input.hidden-input)
     -8:26.3.0 platformio-ide:target:build-C:\Users\fcast\Documents\Marlin-bugfix-2.0.x hopefully the last one (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
 12x -8:02.0 intentions:highlight (input.hidden-input)
     -8:01.2.0 core:paste (input.hidden-input)
     -7:57.5.0 platformio-ide:target:build (input.hidden-input)
     -7:57.5.0 platformio-ide:target:build-C:\Users\fcast\Documents\Marlin-bugfix-2.0.x hopefully the last one (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -7:39.3.0 core:backspace (input.hidden-input)
  3x -7:14.4.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -2:36.8.0 platformio-ide:target:build (input.hidden-input)
     -2:36.8.0 platformio-ide:target:build-C:\Users\fcast\Documents\Marlin-bugfix-2.0.x hopefully the last one (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.1.0 platformio-ide:target:build (div.terminal)
```

### Non-Core Packages

```
autocomplete-clang 0.13.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.39 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.0 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
