### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\Marlin 3d printer firmware\...

### ISSUE THREAD

**Issue by JimboJones1979** [platformio/platformio-atom-ide#2376]
[Enter steps to reproduce:]

1. ... Boot up program 
2. ...Error all the time
3.... you tell me why your program sucks

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\jorda\Documents\Marlin 3d printer firmware\Marlin-bugfix-2.0.x'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\jorda\Documents\Marlin 3d printer firmware\Marlin-bugfix-2.0.x'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:425888)
```

### Commands

```
     -9:37.5.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -9:37.5.0 platformio-ide:target:build-C:\Users\jorda\Documents\Marlin 3d printer firmware\Marlin-bugfix-2.0.x - Star Lord (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:21 platformio-ide:settings:pkg-platformio-ide (button.btn.btn-success)
     -6:52.5.0 platformio-ide:settings:pkg-platformio-ide-terminal (div.package-detail)
  2x -6:43.5.0 platformio-ide:home (div.package-detail)
  2x -6:29.5.0 build:toggle-panel (atom-pane.pane)
     -6:12 platformio-ide:settings:pkg-file-icons (atom-pane.pane)
  2x -4:51.7.0 window:toggle-menu-bar (div.tool-panel.tree-view)
  2x -4:10 tool-bar:toggle (ul.list-inline.tab-bar.inset-panel)
     -2:45.6.0 platformio-ide:home (ul.list-inline.tab-bar.inset-panel)
     -2:05.3.0 platformio-ide-terminal:toggle (iframe.native-key-bindings)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.33 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-gcc2 0.8.8 
linter-ui-default 1.7.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
tool-bar 1.1.12 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
