### ISSUE TITLE
Uninstall incompatible packages: platformio-ide-terminal

### ISSUE THREAD

**Issue by GDEVSoeMinHtet** [platformio/platformio-atom-ide#2380]
at AtomDependenciesStage.<anonymous> (file:///C:/Users/User/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:194:13)
at Generator.throw (<anonymous>)
at step (C:\Users\User\.atom\packages\platformio-ide\lib\installer\stages\atom-dependencies.js:15:273)
at process._tickCallback (internal/process/next_tick.js:68:7)

This is the error

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
