### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by marionik1964** [platformio/platformio-atom-ide#2384]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/Users/nik/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2679:19)
    at tryCatch (/Users/nik/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/Users/nik/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/nik/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/Users/nik/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2781:191)
    at /Users/nik/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2781:361
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ivankravets** [comment]
Please upgrade to v2.7.0 where the new installer is added https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0
