### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by michaelkamprath** [platformio/platformio-atom-ide#2387]
Error: Failed to download file https://github.com/platformio/platformio/archive/develop.zip: 
    at _callee$ (/Users/michael/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2668:19)
    at tryCatch (/Users/michael/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:836:40)
    at Generator.invoke [as _invoke] (/Users/michael/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1070:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/michael/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:888:21)
    at step (/Users/michael/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:191)
    at /Users/michael/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2770:361
    at <anonymous>

**Comment by ivankravets** [comment]
Please upgrade to v2.7.0 where the new installer is added https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0
