### ISSUE TITLE
InstallationManager 

### ISSUE THREAD

**Issue by overs0ull** [platformio/platformio-atom-ide#2388]
Hi i try to install it and i am disabled the antivirus and all but not luck i get that : 

Error: PIP Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while. ERROR: Error [WinError 87] The parameter is incorrect while executing command python setup.py egg_info ERROR: Could not install packages due to an EnvironmentError: [WinError 87] The parameter is incorrect

at s.runCommand (C:\Users\PC\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:35177)
at ChildProcess.d (C:\Users\PC\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:8308)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\PC\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by ivankravets** [comment]
Please upgrade to v2.7.0 where the new installer is added https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0
