### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by NFAZ10** [platformio/platformio-atom-ide#2389]
at s.runCommand (/Users/nick/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:35177)
at ChildProcess.d (/Users/nick/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:8308)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:962:16)
at Socket.stream.socket.on (internal/child_process.js:381:11)
at Socket.emit (events.js:182:13)
at Pipe._handle.close (net.js:606:12)

Getting this error

**Comment by ivankravets** [comment]
Please upgrade to v2.7.0 where the new installer is added https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0
