### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '~/AppData\Local\Temp\Temp1_MKS-TFT24-maste...

### ISSUE THREAD

**Issue by jonmfraley** [platformio/platformio-atom-ide#2390]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.6.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'C:\Users\Dee\AppData\Local\Temp\Temp1_MKS-TFT24-master.zip\MKS-TFT24-master'

```
At fs.js:115

Error: EPERM: operation not permitted, lstat 'C:\Users\Dee\AppData\Local\Temp\Temp1_MKS-TFT24-master.zip\MKS-TFT24-master'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1217348)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:426136)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
autocomplete-clang 0.13.1 
build 0.70.0 
build-platformio 1.2.4 
busy-signal 2.0.1 
clang-tools-extra 0.1.0 
file-icons 2.1.41 
hey-pane 1.2.0 
Hydrogen 2.14.1 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-clang-tidy 0.2.0 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
scroll-through-time 0.3.1 
teletype 0.13.4 
tool-bar 1.3.0 
zentabs 0.8.9 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
