### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'E:/Platformio\I2C\src\I2Cx.ino'

### ISSUE THREAD

**Issue by PeterFalow** [platformio/platformio-atom-ide#2398]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: DESKTOP-95G8NEC
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'E:\Platformio\I2C\src\I2Cx.ino'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'E:\Platformio\I2C\src\I2Cx.ino'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at /packages/platformio-ide/lib/utils.js:98:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:102:6)
    at /packages/platformio-ide/lib/main.js:249:25)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:349576)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:348051)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/items/tool-bar-button-view.js:153:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/items/tool-bar-button-view.js:127:12)
```

### Commands

```
     -9:15.3.0 tree-view:move (span.name.icon.arduino-icon)
     -9:03.5.0 core:confirm (input.hidden-input)
     -8:45.2.0 tree-view:add-file (div.header.list-item)
     -8:24.4.0 core:confirm (input.hidden-input)
  9x -7:28 intentions:highlight (input.hidden-input)
     -7:27.2.0 core:paste (input.hidden-input)
     -6:44.3.0 platformio-ide:target:build (div.tool-panel.tree-view)
     -6:44.3.0 platformio-ide:target:build-E:\Platformio\I2C (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:12 platformio-ide:target:build (div.tool-panel.tree-view)
     -2:12 platformio-ide:target:build-E:\Platformio\I2C (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:37.6.0 platformio-ide:target:upload (div.build.tool-panel.native-key-bindings)
     -1:37.6.0 platformio-ide:target:upload-E:\Platformio\I2C (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:00.0 tree-view:show-in-file-manager (span.name.icon.arduino-icon)
     -0:26.3.0 platformio-ide:target:upload (div.tool-panel.tree-view)
     -0:13.7.0 platformio-ide:target:build (div.tool-panel.tree-view)
```

### Non-Core Packages

```
autocomplete-clang 0.13.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.41 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.3.0 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
