### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.47.0\undefined'

### ISSUE THREAD

**Issue by TRK075** [platformio/platformio-atom-ide#2399]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Tom Brophy\AppData\Local\atom\app-1.47.0\undefined'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Tom Brophy\AppData\Local\atom\app-1.47.0\undefined'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at /packages/platformio-ide/lib/maintenance.js:109:39
    at Array.forEach (<anonymous>)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:105:8)
    at doHighlight (/packages/platformio-ide/lib/main.js:306:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1202691)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:426174
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-python 5.0.0 
atom-import-js undefined 
atom-select-npm-install 1.0.2 
atom-terminal 0.8.0 
autocomplete-clang 0.13.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.41 
intentions 1.1.5 
javascript-snippets undefined 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
script undefined 
tool-bar 1.3.0 
vk-terminal 3.0.1 
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
