### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/.platformio\homestate.json'

### ISSUE THREAD

**Issue by miomatrixx** [platformio/platformio-atom-ide#2402]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.7.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Rino Iodice\.platformio\homestate.json'

```
At fs.js:122

Error: ENOENT: no such file or directory, open 'C:\Users\Rino Iodice\.platformio\homestate.json'
    at Object.openSync (fs.js:453:3)
    at Object.func [as openSync] (electron/js2c/asar.js:138:31)
    at Object.readFileSync (fs.js:353:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
    at /packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:12966)
    at Object.e.getFrontendUri (/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:9672)
    at HomeView.render (/packages/platformio-ide/lib/home/view.js:74:45)
    at updateSync (/packages/platformio-ide/node_modules/etch/lib/component-helpers.js:119:34)
    at /packages/platformio-ide/node_modules/etch/lib/component-helpers.js:84:7
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:326339)
```

### Commands

```
     -3:00.0 platformio-ide:home (div.tool-panel.tree-view)
```

### Non-Core Packages

```
autocomplete-clang 0.13.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.41 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.7.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.3.0 
```

**Comment by ivankravets** [comment]
Thanks for the report! Please update to 2.7.1 => https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.1
