### ISSUE TITLE
InstallationManager - platfrormio not working on atom after upgrade

### ISSUE THREAD

**Issue by hexanet67** [platformio/platformio-atom-ide#2405]
Error: Error: Could not create PIO Core Virtual Environment. 

Installer version: 0.3.2 
Platform: Linux-4.4.0-178-generic-x86_64-with-glibc2.9 
Python version: 3.5.2 (default, Apr 16 2020, 17:47:17) [GCC 5.4.0 20160609] 
Python path: /usr/bin/python3 

at f (/mnt/bigdisk/home/jan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975)
at ChildProcess.c (/mnt/bigdisk/home/jan/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
