### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by rejnok93** [platformio/platformio-atom-ide#2408]
Installer version: 0.3.2 Platform: Darwin-15.6.0 Python version: 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] Python path: /usr/bin/python Creating a virtual environment at /Users/rejnok/.platformio/penv
```
at f (/Users/rejnok/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975)
at ChildProcess.c (/Users/rejnok/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:962:16)
at Socket.stream.socket.on (internal/child_process.js:381:11)
at Socket.emit (events.js:182:13)
at Pipe._handle.close (net.js:606:12)
```

**Comment by rejnok93** [comment]
sorry for duplicating: #2405 2407 (I only do, what error message wanted, then read if I'm first or not...)

**Comment by rejnok93** [comment]
After Atom restart, PlatformIO seems to trying update again, but fails again:
Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 0.3.2 Platform: Darwin-15.6.0 Python version: 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] Python path: /usr/bin/python Creating a virtual environment at /Users/rejnok/.platformio/penv

```
at f (/Users/rejnok/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975)
at ChildProcess.c (/Users/rejnok/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:962:16)
at Socket.stream.socket.on (internal/child_process.js:381:11)
at Socket.emit (events.js:182:13)
at Pipe._handle.close (net.js:606:12)
```

**Comment by rejnok93** [comment]
#2409 #2413 #2415 #2417 #2419 #2420 #2421 #2423 #2424

**Comment by rejnok93** [comment]
Solved by installing Python3.
