### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by EzequielRuiz** [platformio/platformio-atom-ide#2413]
InstallationManager

Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 0.3.2 Platform: Windows-10 Python version: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] Python path: C:\Users\USER.platformio\python37\python.exe Creating a virtual environment at C:\Users\USER.platformio\penv

at C:\Users\USER\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4975
at ChildProcess.c (C:\Users\USER\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4871)
at ChildProcess.emit (events.js:194:13)
at ChildProcess.cp.emit (C:\Users\USER\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:998:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
