### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by rainerschulte** [platformio/platformio-atom-ide#2415]
Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 0.3.2 Platform: Windows-10 Python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] Python path: C:\Users\Rainer.platformio\python37\python.exe Creating a virtual environment at C:\Users\Rainer.platformio\penv

at f (C:\Users\Rainer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4975)
at ChildProcess.c (C:\Users\Rainer\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4871)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\Rainer\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
