### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by SolimanGharieb** [platformio/platformio-atom-ide#2416]
Error: Traceback (most recent call last): File "C:\Users\SG\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\SG\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\SG.platformio\penv\Scripts\platformio.exe__main__.py", line 4, in ModuleNotFoundError: No module named 'platformio'

at C:\Users\SG\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:12058
at ChildProcess.d (C:\Users\SG\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:8308)
at ChildProcess.emit (events.js:194:13)
at ChildProcess.cp.emit (C:\Users\SG\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:998:16)
at Socket.<anonymous> (internal/child_process.js:403:11)
at Socket.emit (events.js:194:13)
at Pipe.<anonymous> (net.js:593:12)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
