### ISSUE TITLE
ImportError: Module use of python36.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by Tristanbox09** [platformio/platformio-atom-ide#2418]
Hey guys, I tried using squeezenet1.1.xml model and I am getting this error:

C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\deployment_tools\inference_engine\samples\python\classification_sample\classification_sample>classification_sample.py -i "C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\deployment_tools\model_optimizer\eopath_10" -m "C:\Users\Owner\Documents\Intel\OpenVINO\openvino_models\ir\public\squeezenet1.1\FP16\squeezenet1.1.xml" -d CPU
Traceback (most recent call last):
  File "C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\deployment_tools\inference_engine\samples\python\classification_sample\classification_sample\classification_sample.py", line 8, in <module>
    from openvino.inference_engine import IECore
  File "C:\Program Files (x86)\IntelSWTools\openvino_2020.3.194\python\python3.6\openvino\inference_engine\__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: Module use of python36.dll conflicts with this version of Python.

I am very new to python and was wondering what it could be. I read up that it is a different version of python but when I check my version of python I get this:

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Any ideas on how to fix this??

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
