### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by umosan** [platformio/platformio-atom-ide#2419]
InstallationManager

Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 0.3.2 Platform: Darwin-16.3.0 Python version: 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] Python path: /usr/bin/python Creating a virtual environment at /Users/UMo/.platformio/penv

at f (/Users/UMo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975)
at ChildProcess.c (/Users/UMo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
