### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by trevor-sonic** [platformio/platformio-atom-ide#2424]
**macOS 10.15.5**

Error: Compatible PlatformIO Core not found. Reason: Could not run /Users/mycomputer/.platformio/penv/bin/platformio --version

Error: Traceback (most recent call last): File "/Users/mycomputer/.platformio/penv/bin/platformio", line 5, in from platformio.main import main File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/platformio/main.py", line 21, in from platformio import version, exception, maintenance, util File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/platformio/maintenance.py", line 24, in from platformio.commands.lib import CTX_META_STORAGE_DIRS_KEY File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/platformio/commands/lib.py", line 29, in from platformio.package.manifest.schema import ManifestSchema File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/platformio/package/manifest/schema.py", line 17, in import marshmallow File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/marshmallow/init.py", line 1, in from marshmallow.schema import Schema, SchemaOpts File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/marshmallow/schema.py", line 14, in from marshmallow import base, fields as ma_fields, class_registry, types File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/marshmallow/fields.py", line 14, in from marshmallow import validate, utils, class_registry, types File "/Users/mycomputer/.platformio/penv/lib/python3.5/site-packages/marshmallow/class_registry.py", line 13, in if typing.TYPE_CHECKING: AttributeError: module 'typing' has no attribute 'TYPE_CHECKING'

```
at /Users/mycomputer/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975
at ChildProcess.c (/Users/mycomputer/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:194:13)
at maybeClose (internal/child_process.js:998:16)
at Socket.<anonymous> (internal/child_process.js:403:11)
at Socket.emit (events.js:194:13)
at Pipe.<anonymous> (net.js:593:12)
```

**Comment by trevor-sonic** [comment]
I resolve the problem by upgrading Python version to 3.7.7 with ```brew```
```
brew upgrade python
```
