### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Kloorob** [platformio/platformio-atom-ide#2426]
at /Users/XXXXXXXXXX/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975
at ChildProcess.c (/Users/XXXXXXXXXX/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:194:13)
at maybeClose (internal/child_process.js:998:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
