### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\Curso IoT\.ftpconfig'

### ISSUE THREAD

**Issue by guillermovalverdebaez** [platformio/platformio-atom-ide#2432]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.7.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\guill\Documents\Curso IoT\.ftpconfig'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\guill\Documents\Curso IoT\.ftpconfig'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at /packages/platformio-ide/lib/utils.js:102:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:106:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:305:43)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at ~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:426379
```

### Commands

```
  2x -5:14.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -5:00.2.0 core:confirm (input.hidden-input)
     -4:20.2.0 application:add-project-folder (div.tool-panel.tree-view)
     -4:14.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:40 remote-ftp:toggle (div.header.list-item.project-root-header)
     -3:15.6.0 core:paste (div.line.cursor-line)
 12x -2:59 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
autocomplete-clang 0.13.1 
autocomplete-python 1.16.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.41 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.7.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
remote-ftp 2.2.4 
script 3.26.0 
tool-bar 1.3.0 
```

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
