### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Downloads/mod_SEC test'

### ISSUE THREAD

**Issue by MariHeesbeen** [platformio/platformio-atom-ide#2436]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.7.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/mari/Downloads/mod_SEC test'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/Users/mari/Downloads/mod_SEC test'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at /packages/platformio-ide/lib/utils.js:102:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:106:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:305:43)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202941)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:426379
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-cli-diff 1.9.0 
atom-css-comb 3.5.1 
atom-html-preview 0.2.6 
atom-svn-commit 0.1.1 
atom-sync 0.7.3 
auto-detect-indentation 1.3.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-clang 0.13.1 
build 0.70.0 
busy-signal 2.0.1 
Delete-Whitelines 0.6.4 
emmet 2.4.3 
file-icons 2.1.42 
highlight-selected 0.17.0 
Hydrogen 2.14.4 
ide-html 0.6.0 
intentions 1.1.5 
language-asciidoc 1.11.0 
language-ini 1.23.0 
linter 2.3.1 
linter-csslint 2.0.6 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-htmlhint 1.6.3 
linter-jshint 3.1.19 
linter-ui-default 1.8.1 
markdown-writer 2.11.10 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
pigments 0.40.2 
platformio-aia 0.0.5 
platformio-ide 2.7.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
project-manager 3.3.8 
remote-sync-pro 5.1.1 
rest-client 1.3.1 
seti-ui 1.11.0 
sort-lines 0.19.0 
todo-show 2.3.2 
tool-bar 1.3.0 
tool-bar-markdown-writer 0.5.1 
```

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
