### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents/Untitled.sh'

### ISSUE THREAD

**Issue by svperion** [platformio/platformio-atom-ide#2519]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.6
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/orionneguse/Documents/Untitled.sh'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, lstat '/Users/orionneguse/Documents/Untitled.sh'
    at Proxy.realpathSync (fs.js:1529:7)
    at Proxy.<anonymous> (electron/js2c/asar.js:302:42)
    at /packages/platformio-ide/lib/utils.js:102:25
    at Object.getActivePioProject (/packages/platformio-ide/lib/utils.js:106:6)
    at Object.highlightActiveProject (/packages/platformio-ide/lib/maintenance.js:103:19)
    at doHighlight (/packages/platformio-ide/lib/main.js:305:43)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188366)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:429131
```

### Commands

```
     -0:54 core:copy (span.syntax--string.syntax--quoted.syntax--double.syntax--shell)
     -0:47.3.0 core:paste (div.highlights)
     -0:29.3.0 intentions:highlight (input.hidden-input)
  2x -0:29.1.0 core:copy (input.hidden-input)
  2x -0:25.6.0 editor:newline (input.hidden-input)
     -0:23.8.0 intentions:highlight (input.hidden-input)
     -0:23.6.0 core:paste (input.hidden-input)
     -0:20 core:save-as (input.hidden-input)
     -0:10.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-clang 0.13.1 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.47 
intentions 2.1.1 
language-ini 1.25.0 
linter 3.4.0 
linter-gcc2 0.8.8 
linter-ui-default 3.4.1 
platformio-ide 2.7.2 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.1 
tool-bar 1.4.4 
```

**Comment by svperion** [comment]
Sorry my mistake, I think I know the cause
