### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by alexandreleick** [platformio/platformio-atom-ide#252]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/wy/3ttxv4_j75nbg6dtpkt_y0qc0000gn/T/tmp-4459FB64mYHO9f7H/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/var/folders/wy/3ttxv4_j75nbg6dtpkt_y0qc0000gn/T/tmp-4459FB64mYHO9f7H/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/var/folders/wy/3ttxv4_j75nbg6dtpkt_y0qc0000gn/T/tmp-4459FB64mYHO9f7H/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/alexandre/.atom/packages/platformio-ide/penv/lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/Users/alexandre/.atom/packages/platformio-ide/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment]
What do you see after Atom restart?

**Comment by alexandreleick** [comment]
It's good !
Thanks you

Sent from my iPhone

On 6 Mar 2017, at 18:37, Ivan Kravets <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you see after Atom restart?
