### ISSUE TITLE
Library command failed: lib update --only-check --json-output

### ISSUE THREAD

**Issue by AngusCo** [platformio/platformio-atom-ide#263]
Error: Error: Traceback (most recent call last):
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py", line 132, in lib_update
    latest = lm.outdated(pkg_dir, requirements)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 573, in outdated
    silent=True)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py", line 196, in get_latest_repo_version
    cache_valid="1d")['versions'], requirements)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 510, in get_api_result
    cc.set(cache_key, result, cache_valid)
  File "/Users/Angus/.platformio/penv/lib/python2.7/site-packages/platformio/app.py", line 216, in set
    os.makedirs(self.cache_dir)
  File "/Users/Angus/.platformio/penv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/Angus/.platformio/.cache'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide/commit/fa41938b9a7ea82e76abcfdf3320afc31b8317cf
