### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by xiaalan123** [platformio/platformio-atom-ide#276]
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Temp\tmp-6164bWhPnTfCWd3n\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Temp\tmp-6164bWhPnTfCWd3n\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "C:\Users\Administrator\AppData\Local\Temp\tmp-6164bWhPnTfCWd3n\virtualenv-15.1.0\virtualenv.py", line 945, in create_environment
    download=download,
  File "C:\Users\Administrator\AppData\Local\Temp\tmp-6164bWhPnTfCWd3n\virtualenv-15.1.0\virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\Administrator\AppData\Local\Temp\tmp-6164bWhPnTfCWd3n\virtualenv-15.1.0\virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\Administrat...v\Scripts\python.exe - setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Could you reproduce it with the latest 2.0 Alpha 13?
