### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by PraveenVasireddy** [platformio/platformio-atom-ide#280]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/5z/lcqn32rs4rb0g7vgr3kjs50m0000gn/T/tmp-397937EjJqeY7sAAt/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/5z/lcqn32rs4rb0g7vgr3kjs50m0000gn/T/tmp-397937EjJqeY7sAAt/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)
  File "/var/folders/5z/lcqn32rs4rb0g7vgr3kjs50m0000gn/T/tmp-397937EjJqeY7sAAt/virtualenv-15.1.0/virtualenv.py", line 925, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/var/folders/5z/lcqn32rs4rb0g7vgr3kjs50m0000gn/T/tmp-397937EjJqeY7sAAt/virtualenv-15.1.0/virtualenv.py", line 1110, in install_python

    mkdir(lib_dir)
  File "/var/folders/5z/lcqn32rs4rb0g7vgr3kjs50m0000gn/T/tmp-397937EjJqeY7sAAt/virtualenv-15.1.0/virtualenv.py", line 323, in mkdir

    os.makedirs(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs

    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/praveen/.platformio/penv'

**Comment by ivankravets** [comment]
>  Permission denied: '/Users/praveen/.platformio/

Did you use `pio` with `sudo`? Now, please remove `Users/praveen/.platformio/` folder and don't use sudo.
