### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by PraveenVasireddy** [platformio/platformio-atom-ide#281]
Error: Error: EACCES: permission denied, mkdir '/Users/praveen/.platformio/project-examples'
    at ProjectExamplesStage.<anonymous> (/Users/praveen/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/praveen/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-atom-ide/issues/280#issuecomment-289218265

Please reopen if you still need a help
