### ISSUE TITLE
Platform command failed: platform frameworks --json-output

### ISSUE THREAD

**Issue by Janderpsy** [platformio/platformio-atom-ide#282]
Error: Error: Traceback (most recent call last):
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py", line 191, in platform_frameworks
    for framework in util.get_api_result("/frameworks", cache_valid="30d"):
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 502, in get_api_result
    with ContentCache() as cc:
  File "/Users/janderjunior/.platformio/penv/lib/python2.7/site-packages/platformio/app.py", line 158, in __enter__
    remove(path)
OSError: [Errno 2] No such file or directory: '/Users/janderjunior/.platformio/.cache/21/33ae5e8b9d505b51e779283e98e15521'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

    at /Users/janderjunior/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/Users/janderjunior/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/janderjunior/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:322:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please remove `/Users/janderjunior/.platformio/.cache` and restart Atom
