### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by patriciooliveira** [platformio/platformio-atom-ide#285]
Error: Error: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\EXPGAME\.atom\packages\linter-ui-default\node_modules\sb-config-file\lib\helpers.js'
    at Error (native)

    at AtomDependenciesStage.<anonymous> (file:///C:/Users/EXPGAME/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (C:\Users\EXPGAME\.atom\packages\platformio-ide\lib\installer\stages\atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Could you restart Atom? Does it work now?

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
