### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by graffiti4u** [platformio/platformio-atom-ide#286]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/jn/7sqthy3n6713v8zzl4v8f3v80000gn/T/tmp-24237MECRZiQpcluG/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/jn/7sqthy3n6713v8zzl4v8f3v80000gn/T/tmp-24237MECRZiQpcluG/virtualenv-15.1.0/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/var/folders/jn/7sqthy3n6713v8zzl4v8f3v80000gn/T/tmp-24237MECRZiQpcluG/virtualenv-15.1.0/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/var/folders/jn/7sqthy3n6713v8zzl4v8f3v80000gn/T/tmp-24237MECRZiQpcluG/virtualenv-15.1.0/virtualenv.py", line 1130, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/var/folders/jn/7sqthy3n6713v8zzl4v8f3v80000gn/T/tmp-24237MECRZiQpcluG/virtualenv-15.1.0/virtualenv.py", line 354, in copyfile
    copyfileordir(src, dest, symlink)
  File "/var/folders/jn/7sqthy3n6713v8zzl4v8f3v80000gn/T/tmp-24237MECRZiQpcluG/virtualenv-15.1.0/virtualenv.py", line 329, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 177, in copytree

    os.makedirs(dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs

    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/graffiti/.platformio/penv/lib/python2.7/lib-dynload'

**Comment by ivankravets** [comment]
Could you remove `/Users/graffiti/.platformio` folder and restart IDE?
