### ISSUE TITLE
Install missed packages: platformio-ide-terminal,busy-signal,linter-ui-default,intentions

### ISSUE THREAD

**Issue by basbaba** [platformio/platformio-atom-ide#288]
Error: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/victor/.atom/packages/platformio-ide-terminal/keymaps/platformio-ide-terminal.cson'
    at Error (native)

    at /Users/victor/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/Users/victor/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/victor/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Users/victor/app/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:299:11)
    at /Users/victor/app/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:312:11
    at Socket.<anonymous> (/Users/victor/app/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:181:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
1. Have you had PlatformIO IDE installed before?
2. Try to uninstall `platformio-ide-terminal` and install again

Settings :gear: > Pakcages > Search for platformio-ide-terminal

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
