### ISSUE TITLE
Library command failed: lib update --only-check --json-output

### ISSUE THREAD

**Issue by Spongman** [platformio/platformio-atom-ide#289]
````
Error: Traceback (most recent call last):
  File "/home/user/.platformio/penv/bin/platformio", line 11, in <module>
    load_entry_point('platformio==3.3.0', 'console_scripts', 'platformio')()
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 109, in main
    maintenance.on_platformio_exception(e)

  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 82, in on_platformio_exception
    telemetry.on_exception(e)
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 311, in on_exception
    mp = MeasurementProtocol()
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 65, in __init__
    self['cid'] = app.get_cid()
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 319, in get_cid
    cid = get_state_item("cid")
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 268, in get_state_item
    with State() as data:
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 89, in __enter__
    self._state = util.load_json(self.path)
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 170, in load_json
    file_path)
platformio.exception.PlatformioException: Could not load broken JSON: /home/user/.platformio/appstate.json

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 328, in _finalize
    backup_reports(MPDataPusher().get_items())
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 338, in backup_reports
    tm = app.get_state_item("telemetry", {})
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 268, in get_state_item
    with State() as data:
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 89, in __enter__
    self._state = util.load_json(self.path)
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 170, in load_json
    file_path)
PlatformioException: Could not load broken JSON: /home/user/.platformio/appstate.json
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 328, in _finalize
    backup_reports(MPDataPusher().get_items())
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 338, in backup_reports
    tm = app.get_state_item("telemetry", {})
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 268, in get_state_item
    with State() as data:
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 89, in __enter__
    self._state = util.load_json(self.path)
  File "/home/user/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 170, in load_json
    file_path)
platformio.exception.PlatformioException: Could not load broken JSON: /home/user/.platformio/appstate.json

    at utils.runPIOCommand.spawnOptions (/home/user/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (/home/user/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/user/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:323:11)
    at /opt/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
````

**Comment by ivankravets** [comment]
1. Please remove `/home/user/.platformio/appstate.json`
2. Open PIO IDE Terminal and run
```
pio settings set enable_telemetry No
```
