### ISSUE TITLE
Install missed packages: busy-signal,linter-ui-default,intentions

### ISSUE THREAD

**Issue by EranGoldman** [platformio/platformio-atom-ide#292]
Error: events.js:141

      throw er; // Unhandled 'error' event

      ^

Error: ENOENT: no such file or directory, open '/home/marinetech/.atom/packages/linter-ui-default/node_modules/core-js/fn/_.js'

    at Error (native)

    at /home/marinetech/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/marinetech/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/marinetech/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:322:11)
    at ChildProcess.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Could you try restart Atom?

**Comment by emranweb** [comment]
I have some problem in writing JS code. After that I disable in Plugin. Now It Working Fine.

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424

**Comment by ivankravets** [comment]
@emranweb What did you disable?
