### ISSUE TITLE
Problem has beenn occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by limawill** [platformio/platformio-atom-ide#294]
Error: undefined

    at utils.runAPMCommand.busyTitle (/home/will/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (/home/will/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/will/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/lib64/atom/src/buffered-process.js:303:11)
    at /usr/lib64/atom/src/buffered-process.js:324:11
    at Socket.<anonymous> (/usr/lib64/atom/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please restart Atom. Which version of PIO IDE do you see on PIo Home screen?

**Comment by ivankravets** [comment]
@orgkhnargh if an error occurs while automatically upgrading PIO IDE, need to ask the user upgrade IDE manually (modal window) \.
