### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gorec2005** [platformio/platformio-atom-ide#297]
Virtualenv Download: Traceback (most recent call last):
  File "/tmp/tmp-31708IeY5CnzvScuo/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/tmp/tmp-31708IeY5CnzvScuo/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)
  File "/tmp/tmp-31708IeY5CnzvScuo/virtualenv-15.1.0/virtualenv.py", line 925, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/oleg/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/home/oleg/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')

AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment]
How did you resolve that?
