### ISSUE TITLE
Error installing PlatformIO

### ISSUE THREAD

**Issue by Super169** [platformio/platformio-atom-ide#305]
Error: Error: tunneling socket could not be established, statusCode=407
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/makk/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\makk\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Super169** [comment]
The above error was prompted for installation of Clang, and the above message was generated by clicking the [Report a problem] button.

**Comment by Super169** [comment]
The latest error was reported when the system trying to install PlatformIO Core.

Is it possible to install it by standalone package?  I have try to install by "pip install platformio", but it seems that Atom cannot recognize the installation via pip.
