### ISSUE TITLE
Install missed packages: linter-ui-default,intentions

### ISSUE THREAD

**Issue by BenLauezzari** [platformio/platformio-atom-ide#310]
Error: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/ben/.atom/packages/linter-ui-default/node_modules/brace-expansion/index.js'
    at Error (native)

    at /home/ben/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/ben/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/ben/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /opt/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by BenLauezzari** [comment]
Error during updates

**Comment by ivankravets** [comment]
Do you mean update from PIO IDE 1.0 to PIO IDE 2.0?

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
