### ISSUE TITLE
InstallationManager: Error: unexpected end of file

### ISSUE THREAD

**Issue by greent2008** [platformio/platformio-atom-ide#311]
Error: Error: unexpected end of file
    at ProjectExamplesStage.<anonymous> (/home/jianengxi/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/home/jianengxi/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Do you see this error after Atom restart?

**Comment by greent2008** [comment]
I have already solved this problem
