### ISSUE TITLE
Install missed packages: linter-ui-default,intentions

### ISSUE THREAD

**Issue by svsummer** [platformio/platformio-atom-ide#314]
Error: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/stijn/.atom/packages/linter-ui-default/node_modules/sb-npm-path/.babelrc'
    at Error (native)

    at /home/stijn/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/stijn/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/stijn/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Could you restart Atom, does it work now?

**Comment by svsummer** [comment]
Yes, it works now. Sincere apologies for the overhead!

Op 1 apr. 2017 19:59 schreef "Ivan Kravets" <notifications@github.com>:

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
