### ISSUE TITLE
Install missed packages: linter-ui-default,intentions

### ISSUE THREAD

**Issue by treaves** [platformio/platformio-atom-ide#315]
Error: events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/treaves/.atom/packages/linter-ui-default/node_modules/minimist/.travis.yml'
    at Error (native)

    at /Users/treaves/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/Users/treaves/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/treaves/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:303:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:316:11
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Could you restart Atom, does it work now?

**Comment by treaves** [comment]
When I restarted, it re-downloaded the failed packages, and is now working.

**Comment by ivankravets** [comment]
@TODO If installer fails for multiple packages, try to install each package separate or try again.

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
