### ISSUE TITLE
Install missed packages: dbg,dbg-gdb,output-panel

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#317]
Error: Unable to download https://www.atom.io/api/packages/dbg/versions/1.4.1/tarball: connect ETIMEDOUT 23.21.77.86:443

    at /Users/sstaub/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/Users/sstaub/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/sstaub/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:322:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Internet
