### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#318]
Error: Error: Unable to download https://www.atom.io/api/packages/dbg/versions/1.4.1/tarball: connect ETIMEDOUT 23.21.77.86:443

    at AtomDependenciesStage.<anonymous> (/Users/sstaub/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (/Users/sstaub/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please restart Atom. `TIMEDOUT`, something wrong with Internet connection
