### ISSUE TITLE
InstallationManager: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by petrovichpit** [platformio/platformio-atom-ide#321]
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-1076A8X38QNU4aHk\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-1076A8X38QNU4aHk\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-1076A8X38QNU4aHk\virtualenv-15.1.0\virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-1076A8X38QNU4aHk\virtualenv-15.1.0\virtualenv.py", line 1148, in install_python
    writefile(join(site_dir, 'orig-prefix.txt'), prefix)
  File "C:\Users\B19A~1\AppData\Local\Temp\tmp-1076A8X38QNU4aHk\virtualenv-15.1.0\virtualenv.py", line 368, in writefile
    if c != content.encode("utf-8"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 9: ordinal not in range(128)

**Comment by ivankravets** [comment]
@orgkhnargh see https://github.com/platformio/platformio-atom-ide/blob/develop/lib/config.js#L112

if `process.env.PLATFORMIO_HOME_DIR` does not set and `fs.getHomeDirectory()` contains non-ascii chars, then need to set `process.env.PLATFORMIO_HOME_DIR=%DRIVE%:\.platformio`. (as you do that here https://github.com/platformio/platformio-atom-ide/blob/develop/lib/config.js#L187)
