### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by DJManas** [platformio/platformio-atom-ide#322]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/n6/m9j893wd0qj2klmx2_1r32x80000gn/T/tmp-46879omDzBRD8FvG6/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/n6/m9j893wd0qj2klmx2_1r32x80000gn/T/tmp-46879omDzBRD8FvG6/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)
  File "/var/folders/n6/m9j893wd0qj2klmx2_1r32x80000gn/T/tmp-46879omDzBRD8FvG6/virtualenv-15.1.0/virtualenv.py", line 925, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))

  File "/Users/djmanas/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/Users/djmanas/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 54, in isabs

    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by DJManas** [comment]
After restart everything works...
