### ISSUE TITLE
Library command failed: lib list --json-output

### ISSUE THREAD

**Issue by 6s1gm4** [platformio/platformio-atom-ide#325]
Error: Error: Could not load broken JSON: C:\Users\win\Documents\Arduino\PlatformIO\mqtt-ir-transceiver-OTA\.piolibdeps\IRremoteESP8266\.library.json

    at utils.runPIOCommand.spawnOptions (file:///C:/Users/win/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (file:///C:/Users/win/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/win/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\win\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at C:\Users\win\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:343:11
    at Socket.<anonymous> (C:\Users\win\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Could you share here a content fo this files?
C:\Users\win\Documents\Arduino\PlatformIO\mqtt-ir-transceiver-OTA\.piolibdeps\IRremoteESP8266\.library.json
