### ISSUE TITLE
Platform command failed: platform install atmelavr@1.4.5

### ISSUE THREAD

**Issue by guilhermegazzinelli** [platformio/platformio-atom-ide#326]
Error: Error: Could not install 'toolchain-atmelavr' with version requirements '~1.40902.0' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

    at file:///C:/Users/artur gazzinelli/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (file:///C:/Users/artur gazzinelli/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/artur gazzinelli/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\artur gazzinelli\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\artur gazzinelli\AppData\Local\atom\app-1.15.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Should be fixed in the latest PIO IDE 2.0 Beta 3
