### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by DevilOnWalk** [platformio/platformio-atom-ide#332]
Error: Error: ENOTEMPTY: directory not empty, rmdir '/Users/adityasharma/.atom/packages/linter-ui-default/node_modules/disposable-event'

    at AtomDependenciesStage.<anonymous> (/Users/adityasharma/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (/Users/adityasharma/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
