### ISSUE TITLE
Install missed packages: linter-ui-default,intentions

### ISSUE THREAD

**Issue by TinajaLabs** [platformio/platformio-atom-ide#334]
Error: ENOTEMPTY: directory not empty, rmdir '/home/chrisj/.atom/packages/linter-ui-default/node_modules/core-js/modules'

    at /home/chrisj/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/chrisj/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/chrisj/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
