### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by PeAugR** [platformio/platformio-atom-ide#336]
Virtualenv Download: Traceback (most recent call last):
  File "C:/Users/PEDROR~1/PLATFO~1/penv/lib/python2.7/site.py", line 703, in <module>
    main()
  File "C:/Users/PEDROR~1/PLATFO~1/penv/lib/python2.7/site.py", line 692, in main
    aliasmbcs()
  File "C:/Users/PEDROR~1/PLATFO~1/penv/lib/python2.7/site.py", line 515, in aliasmbcs
    import locale, codecs
  File "C:\Users\PEDROR~1\PLATFO~1\penv\lib\python2.7/locale.py", line 17, in <module>
    import functools
ImportError: No module named functools

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/337
