### ISSUE TITLE
Install missed packages: linter-ui-default,intentions

### ISSUE THREAD

**Issue by htrcarlos** [platformio/platformio-atom-ide#338]
Error: ENOTEMPTY: directory not empty, rmdir '/Users/heitor/.atom/packages/linter-ui-default/node_modules'

    at /Users/heitor/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/Users/heitor/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/heitor/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:303:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
