### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by rianders** [platformio/platformio-atom-ide#340]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/2c/vb3ntrs514q41rqr1zbyy56w0000gr/T/tmp-196181h16UuwC5RuZ/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/2c/vb3ntrs514q41rqr1zbyy56w0000gr/T/tmp-196181h16UuwC5RuZ/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)
  File "/var/folders/2c/vb3ntrs514q41rqr1zbyy56w0000gr/T/tmp-196181h16UuwC5RuZ/virtualenv-15.1.0/virtualenv.py", line 945, in create_environment

    download=download,
  File "/var/folders/2c/vb3ntrs514q41rqr1zbyy56w0000gr/T/tmp-196181h16UuwC5RuZ/virtualenv-15.1.0/virtualenv.py", line 901, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/var/folders/2c/vb3ntrs514q41rqr1zbyy56w0000gr/T/tmp-196181h16UuwC5RuZ/virtualenv-15.1.0/virtualenv.py", line 797, in call_subprocess

    % (cmd_desc, proc.returncode))
OSError: Command /Users/rk2/.platformio/penv/bin/python2.7 - setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Does Atom restart help you?

**Comment by rianders** [comment]
I was asked to restart and then it wanted to update again. Then the error occurred  again.

On Apr 6, 2017, at 1:25 PM, Ivan Kravets <notifications@github.com<mailto:notifications@github.com>> wrote:


Does Atom restart help you?
