### ISSUE TITLE
InstallationManager: Error: Could not get proxy from APM

### ISSUE THREAD

**Issue by NetForces** [platformio/platformio-atom-ide#341]
Error: Could not get proxy from APM: npm config failed: 1

    at ProjectExamplesStage.<anonymous> (/Users/courchea/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/courchea/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please update Atom to 1.17 and PIO IDE to the latest version
