### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mateorico** [platformio/platformio-atom-ide#342]
Error: Error: Unable to download https://www.atom.io/api/packages/build/versions/0.67.0/tarball: read ETIMEDOUT

    at AtomDependenciesStage.<anonymous> (/home/mateorico/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (/home/mateorico/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
