### ISSUE TITLE
InstallationManager: Error: unexpected end of file

### ISSUE THREAD

**Issue by twaider** [platformio/platformio-atom-ide#344]
Error: Error: unexpected end of file
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/twaider/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\twaider\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/284
