### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by darkdragondraco** [platformio/platformio-atom-ide#346]
Error: Error: events.js:141

      throw er; // Unhandled 'error' event

      ^

Error: ENOENT: no such file or directory, open '/Users/draco/.atom/packages/linter-ui-default/styles/linter-ui.less'
    at Error (native)

    at AtomDependenciesStage.<anonymous> (/Users/draco/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (/Users/draco/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
