### ISSUE TITLE
InstallationManager: setuptools pip wheel failed with error code 2

### ISSUE THREAD

**Issue by argorain** [platformio/platformio-atom-ide#352]
```
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\E878714\AppData\Local\Temp\tmp-15288FaF3qwqfK0UU\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "C:\Users\E878714\AppData\Local\Temp\tmp-15288FaF3qwqfK0UU\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "C:\Users\E878714\AppData\Local\Temp\tmp-15288FaF3qwqfK0UU\virtualenv-15.1.0\virtualenv.py", line 945, in create_environment
    download=download,
  File "C:\Users\E878714\AppData\Local\Temp\tmp-15288FaF3qwqfK0UU\virtualenv-15.1.0\virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\E878714\AppData\Local\Temp\tmp-15288FaF3qwqfK0UU\virtualenv-15.1.0\virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\E878714\.pl...v\Scripts\python.exe - setuptools pip wheel failed with error code 2
```
I tried it several times, always crashes.
It tries to reinstall Platformio Core on each start of Atom.
Windows 7 64bit

**Comment by argorain** [comment]
Hm, seems installing latest Python 2.7.13 and inside of this installing PlatformIO helps. I used pip for this
`pip install platformio`
But after PlatformIO start, I run into anotheger issue, for example this one: https://github.com/platformio/platformio-atom-ide/issues/75
but I think it is not related to install process, correct me if I am wrong.

**Comment by argorain** [comment]
Well, it works now.

Steps to get it working:
1) Install platformio with pip `pip install platformio`
2) In Atom install platformio-ide package and **uncheck** `Use built-in PlatformIO Core` and fill in `Custom PATH for platformio command` with path to your platformio (in my case it is `C:\Python27\Scripts\platformio`. You can test it in command line)
3) Remove .platformio folder. In my case it was located at `C:\Users\E878714\.platformio` 
4) Restart Atom
5) It should recreate .platformio folder and ask for restart
6) Now it should work.
