### ISSUE TITLE
Platform command failed: platform frameworks --json-output

### ISSUE THREAD

**Issue by ubIQio** [platformio/platformio-atom-ide#354]
Error: Usage: platformio [OPTIONS] COMMAND [ARGS]...

Error: no such option: -f

    at /Users/jonathanpeace/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/Users/jonathanpeace/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/jonathanpeace/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:322:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please check => Menu: PlatformIO > Settings > PIO IDE > Use built-in PIO Core.

Also, remove (`pip uninstall platformio`) any instances of PIO Core in your system terminal (not PIO IDE terminal)
