### ISSUE TITLE
Install missed packages: build,platformio-ide-terminal,linter-ui-default,intentions,dbg,dbg-gdb,output-panel

### ISSUE THREAD

**Issue by seawayza** [platformio/platformio-atom-ide#362]
Error: EPERM: operation not permitted, unlink 'C:\Users\K\.atom\packages\build'

    at file:///C:/Users/K/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (file:///C:/Users/K/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/K/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\K\AppData\Local\atom\app-1.14.3\resources\app.asar\src\buffered-process.js:303:11)
    at ChildProcess.<anonymous> (C:\Users\K\AppData\Local\atom\app-1.14.3\resources\app.asar\src\buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424

**Comment by ProPuke** [comment]
Author of `dbg`, `dbg-gdb` and `output-panel` here.

These packages do appear to be compatible with platformio (now?).

How does one escape the clutches of the naughty (ATOM_CONFLICTED_DEPENDENCIES) list?

**Comment by ivankravets** [comment]
@ProPuke Sorry, we had problems before when migrated to our debugging front-end https://github.com/platformio/platformio-atom-ide-debugger


I've just removed these packages https://github.com/platformio/platformio-atom-ide/commit/e32299468dde211f3f80bd8f07416bbc370f69be . So, developers should control which packages to use. Also, need to manually specify debugging configuration for dbg-gdb.

**Comment by ProPuke** [comment]
Thanks Ivan.

Your debugger looks nice btw!
