### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by seawayza** [platformio/platformio-atom-ide#363]
Error: Error: EPERM: operation not permitted, unlink 'C:\Users\K\.atom\packages\build'

    at AtomDependenciesStage.<anonymous> (file:///C:/Users/K/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (C:\Users\K\.atom\packages\platformio-ide\lib\installer\stages\atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
