### ISSUE TITLE
InstallationManager -> I think you should not use system path dependency...

### ISSUE THREAD

**Issue by mzozo95** [platformio/platformio-atom-ide#379]
InstallationManager -> I think you should not use system path dependency...
Horrible to do anything with an old installed Windows...
Error again:
```
Virtualenv Download: Traceback (most recent call last):
  File "C:\TEMP\AppData\Local\Temp;\tmp-8656E0IM0G5aPLqw\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "C:\TEMP\AppData\Local\Temp;\tmp-8656E0IM0G5aPLqw\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "C:\TEMP\AppData\Local\Temp;\tmp-8656E0IM0G5aPLqw\virtualenv-15.1.0\virtualenv.py", line 945, in create_environment
    download=download,
  File "C:\TEMP\AppData\Local\Temp;\tmp-8656E0IM0G5aPLqw\virtualenv-15.1.0\virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\TEMP\AppData\Local\Temp;\tmp-8656E0IM0G5aPLqw\virtualenv-15.1.0\virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\.pioidepenv\Scripts\python.exe - setuptools pip wheel failed with error code 1

```

**Comment by ivankravets** [comment]
We don't do that. Please open issue https://github.com/atom/atom/issues
