### ISSUE TITLE
Install missed packages: intentions,linter,linter-gcc,language-ini,tool-bar,file-icons,minimap

### ISSUE THREAD

**Issue by AliGheibi** [platformio/platformio-atom-ide#380]
Error: Unable to download https://www.atom.io/api/packages/intentions/versions/1.1.2/tarball: getaddrinfo EAI_AGAIN codeload.github.com:443

    at file:///C:/Users/sombre/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (file:///C:/Users/sombre/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/sombre/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\sombre\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\sombre\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
