### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by AliGheibi** [platformio/platformio-atom-ide#381]
Error: Error: Unable to download https://www.atom.io/api/packages/intentions/versions/1.1.2/tarball: getaddrinfo EAI_AGAIN codeload.github.com:443

    at AtomDependenciesStage.<anonymous> (file:///C:/Users/sombre/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (C:\Users\sombre\.atom\packages\platformio-ide\lib\installer\stages\atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends https://github.com/platformio/platformio-atom-ide/issues/424
