### ISSUE TITLE
Install missed packages: build,busy,platformio-ide-terminal,autocomplete-clang,linter-ui-default,intentions,linter,linter-gcc,language-ini,tool-bar,file-icons,minimap

### ISSUE THREAD

**Issue by bwv552** [platformio/platformio-atom-ide#383]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\noriyuki\.atom\packages\minimap\spec\canvas-layer-spec.js'
    at Error (native)

    at file:///C:/Users/noriyuki/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (file:///C:/Users/noriyuki/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/noriyuki/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\noriyuki\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\noriyuki\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
