### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by zuzy** [platformio/platformio-atom-ide#385]
Error: Error: Request for package information failed: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80 80:80 (5 attempts) (ECONNRESET)

    at AtomDependenciesStage.<anonymous> (file:///C:/Users/zizy/.atom/packages/platformio-atom-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (C:\Users\zizy\.atom\packages\platformio-atom-ide\lib\installer\stages\atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Internet connection problem?
