### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mcprakash** [platformio/platformio-atom-ide#386]
Error: Error: events.js:141

      throw er; // Unhandled 'error' event

      ^

Error: ENOENT: no such file or directory, open '/home/chandra/.atom/packages/linter-ui-default/node_modules/isomorphic-fetch/.editorconfig'

    at Error (native)

    at AtomDependenciesStage.<anonymous> (/home/chandra/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (/home/chandra/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
