### ISSUE TITLE
Install missed packages: linter-ui-default,intentions

### ISSUE THREAD

**Issue by mcprakash** [platformio/platformio-atom-ide#387]
Error: events.js:141

      throw er; // Unhandled 'error' event

      ^

Error: ENOENT: no such file or directory, open '/home/chandra/.atom/packages/linter-ui-default/node_modules/isomorphic-fetch/.editorconfig'

    at Error (native)

    at /home/chandra/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/chandra/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/chandra/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:299:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:320:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:181:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
