### ISSUE TITLE
InstallationManager: WindowsError: [Error 5] Accesso negato

### ISSUE THREAD

**Issue by Jbbs** [platformio/platformio-atom-ide#392]
Virtualenv Download: Traceback (most recent call last):
  File "c:\temp\tmp-31388JaFIXf4FE0FM\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "c:\temp\tmp-31388JaFIXf4FE0FM\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "c:\temp\tmp-31388JaFIXf4FE0FM\virtualenv-15.1.0\virtualenv.py", line 945, in create_environment
    download=download,
  File "c:\temp\tmp-31388JaFIXf4FE0FM\virtualenv-15.1.0\virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "c:\temp\tmp-31388JaFIXf4FE0FM\virtualenv-15.1.0\virtualenv.py", line 753, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Users\401993\.platformio\python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\401993\.platformio\python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Accesso negato

**Comment by Jbbs** [comment]
This happens during the platformIO core installation launced from ATOM, both as a normal user that as admin

**Comment by ivankravets** [comment]
Do you have Python installed in a system?

**Comment by Jbbs** [comment]
Yes,
I think that is something proxy related. I'm on windows 7 and I had the error at office, where I must  use a proxy server, but I was able to install without problems at home without proxy.
The error persist also if I define HTTP PROXYs environment variables.
At home I installed also un linux Ubunto without problems.


      Da: Ivan Kravets <notifications@github.com>
 A: platformio/platformio-atom-ide <platformio-atom-ide@noreply.github.com> 
Cc: Jbbs <miziob@yahoo.com>; Author <author@noreply.github.com>
 Inviato: Lunedì 1 Maggio 2017 0:06
 Oggetto: Re: [platformio/platformio-atom-ide] InstallationManager (#392)
   
Do you have Python installed in a system?—

**Comment by ivankravets** [comment]
Could you try to update to the latest PIO IDE 2.0 Beta 3? Do you use the latest Atom v1.16?

**Comment by ivankravets** [comment]
Please reopen if you still need help
