### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by egs2003** [platformio/platformio-atom-ide#395]
Error: Error: Request for package information failed: Internal Server Error

    at AtomDependenciesStage.<anonymous> (file:///C:/Users/Marcel/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (C:\Users\Marcel\.atom\packages\platformio-ide\lib\installer\stages\atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
