### ISSUE TITLE
Install missed packages: language-ini,tool-bar

### ISSUE THREAD

**Issue by sinolliu** [platformio/platformio-atom-ide#397]
Error: Request for package information failed: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:1080 (5 attempts) (ECONNRESET)

    at file:///C:/Users/xsin/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (file:///C:/Users/xsin/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/xsin/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\xsin\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\xsin\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
