### ISSUE TITLE
Install missed packages: build,busy,platformio-ide-terminal,autocomplete-clang,linter-ui-default,intentions,linter,linter-gcc,language-ini,tool-bar,file-icons,minimap

### ISSUE THREAD

**Issue by sidlo64** [platformio/platformio-atom-ide#401]
Error: Unable to download https://www.atom.io/api/packages/linter/versions/2.1.4/tarball: read ECONNRESET

    at /home/tata/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/tata/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/tata/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
