### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by sidlo64** [platformio/platformio-atom-ide#402]
Error: Error: Unable to download https://www.atom.io/api/packages/linter/versions/2.1.4/tarball: read ECONNRESET

    at AtomDependenciesStage.<anonymous> (/home/tata/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:164:13)
    at throw (<anonymous>)
    at step (/home/tata/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
