### ISSUE TITLE
InstallationManager:  Error: unexpected end of file

### ISSUE THREAD

**Issue by chedongzhe** [platformio/platformio-atom-ide#403]
Error: Error: unexpected end of file
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/CheDongZhe/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\CheDongZhe\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Could you try uninstall `platformio-ide` package in Atom and install again?

**Comment by ivankravets** [comment]
Please upgrade to the latest PIO IDE 2.0 Beta 3
