### ISSUE TITLE
Library command failed: lib --global stats --json-output

### ISSUE THREAD

**Issue by geovanips** [platformio/platformio-atom-ide#409]
Error: Error: Traceback (most recent call last):
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/lib.py", line 399, in lib_stats
    result = get_api_result("/lib/stats", cache_valid="1h")
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 501, in get_api_result
    with ContentCache() as cc:
  File "/home/geovani/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 158, in __enter__
    remove(path)
OSError: [Errno 13] Permission denied: '/home/geovani/.platformio/.cache/ce/67bbd92c678c9d80c7a37baf26ce2ace'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

    at utils.runPIOCommand.spawnOptions (/home/geovani/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (/home/geovani/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/geovani/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:303:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:324:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please remove `/home/geovani/.platformio/.cache` folder
