### ISSUE TITLE
Platform command failed: platform install esp32

### ISSUE THREAD

**Issue by gkbtaru** [platformio/platformio-atom-ide#412]
Error: Error: Detected unknown package 'esp32'

    at file:///C:/Users/gkbhat.TARUAMD/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (file:///C:/Users/gkbhat.TARUAMD/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/gkbhat.TARUAMD/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\gkbhat.TARUAMD\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\gkbhat.TARUAMD\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please use GUI for platform installing. Home > Platforms > Embedded > Install
