### ISSUE TITLE
Library command failed: lib --global install 1407

### ISSUE THREAD

**Issue by fhwessels** [platformio/platformio-atom-ide#415]
Error: Error: Could not find a version that satisfies the requirement '2.0.0' for your system 'windows_x86'

    at utils.runPIOCommand.spawnOptions (file:///C:/Users/fhwes/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (file:///C:/Users/fhwes/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/fhwes/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\fhwes\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\fhwes\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-atom-ide/issues/415
