### ISSUE TITLE
Install missed packages: build,busy,autocomplete-clang,linter-ui-default,intentions,linter,linter-gcc,language-ini,tool-bar,file-icons,minimap

### ISSUE THREAD

**Issue by 3bb** [platformio/platformio-atom-ide#418]
Error: Unable to download https://www.atom.io/api/packages/build/versions/0.67.0/tarball: getaddrinfo ENOTFOUND www.atom.io www.atom.io:443

    at /home/bogdan/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/bogdan/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/bogdan/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /opt/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
