### ISSUE TITLE
Install missed packages: linter-ui-default,intentions

### ISSUE THREAD

**Issue by Morton16ok** [platformio/platformio-atom-ide#421]
Error: (node:13754) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/morton/.atom/packages/linter-ui-default/node_modules/iconv-lite/.npmignore'

    at /home/morton/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/home/morton/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/morton/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-atom-ide/issues/424
