### ISSUE TITLE
UnicodeDecodeError when generating CLion integration files

### ISSUE THREAD

**Issue by Oromis** [platformio/platformio-atom-ide#429]
When setting up our PlatformIO project on my coworker's laptop, I ran into an encoding error while running `pio init --ide clion`. She has a non-ASCII character in her Windows username, which is nothing I can do anything about. 

I read issue https://github.com/platformio/platformio-core/issues/143#issuecomment-88060906 and applied all suggestions.

Steps I took in an attempt to resolve the error:
* Place the project in a directory outside of her home directory (C:\Software)
* Defined `home_dir` in `platformio.ini` to point at a directory without non-ASCII characters (C:\.platformio)
* Defined the System Environment Variable `PLATFORMIO_HOME_DIR` to point at the same directory (C:\.platformio)

None of these worked. I can run `pio init` successfully, but the CLion IDE integration makes it fail. Here is the traceback: 

```
Error: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\platformio\__main__.py", line 106, in main
    cli(None, None, None)
  File "c:\python27\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\platformio\commands\init.py", line 114, in cli
    pg.generate()
  File "c:\python27\lib\site-packages\platformio\ide\projectgenerator.py", line 116, in generate
    self._render_tpl(tpl_path).encode("utf8"))
  File "c:\python27\lib\site-packages\platformio\ide\projectgenerator.py", line 122, in _render_tpl
    return bottle.template(content, **self._tplvars)
  File "c:\python27\lib\site-packages\bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "c:\python27\lib\site-packages\bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "c:\python27\lib\site-packages\bottle.py", line 3396, in execute
    eval(self.co, env)
  File "<string>", line 1, in <module>
  File "c:\python27\lib\site-packages\bottle.py", line 3347, in <lambda>
    self._escape = lambda x: escape_func(touni(x, enc))
  File "c:\python27\lib\site-packages\bottle.py", line 123, in touni
    return s.decode(enc, err) if isinstance(s, bytes) else unicode(s)
  File "c:\python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 217: invalid continuation byte
```

The traceback refers to the invalid character 0xE4, which is the Windows-1252 representation of the umlaut `ä`, which is a part of my coworker's username.

**Comment by Oromis** [comment]
Sorry, wrong issue tracker (This is a PlatformIO Core bug)
