### ISSUE TITLE
Library command failed: lib --global stats --json-output

### ISSUE THREAD

**Issue by cgIntel** [platformio/platformio-atom-ide#431]
Error: Error: no such option: --global

    at utils.runPIOCommand.spawnOptions (/Users/chetanga/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (/Users/chetanga/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/chetanga/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Users/chetanga/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:322:11)
    at /Users/chetanga/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/Users/chetanga/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please uninstall external PIO Core from a system. Run system terminal and type `pip uninstall platformio` or `brew uninstall platformio` (I don't know how did you install it).

Then go to `Menu: PlatformIO > Settings > PlatformIO IDE > Check "Use built-in PIO Core`
