### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by raghunath-posa** [platformio/platformio-atom-ide#438]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/p5/15y8gmcj50dcy92zgf0rs948rm4qs1/T/tmp-36206RFQxKOGiMP4z/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/p5/15y8gmcj50dcy92zgf0rs948rm4qs1/T/tmp-36206RFQxKOGiMP4z/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)
  File "/var/folders/p5/15y8gmcj50dcy92zgf0rs948rm4qs1/T/tmp-36206RFQxKOGiMP4z/virtualenv-15.1.0/virtualenv.py", line 945, in create_environment

    download=download,
  File "/var/folders/p5/15y8gmcj50dcy92zgf0rs948rm4qs1/T/tmp-36206RFQxKOGiMP4z/virtualenv-15.1.0/virtualenv.py", line 901, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/var/folders/p5/15y8gmcj50dcy92zgf0rs948rm4qs1/T/tmp-36206RFQxKOGiMP4z/virtualenv-15.1.0/virtualenv.py", line 797, in call_subprocess

    % (cmd_desc, proc.returncode))
OSError: Command /Users/i839972/.platformio/penv/bin/python2.7 - setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Should be fixed in the latest Beta 3. Please update it.

Please reopen if you still need a help
