### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jot4p** [platformio/platformio-atom-ide#440]
Error: Error: tunneling socket could not be established, statusCode=407
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/XXX/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\XXX\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Looks like a problem with Internet connection. Could you restart Atom? Please reopen this issue if you still have a problem.
