### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by kaosat-dev** [platformio/platformio-atom-ide#442]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/yj/9s847qm14ln13m9pfc1_ks580000gn/T/tmp-91933zvDpoVhwZKQG/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/yj/9s847qm14ln13m9pfc1_ks580000gn/T/tmp-91933zvDpoVhwZKQG/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)

  File "/var/folders/yj/9s847qm14ln13m9pfc1_ks580000gn/T/tmp-91933zvDpoVhwZKQG/virtualenv-15.1.0/virtualenv.py", line 925, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/var/folders/yj/9s847qm14ln13m9pfc1_ks580000gn/T/tmp-91933zvDpoVhwZKQG/virtualenv-15.1.0/virtualenv.py", line 1158, in install_python

    copyfile(stdinc_dir, inc_dir, symlink)
  File "/var/folders/yj/9s847qm14ln13m9pfc1_ks580000gn/T/tmp-91933zvDpoVhwZKQG/virtualenv-15.1.0/virtualenv.py", line 343, in copyfile

    os.makedirs(os.path.dirname(dest))
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs

    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/kraftwerk-mb/.platformio/penv/include'

**Comment by ivankravets** [comment]
Could you remove `/Users/kraftwerk-mb/.platformio/penv` and restart Atom? 

Also, please update to PIO IDE 2.0 Beta 3

**Comment by ivankravets** [comment]
Please reopen if you still need help
