### ISSUE TITLE
InstallationManager: setuptools pip wheel failed with error code 2

### ISSUE THREAD

**Issue by enricotimisela** [platformio/platformio-atom-ide#446]
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\etimisel\AppData\Local\Temp\tmp-1488VP0m0ooTDEhV\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "C:\Users\etimisel\AppData\Local\Temp\tmp-1488VP0m0ooTDEhV\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "C:\Users\etimisel\AppData\Local\Temp\tmp-1488VP0m0ooTDEhV\virtualenv-15.1.0\virtualenv.py", line 945, in create_environment
    download=download,
  File "C:\Users\etimisel\AppData\Local\Temp\tmp-1488VP0m0ooTDEhV\virtualenv-15.1.0\virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "C:\Users\etimisel\AppData\Local\Temp\tmp-1488VP0m0ooTDEhV\virtualenv-15.1.0\virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\etimisel\.p...v\Scripts\python.exe - setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Could you uninstall PIO IDE http://docs.platformio.org/en/latest/ide/atom.html#uninstall-atom-with-platformio-ide and install the latest Beta 3?

Thanks!

**Comment by ivankravets** [comment]
Please open system terminal (`cmd`) and provide:
```
python --version
pip --version
virtualenv -- version
echo %PATH%
```

Thanks!

**Comment by ivankravets** [comment]
Please reopen if you still need help
