### ISSUE TITLE
Failed to reset password.

### ISSUE THREAD

**Issue by jkDesignDE** [platformio/platformio-atom-ide#450]
Error
    at file:///C:/Users/jochen.krapf/.atom/packages/platformio-ide/lib/account/helpers.js:30:25
    at onExit (file:///C:/Users/jochen.krapf/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/jochen.krapf/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\jochen.krapf\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\jochen.krapf\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by orgkhnargh** [comment]
Hi @jkDesignDE,

Can you please try to reset password via the CLI and let me know what error it prints (if any)? Run the following command in a terminal inside Atom:

```
pio account forgot --username {your email}
```

**Comment by jkDesignDE** [comment]
typed in the command:
No response = no error!?!

**Comment by orgkhnargh** [comment]
Doesn't sound right.

`pio --version`?

**Comment by jkDesignDE** [comment]
pio --version ->
PlatformIO, version 3.4.0b2

**Comment by orgkhnargh** [comment]
I wasn't able to reproduce this error using PlatformIO IDE 2.0.0.beta3 and PlatformIO Core 3.4.0b2 on Windows 7.

Can you please reinstall the IDE package and let me know if you still see the error?

**Comment by ivankravets** [comment]
Please reopen if you still need help
