### ISSUE TITLE
Failed to change password.

### ISSUE THREAD

**Issue by zuzy** [platformio/platformio-atom-ide#461]
Error: Error: [API] Account: Invalid old password

    at file:///C:/Users/zizy/.atom/packages/platformio-ide/lib/account/helpers.js:30:25
    at onExit (file:///C:/Users/zizy/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/zizy/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\zizy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\zizy\AppData\Local\atom\app-1.16.0\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Do you use valid old password?
