### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by DPDmancul** [platformio/platformio-atom-ide#462]
Error: Error: connect ETIMEDOUT 192.30.253.113:443
    at ProjectExamplesStage.<anonymous> (/home/dpd-/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/home/dpd-/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Thanks a lot for the report! We fixed it in the latest development version https://github.com/platformio/platformio-atom-ide/commit/19ea3e8a8c22c1d4fbbfbc1d657a44546d443120

**Comment by ivankravets** [comment]
Try to restart Atom
