### ISSUE TITLE
InstallationManager: Error: Error: unexpected end of file

### ISSUE THREAD

**Issue by fuzumoe** [platformio/platformio-atom-ide#470]
Error: Error: unexpected end of file
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Adam/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\Adam\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Could try to uninstall/install `platformio-ide` package again?

**Comment by ivankravets** [comment]
Please upgrade to the latest PIO IDE
