### ISSUE TITLE
Cannot read property 'entities' of null

### ISSUE THREAD

**Issue by laveur** [platformio/platformio-atom-ide#472]
Enter steps to reproduce:

1. Updated to latest version of atom and platform io
2. Restart atom.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.5
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-beta.3.1

### Stack Trace

Failed to activate the platformio-ide package

```
At Cannot read property 'entities' of null

TypeError: Cannot read property 'entities' of null
    at combination (/packages/platformio-ide/node_modules/redux/lib/combineReducers.js:131:38)
    at dispatch (/packages/platformio-ide/node_modules/redux/lib/createStore.js:179:22)
    at createStore (/packages/platformio-ide/node_modules/redux/lib/createStore.js:253:3)
    at /packages/platformio-ide/node_modules/redux/lib/applyMiddleware.js:38:19
    at createStore (/packages/platformio-ide/node_modules/redux/lib/createStore.js:65:33)
    at initStore (/packages/platformio-ide/lib/core/store.js:40:17)
    at PlatformIOIDEPackage.activate (/packages/platformio-ide/lib/main.js:61:7)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/app.asar/src/package-manager.js:581:36)
    at /app.asar/src/package-manager.js:512:17
```

### Commands

```
     -0:18 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.67.0 
busy 0.7.0 
file-icons 2.1.3 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.2.3 
minimap 4.27.1 
platformio-ide 2.0.0-beta.3.1 
platformio-ide-debugger 1.2.0 
platformio-ide-terminal 2.5.0 
tool-bar 1.1.0 
```

**Comment by laveur** [comment]
Seems that it fixed it self when I closed the current project I had open. Not sure what happened otherwise.
