### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jasonoviedo** [platformio/platformio-atom-ide#476]
Error: Error: ENOENT: no such file or directory, open '/Users/jasonoviedo/.atom/packages/platformio-ide/.cache/examples.tar.gz'
    at ProjectExamplesStage.<anonymous> (/Users/jasonoviedo/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/jasonoviedo/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Do you see this error after Atom restart?

**Comment by ivankravets** [comment]
Atom > Settings > Updates

Restart Atom
