### ISSUE TITLE
Library command failed: lib install 89: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by GoRo33** [platformio/platformio-atom-ide#487]
Error: Error: Traceback (most recent call last):
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py", line 97, in lib_install
    lm.install(library, silent=silent, interactive=interactive)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py", line 252, in install
    trigger_event)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 627, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py", line 231, in _install_from_piorepo
    if app.get_setting("enable_ssl") else dl_data['url'], requirements)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 361, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 172, in download
    fd = FileDownloader(url, dest_dir)
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/site-packages/platformio/downloader.py", line 50, in __init__
    self.set_destination(join(dest_dir, self._fname))
  File "/Users/Justyna&Grzegorz/.platformio/penv/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 20: ordinal not in range(128)

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

    at utils.runPIOCommand.spawnOptions (/Users/Justyna&Grzegorz/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (/Users/Justyna&Grzegorz/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/Justyna&Grzegorz/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Which library do you want to install?

**Comment by ivankravets** [comment]
Please reopen if you still need help
