### ISSUE TITLE
Platform command failed: platform install espressif32

### ISSUE THREAD

**Issue by tuhuynh** [platformio/platformio-atom-ide#490]
Error: Error: Could not find a version that satisfies the requirement '~1.50200.0' for your system 'linux_i686'

    at /home/httu/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/home/httu/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/httu/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /opt/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type:
```
pio platform install espressif32
```

Does it work?

**Comment by ivankravets** [comment]
Please reopen if you still need help
