### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by jm4rcos** [platformio/platformio-atom-ide#495]
Error: undefined

    at utils.runAPMCommand.busyTitle (/home/jmarcos/.atom/packages/platformio-ide/lib/installer/ide.js:154:77)
    at onExit (/home/jmarcos/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/jmarcos/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:338:1)
    at /opt/atom/resources/app/src/buffered-process.js:359:1
    at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please upgrade via Atom > Settings > Updates
