### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [platformio/platformio-atom-ide#496]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\me\.atom\packages\platformio-ide\node_modules\minimist\example\parse.js'
    at Error (native)

    at utils.runAPMCommand.busyTitle (file:///C:/Users/me/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (file:///C:/Users/me/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/me/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\me\AppData\Local\atom\app-1.17.0\resources\app\src\buffered-process.js:338:1)
    at C:\Users\me\AppData\Local\atom\app-1.17.0\resources\app\src\buffered-process.js:359:1
    at Socket.<anonymous> (C:\Users\me\AppData\Local\atom\app-1.17.0\resources\app\src\buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please upgrade via Atom > Settings > Updates
