### ISSUE TITLE
InstallationManager: setuptools pip wheel failed with error code 2

### ISSUE THREAD

**Issue by quando1** [platformio/platformio-atom-ide#499]
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\quand\AppData\Local\Temp\tmp-7844f8Ly8OdgcjDZ\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\quand\AppData\Local\Temp\tmp-7844f8Ly8OdgcjDZ\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\quand\AppData\Local\Temp\tmp-7844f8Ly8OdgcjDZ\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\quand\AppData\Local\Temp\tmp-7844f8Ly8OdgcjDZ\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\quand\AppData\Local\Temp\tmp-7844f8Ly8OdgcjDZ\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\quand\.plat...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please mail me@ikravets.com for detailed instructions. Thanks!

**Comment by ivankravets** [comment]
Please provide an output from `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by me21** [comment]
It was fixed for me by installing virtualenv package in Python manually.
