### ISSUE TITLE
InstallationManager: AttributeError: 'module' object has no attribute 'F_GETFD'

### ISSUE THREAD

**Issue by radiosonder** [platformio/platformio-atom-ide#501]
Virtualenv Download: Traceback (most recent call last):
  File "C:\Users\xman\AppData\Local\Temp\tmp-3796sT54qXfKLYZy\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\xman\AppData\Local\Temp\tmp-3796sT54qXfKLYZy\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\xman\AppData\Local\Temp\tmp-3796sT54qXfKLYZy\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\xman\AppData\Local\Temp\tmp-3796sT54qXfKLYZy\virtualenv-14.0.6\virtualenv.py", line 846, in install_wheel
    cert_file = tempfile.NamedTemporaryFile(delete=False)
  File "c:\Python27\Lib\tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "c:\Python27\Lib\tempfile.py", line 245, in _mkstemp_inner
    _set_cloexec(fd)
  File "c:\Python27\Lib\tempfile.py", line 50, in _set_cloexec
    flags = _fcntl.fcntl(fd, _fcntl.F_GETFD, 0)
AttributeError: 'module' object has no attribute 'F_GETFD'

win7 sp1

**Comment by ivankravets** [comment]
Please provide
```
python --version
pip --version
virtualenv --version
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
