### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by dagrende** [platformio/platformio-atom-ide#508]
Error: fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/dag/.atom/packages/platformio-ide/package.json'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Proxy.fs.readFileSync (fs.js:508:33)
  at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
  at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:470:42
  at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
  at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
  at runCallback (timers.js:649:20)
  at tryOnImmediate (timers.js:622:5)
  at processImmediate [as _immediateCallback] (timers.js:594:5)

    at utils.runAPMCommand.busyTitle (/Users/dag/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (/Users/dag/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/dag/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please uninstall/install PlatformIO IDE package in Atom > Settings > Packages
