### ISSUE TITLE
InstallationManager: ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by chiduc80** [platformio/platformio-atom-ide#524]
Virtualenv Download: Traceback (most recent call last):
  File "F:\Temp\tmp-8520BxbYhEM52Axi\virtualenv-15.1.0\virtualenv.py", line 2328, in <module>
    main()
  File "F:\Temp\tmp-8520BxbYhEM52Axi\virtualenv-15.1.0\virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "F:\Temp\tmp-8520BxbYhEM52Axi\virtualenv-15.1.0\virtualenv.py", line 945, in create_environment
    download=download,
  File "F:\Temp\tmp-8520BxbYhEM52Axi\virtualenv-15.1.0\virtualenv.py", line 848, in install_wheel
    from urllib.parse import urljoin
  File "C:\Python27\lib\urllib.py", line 26, in <module>
    import socket
  File "C:\Python27\lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by ivankravets** [comment]
I see that you don't use the latest PIO IDE Installer. Could you reinstall with http://docs.platformio.org/en/latest/ide/atom.html#uninstall-atom-with-platformio-ide ?

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by Msiavashi** [comment]
i've got the same problem . both on atom and vscode .
