### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by MabeleL** [platformio/platformio-atom-ide#526]
Error: Traceback (most recent call last):
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 106, in main
    cli(None, None, None)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 75, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 66, in on_platformio_start
    after_upgrade(ctx)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 173, in after_upgrade
    if u.run(ctx):
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 111, in run
    result.append(callback(ctx))
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 154, in _update_dev_platforms
    ctx.invoke(cmd_platform_update)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/platform.py", line 373, in platform_update
    platform, only_packages=only_packages, only_check=only_check)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py", line 115, in update
    p = PlatformFactory.newPlatform(pkg_dir)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py", line 201, in newPlatform
    if isdir(name):
  File "/home/mabele/.platformio/penv/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/commit/5da5bd43e4138ecef0b001cb312138e55d73c2ec
