### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by nbeAnomes** [platformio/platformio-atom-ide#535]
Error: undefined

    at utils.runAPMCommand.busyTitle (/Users/nicolasbertrand/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (/Users/nicolasbertrand/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/nicolasbertrand/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:322:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please upgrade via Atom > Settings > Updates
