### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by piodabro** [platformio/platformio-atom-ide#539]
Virtualenv Download: Traceback (most recent call last):
  File "<there was AppData path>\Local\Temp\tmp-18472XPJ6dP4oh7sQ\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "<there was AppData path>\Local\Temp\tmp-18472XPJ6dP4oh7sQ\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "<there was AppData path>\Local\Temp\tmp-18472XPJ6dP4oh7sQ\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "<there was AppData path>\Local\Temp\tmp-18472XPJ6dP4oh7sQ\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "<there was AppData path>\Local\Temp\tmp-18472XPJ6dP4oh7sQ\virtualenv-14.0.6\virtualenv.py", line 780, in call_subprocess
    logger.notify('\n'.join(all_output) + '\n----------------------------------------')
  File "<there was AppData path>\Local\Temp\tmp-18472XPJ6dP4oh7sQ\virtualenv-14.0.6\virtualenv.py", line 193, in notify
    self.log(self.NOTIFY, msg, *args, **kw)
  File "<there was AppData path>\Local\Temp\tmp-18472XPJ6dP4oh7sQ\virtualenv-14.0.6\virtualenv.py", line 225, in log
    consumer.write(rendered+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0119' in position 2916: ordinal not in range(128)

**Comment by piodabro** [comment]
This happened when updated to 2.0.0.-beta.4.
Also clean Atom installation shows the same.
Sys: Windows 10

**Comment by alexodus** [comment]
me too

**Comment by ivankravets** [comment]
Try to remove `~/.platformio` folder and start again
