### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by zwanh** [platformio/platformio-atom-ide#544]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/zwh/.atom/packages/platformio-ide/node_modules/har-validator/LICENSE'
    at Error (native)

    at utils.runAPMCommand.busyTitle (/Users/zwh/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (/Users/zwh/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/zwh/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please update IDE via Atom > Settings > Updates
