### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by nicolalandro** [platformio/platformio-atom-ide#546]
Error: Unable to download https://www.atom.io/api/packages/platformio-ide/versions/2.0.0-beta.4/tarball: 503

    at utils.runAPMCommand.busyTitle (/home/mint/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (/home/mint/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/home/mint/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please update IDE via Atom > Settings > Updates
