### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by lugerh** [platformio/platformio-atom-ide#555]
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (/home/<user>/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/home/<user>/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-atom-ide/commit/715afa1ca1929e34961981a027944bf390f0ab1e
