### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by Vollbrecht** [platformio/platformio-atom-ide#563]
Error: /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/fred/.atom/packages/platformio-ide/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (/usr/share/atom/resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /usr/share/atom/resources/app/apm/lib/install.js:470:42
    at fn (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

    at utils.runAPMCommand.busyTitle (/home/fred/.atom/packages/platformio-ide/lib/installer/ide.js:154:77)
    at onExit (/home/fred/.atom/packages/platformio-ide/lib/utils.js:144:7)
    at exit (/home/fred/.atom/packages/platformio-ide/lib/utils.js:159:14)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:322:11)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Fixed in the latest Beta 6. 

Please update it via Atom > Settings > Updates
