### ISSUE TITLE
Platform command failed: platform frameworks --json-output

### ISSUE THREAD

**Issue by hop666** [platformio/platformio-atom-ide#564]
Error: Error: Could not load broken JSON: /Users/poduszczak/.platformio/appstate.json

    at /Users/poduszczak/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/Users/poduszczak/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/poduszczak/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Do you run Atom with administrative priveledges? Try without.
