### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mmikel** [platformio/platformio-atom-ide#566]
Traceback (most recent call last):
  File "/home/mmikel/.platformio/penv/bin/platformio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>

    @_call_aside
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside

    f(*args, **kwargs)
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 862, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2568, in requires

    dm = self._dep_map
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2815, in _dep_map

    self.__dep_map = self._compute_dependencies()
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2824, in _compute_dependencies

    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2806, in _parsed_pkg_info

    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/mmikel/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1861, in get_metadata

    raise KeyError("No metadata except PKG-INFO is available")

KeyError: 'No metadata except PKG-INFO is available'

**Comment by ivankravets** [comment]
Please remove `/home/mmikel/.platformio/penv` and restart Atom
