### ISSUE TITLE
Uninstall incompatible packages: platformio-ide-terminal

### ISSUE THREAD

**Issue by joaopedrowinhaski** [platformio/platformio-atom-ide#570]
Error: Failed to delete platformio-ide-terminal: EPERM: operation not permitted, unlink 'C:\Users\joaopedro\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\winpty.x64.dll'

    at file:///C:/Users/joaopedro/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:137:27
    at onExit (file:///C:/Users/joaopedro/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/joaopedro/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\joaopedro\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:338:1)
    at ChildProcess.<anonymous> (C:\Users\joaopedro\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Atom > Settings > Updates

Please update all packages.
