### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by joaopedrowinhaski** [platformio/platformio-atom-ide#571]
Error: Error: Failed to delete platformio-ide-terminal: EPERM: operation not permitted, unlink 'C:\Users\joaopedro\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\winpty.x64.dll'

    at AtomDependenciesStage.<anonymous> (file:///C:/Users/joaopedro/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:192:13)
    at throw (<anonymous>)
    at step (C:\Users\joaopedro\.atom\packages\platformio-ide\lib\installer\stages\atom-dependencies.js:15:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Atom -> Settings > Updates 

Please update all packages manually.
