### ISSUE TITLE
Problem occurred while upgrading PlatformIO IDE.

### ISSUE THREAD

**Issue by ButchAnton** [platformio/platformio-atom-ide#574]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/butch/.atom/packages/platformio-ide/.editorconfig'
    at Error (native)

    at utils.runAPMCommand.busyTitle (/Users/i831533/.atom/packages/platformio-ide/lib/installer/ide.js:154:77)
    at onExit (/Users/i831533/.atom/packages/platformio-ide/lib/utils.js:144:7)
    at exit (/Users/i831533/.atom/packages/platformio-ide/lib/utils.js:159:14)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Fixed in Beta 6. Please update manually via 
Atom > Settings > Updates
