### ISSUE TITLE
Library command failed: lib list --json-output

### ISSUE THREAD

**Issue by APerlman2015** [platformio/platformio-atom-ide#577]
Error: Error: Could not load broken JSON: C:\SPB_Data\.platformio\appstate.json

    at utils.runPIOCommand.spawnOptions (file:///C:/Users/Aperl/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (file:///C:/Users/Aperl/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/Aperl/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\Aperl\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:338:1)
    at ChildProcess.<anonymous> (C:\Users\Aperl\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Do you run Atom with administrative priveledges? Try without.
