### ISSUE TITLE
C/C++ project index rebuild failed, PlatformIO: Failed to initialize PlatformIO Project

### ISSUE THREAD

**Issue by Abraxas3d** [platformio/platformio-atom-ide#578]
Newly installed and updated PlatformIO Atom editor, attempted "+ New Project", selected board and directory: 

Traceback (most recent call last):
File "/Users/w5nyv/.platformio/packages/tool-scons/script/scons", line 190, in <module>

import SCons.Script
ImportError: No module named SCons.Script

========================== [ERROR] Took 0.31 seconds ==========================

Traceback (most recent call last):
File "/Users/w5nyv/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script
========================== [ERROR] Took 0.32 seconds ==========================

**Comment by ivankravets** [comment]
try to remove `/Users/w5nyv/.platformio/packages/tool-scons/` and start again
