### ISSUE TITLE
Platform command failed: platform frameworks --json-output

### ISSUE THREAD

**Issue by jormar** [platformio/platformio-atom-ide#579]
Error: Error: Traceback (most recent call last):
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py", line 200, in platform_frameworks
    platform['name'] for platform in _get_registry_platforms()
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py", line 50, in _get_registry_platforms
    platforms = util.get_api_result("/platforms", cache_valid="30d")
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 516, in get_api_result
    result = cc.get(cache_key)
  File "/Users/jormar/.platformio/penv/lib/python2.7/site-packages/platformio/app.py", line 191, in get
    return json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting : delimiter: line 1 column 4097 (char 4096)

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

    at /Users/jormar/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/Users/jormar/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/jormar/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Something wrong with the internet connection, please try again.
