### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by nano8ot** [platformio/platformio-atom-ide#582]
Error: undefined

    at utils.runAPMCommand.busyTitle (/Users/jacek/.atom/packages/platformio-ide/lib/installer/ide.js:154:77)
    at onExit (/Users/jacek/.atom/packages/platformio-ide/lib/utils.js:144:7)
    at exit (/Users/jacek/.atom/packages/platformio-ide/lib/utils.js:159:14)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please upgrade IDE via 

Atom > Settings > Updates
