### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by wjm0621** [platformio/platformio-atom-ide#585]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-beta.6

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 1

```
At file:///C:/Users/AI_Lab/AppData/Local/atom/app-1.17.2/resources/app/static/index.html:2

SyntaxError: Unexpected token < in JSON at position 1
    at Object.parse (native)
    at /packages/platformio-ide/lib/installer/ide.js:81:65
    at Request._callback (/packages/platformio-ide/lib/utils.js:184:12)
    at Request.self.callback (/packages/platformio-ide/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/platformio-ide/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/platformio-ide/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:47.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.1 
file-icons 2.1.7 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment]
It looks like you had a problem with Internet connection
