### ISSUE TITLE
Install missed packages: linter,linter-gcc,language-ini,tool-bar,file-icons,minimap

### ISSUE THREAD

**Issue by venkatramanp** [platformio/platformio-atom-ide#592]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/vpoornalingam/.atom/packages/linter/node_modules/sb-callsite/.npmignore'
    at Error (native)

    at /Users/vpoornalingam/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:86:27
    at onExit (/Users/vpoornalingam/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/vpoornalingam/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/private/var/folders/rh/xlx_5_ld1p1cv1xmby0kll800000gn/T/AppTranslocation/A01824F8-E29A-4F3A-90BF-A43F0D7060FC/d/Atom-2.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (/private/var/folders/rh/xlx_5_ld1p1cv1xmby0kll800000gn/T/AppTranslocation/A01824F8-E29A-4F3A-90BF-A43F0D7060FC/d/Atom-2.app/Contents/Resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please restart Atom with active Internet connection
