### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by frank3141** [platformio/platformio-atom-ide#597]
Error: Couldn't clone https://github.com/platformio/platformio-atom-ide.git or git+ssh://git@github.com/platformio/platformio-atom-ide.git

    at utils.runAPMCommand.busyTitle (file:///d:/Users/frank/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (file:///d:/Users/frank/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///d:/Users/frank/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (D:\Users\frank\AppData\Local\atom\app-1.17.0\resources\app\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (D:\Users\frank\AppData\Local\atom\app-1.17.0\resources\app\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by frank3141** [comment]
Restart seemed to fix this.  IDE is now listed as up to date, newest version available
