### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by mett96** [platformio/platformio-atom-ide#599]
Error: undefined

    at utils.runAPMCommand.busyTitle (/Users/mattiasanchioni/.atom/packages/platformio-ide/lib/installer/ide.js:154:77)
    at onExit (/Users/mattiasanchioni/.atom/packages/platformio-ide/lib/utils.js:144:7)
    at exit (/Users/mattiasanchioni/.atom/packages/platformio-ide/lib/utils.js:159:14)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Please upgrade IDE via 

Atom > Settings > Updates
