### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by PierreAuge** [platformio/platformio-atom-ide#606]
Traceback (most recent call last):
  File "/home/pierre/.platformio/penv/bin/platformio", line 11, in <module>

    
  File "/home/pierre/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pierre/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point

    return ep.load()
  File "/home/pierre/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2303, in load

    return self.resolve()
  File "/home/pierre/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2309, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pierre/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 23, in <module>

  File "/home/pierre/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 25, in <module>

    from platformio.commands.lib import lib_update as cmd_lib_update

ImportError: No module named commands.lib

**Comment by ivankravets** [comment]
Please remove `/home/pierre/.platformio/penv` and restart Atom
