### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by MabeleL** [platformio/platformio-atom-ide#614]
Error: Traceback (most recent call last):
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/init.py", line 103, in cli
    pg.generate()
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 121, in generate
    self._render_tpl(tpl_path).encode("utf8"))
  File "/home/mabele/.platformio/penv/local/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 148, in _merge_contents
    f.write(contents)
IOError: [Errno 28] No space left on device

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
IOError: [Errno 28] No space left on device
