### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by ziron4** [platformio/platformio-atom-ide#629]
I got an error while updating to the newest version
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\lars s\.atom\packages\platformio-ide\node_modules\highlight.js\LICENSE'
    at Error (native)

    at utils.runAPMCommand.busyTitle (C:\Users\lars s\.atom\packages\platformio-ide\lib\installer\ide.js:154:77)
    at onExit (C:\Users\lars s\.atom\packages\platformio-ide\lib\utils.js:144:7)
    at exit (C:\Users\lars s\.atom\packages\platformio-ide\lib\utils.js:159:14)
    at triggerExitCallback (C:\Users\lars s\AppData\Local\atom\app-1.17.0\resources\app\src\buffered-process.js:338:1)
    at ChildProcess.<anonymous> (C:\Users\lars s\AppData\Local\atom\app-1.17.0\resources\app\src\buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please upgrade IDE via 

Atom > Settings > Updates
