### ISSUE TITLE
InstallationManager: setuptools pip wheel failed with error code 2

### ISSUE THREAD

**Issue by suchakra** [platformio/platformio-atom-ide#630]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/xz/lz759kdd34b1_1_yzpv0ssz40000gn/T/tmp-59349qtN4oHTJ97f0/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/var/folders/xz/lz759kdd34b1_1_yzpv0ssz40000gn/T/tmp-59349qtN4oHTJ97f0/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)

  File "/var/folders/xz/lz759kdd34b1_1_yzpv0ssz40000gn/T/tmp-59349qtN4oHTJ97f0/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment

    download=download,
  File "/var/folders/xz/lz759kdd34b1_1_yzpv0ssz40000gn/T/tmp-59349qtN4oHTJ97f0/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/var/folders/xz/lz759kdd34b1_1_yzpv0ssz40000gn/T/tmp-59349qtN4oHTJ97f0/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess

    % (cmd_desc, proc.returncode))
OSError: Command /Users/SUMABTCH/.platformio/penv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please provide an output from system Terminal 
```
echo $PATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
1. Please open Atom > Settings > Packages > PlatformIO IDE
2. Check "Advanced > Use development version of PlatformIO IDE"
3. Wait while Atom will re-install PIO IDE

Does it work now?
