### ISSUE TITLE
InstallationManager: ImportError: cannot import name HTTPSHandler

### ISSUE THREAD

**Issue by Huynhtri027** [platformio/platformio-atom-ide#632]
Virtualenv Download: Traceback (most recent call last):
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment

    download=download,
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv.py", line 843, in install_wheel

    cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")
  File "/usr/local/lib/python2.7/pkgutil.py", line 578, in get_data

    loader = get_loader(package)
  File "/usr/local/lib/python2.7/pkgutil.py", line 464, in get_loader

    return find_loader(fullname)
  File "/usr/local/lib/python2.7/pkgutil.py", line 474, in find_loader

    for importer in iter_importers(fullname):
  File "/usr/local/lib/python2.7/pkgutil.py", line 430, in iter_importers

    __import__(pkg)
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>

  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/index.py", line 29, in <module>
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/tmp/tmp-21240lOc9JwyiLLRr/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 31, in <module>

ImportError: cannot import name HTTPSHandler

**Comment by ivankravets** [comment]
Please provide an output from system Terminal 
```
echo $PATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
