### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by J-f-Jensen** [platformio/platformio-atom-ide#641]
Error: undefined

    at utils.runAPMCommand.busyTitle (C:\Users\Bruger\.atom\packages\platformio-ide\lib\installer\ide.js:154:77)
    at onExit (C:\Users\Bruger\.atom\packages\platformio-ide\lib\utils.js:144:7)
    at exit (C:\Users\Bruger\.atom\packages\platformio-ide\lib\utils.js:159:14)
    at triggerExitCallback (C:\Users\Bruger\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:338:1)
    at ChildProcess.<anonymous> (C:\Users\Bruger\AppData\Local\atom\app-1.17.2\resources\app\src\buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by J-f-Jensen** [comment]
I don't know if you have seen this before, it looks like its still working when I build code+
