### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by TomAuger** [platformio/platformio-atom-ide#650]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/elrond/.atom/packages/platformio-ide/lib/base-view.js'
    at Error (native)

    at utils.runAPMCommand.busyTitle (/Users/elrond/.atom/packages/platformio-ide/lib/installer/ide.js:154:77)
    at onExit (/Users/elrond/.atom/packages/platformio-ide/lib/utils.js:144:7)
    at exit (/Users/elrond/.atom/packages/platformio-ide/lib/utils.js:159:14)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please upgrade IDE via 

Atom > Settings > Updates
