### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by saschaludwig** [platformio/platformio-atom-ide#654]
Got this Error Message, I have no idea if this report will help anyone.
IDE 2.0.0-beta.6 Core 3.4.0rc1

---
Error: Request for package information failed: getaddrinfo ENOTFOUND atom.io atom.io:443

    at utils.runAPMCommand.busyTitle (/Users/sascha/.atom/packages/platformio-ide/lib/installer/ide.js:111:13)
    at onExit (/Users/sascha/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/sascha/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please update PIO IDE manually via Atom > Settings > Updates
