### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by MichalKrakow** [platformio/platformio-atom-ide#656]
Error: Traceback (most recent call last):
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 74, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 68, in on_platformio_start
    after_upgrade(ctx)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 192, in after_upgrade
    if u.run(ctx):
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 113, in run
    result.append(callback(ctx))
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 156, in _update_dev_platforms
    ctx.invoke(cmd_platform_update)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py", line 342, in platform_update
    for manifest in pm.get_installed():
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 268, in get_installed
    manifest = self.load_manifest(pkg_dir)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 232, in load_manifest
    src_manifest_path = self.get_src_manifest_path(pkg_dir)
  File "/Users/test/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 203, in get_src_manifest_path
    for item in os.listdir(pkg_dir):
OSError: [Errno 13] Permission denied: '/Users/test/.platformio/platforms/atmelavr'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please remove `/Users/test/.platformio` folder and start build again
