### ISSUE TITLE
Problem has been occured while installing PlatformIO IDE.

### ISSUE THREAD

**Issue by AlexandreLeone** [platformio/platformio-atom-ide#671]
Error: Cloning https://github.com/platformio/platformio-atom-ide.git failed

Installing modules done
Cannot read property 'getReferenceTarget' of null

    at C:\Users\user\.atom\packages\platformio-ide\lib\installer\ide.js:66:84
    at throw (<anonymous>)
    at step (C:\Users\user\.atom\packages\platformio-ide\lib\installer\ide.js:89:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please update IDE using Atom > Settings > Updates
