### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mverleun** [platformio/platformio-atom-ide#674]
Error: Error: unexpected end of file
    at ProjectExamplesStage.<anonymous> (/Users/marco/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/marco/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please uninstall PlatformIO IDE package and install it again
