### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by kskenyon** [platformio/platformio-atom-ide#676]
Traceback (most recent call last):
  File "/Users/private/.platformio/penv/bin/platformio", line 11, in <module>
  File "/Users/private/.platformio/penv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/private/.platformio/penv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2647, in load_entry_point

    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'platformio') not found

**Comment by ivankravets** [comment]
Please remove /Users/private/.platformio/penv folder and restart IDE
