### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ecoPlanosVasco** [platformio/platformio-atom-ide#677]
Virtualenv Create: Traceback (most recent call last):
  File "/home/xubuntu/.platformio/.cache-ide/tmp-5684H1Cio8BE7R4t/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/home/xubuntu/.platformio/.cache-ide/tmp-5684H1Cio8BE7R4t/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/home/xubuntu/.platformio/.cache-ide/tmp-5684H1Cio8BE7R4t/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/xubuntu/.platformio/.cache-ide/tmp-5684H1Cio8BE7R4t/virtualenv-14.0.6/virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device

**Comment by ivankravets** [comment]
No space left on device
