### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by giapdangle** [platformio/platformio-atom-ide#680]
Error: Error: ENOENT: no such file or directory, open '/Users/giaple/.atom/packages/platformio-ide/.cache/examples.tar.gz'
  at ProjectExamplesStage.<anonymous> (/Users/giaple/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:201:15)
  at undefined.throw (<anonymous>:null:null)
  at step (/Users/giaple/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please restart Atom
