### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by idmontie** [platformio/platformio-atom-ide#684]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/ivanmontiel/.platformio/.cache-ide/tmp-35250R4PIrRgcKC8/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/Users/ivanmontiel/.platformio/.cache-ide/tmp-35250R4PIrRgcKC8/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/Users/ivanmontiel/.platformio/.cache-ide/tmp-35250R4PIrRgcKC8/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/ivanmontiel/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/Users/ivanmontiel/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment]
Please remove `/Users/ivanmontiel/.platformio/penv` and restart Atom
