### ISSUE TITLE
Library command failed: lib --storage-dir D:\Projects\[Arduino]\IDE\arduino-1.8.1\libraries\ list --json-output

### ISSUE THREAD

**Issue by SaeidArya** [platformio/platformio-atom-ide#687]
Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "D:\Projects\[Arduino]\IDE\arduino-1.8.1\libraries" list --json-output" does not exist.

    at utils.runPIOCommand.spawnOptions (file:///C:/Users/irdev/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (file:///C:/Users/irdev/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/irdev/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\irdev\AppData\Local\atom\app-1.18.0\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\irdev\AppData\Local\atom\app-1.18.0\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
