### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ezekiellanek** [platformio/platformio-atom-ide#691]
Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\Admin\.platformio\project-examples\atmelavr\arduino-external-libs\lib'
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Admin/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (C:\Users\Admin\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please close Atom, remove this folder `C:\Users\Admin\.platformio` and start Atom again
