### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ruipcunha** [platformio/platformio-atom-ide#693]
Error: Error: unexpected end of file
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Rui_Cunha/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\Rui_Cunha\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please uninstall and install `platformio-ide` package.

**Comment by ruipcunha** [comment]
Seems to be fixed.
Thanks!
