### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Helix70** [platformio/platformio-atom-ide#695]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Z0035SJY\.platformio\.cache-ide\tmp-10160IPEf6x6Xm5TJ\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Z0035SJY\.platformio\.cache-ide\tmp-10160IPEf6x6Xm5TJ\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Z0035SJY\.platformio\.cache-ide\tmp-10160IPEf6x6Xm5TJ\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\Z0035SJY\.platformio\.cache-ide\tmp-10160IPEf6x6Xm5TJ\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\Z0035SJY\.platformio\.cache-ide\tmp-10160IPEf6x6Xm5TJ\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\Z0035SJY\.p...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please remove this folder `C:\Users\Z0035SJY\.platformio` and start Atm again
