### ISSUE TITLE
InstallationManager: UnicodeDecodeError: 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by ecoPlanosVasco** [platformio/platformio-atom-ide#699]
Virtualenv Create: Traceback (most recent call last):
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment
    download=download,
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv.py", line 843, in install_wheel
    cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")
  File "/usr/lib/python2.7/pkgutil.py", line 578, in get_data

    loader = get_loader(package)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader

    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader

    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers

    __import__(pkg)
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>

  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/utils/__init__.py", line 26, in <module>

  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3130, in <module>
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3116, in _call_aside
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 3143, in _initialize_master_working_set

  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 633, in _build_master
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 626, in __init__

  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 682, in add_entry
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2120, in find_on_path
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2510, in from_location
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2827, in _reload_version
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2475, in _version_from_file
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2643, in _get_metadata
  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2011, in get_metadata_lines

  File "/home/vascostmr/.platformio/.cache-ide/tmp-1216gO13R2XbzMsZ/virtualenv-14.0.6/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 2006, in get_metadata
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 147: invalid start byte

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
