### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by BrenoMiyazaki** [platformio/platformio-atom-ide#701]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\breno\.platformio\.cache-ide\tmp-47860IZrUgzYp3kfq\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\breno\.platformio\.cache-ide\tmp-47860IZrUgzYp3kfq\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\breno\.platformio\.cache-ide\tmp-47860IZrUgzYp3kfq\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\breno\.platformio\.cache-ide\tmp-47860IZrUgzYp3kfq\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\breno\.platformio\.cache-ide\tmp-47860IZrUgzYp3kfq\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Acesso negado

**Comment by ivankravets** [comment]
Please remove `C:\Users\breno\.platformio` folder and rerstart atom
