### ISSUE TITLE
InstallationManager: setuptools pip wheel failed with error code 2

### ISSUE THREAD

**Issue by swilalaa** [platformio/platformio-atom-ide#702]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/74/717cmqhs4wb2sv408dzl7hkh0000gn/T/tmp-3954rVnCVXonEhrM/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/var/folders/74/717cmqhs4wb2sv408dzl7hkh0000gn/T/tmp-3954rVnCVXonEhrM/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/var/folders/74/717cmqhs4wb2sv408dzl7hkh0000gn/T/tmp-3954rVnCVXonEhrM/virtualenv-14.0.6/virtualenv.py", line 924, in create_environment

    download=download,
  File "/var/folders/74/717cmqhs4wb2sv408dzl7hkh0000gn/T/tmp-3954rVnCVXonEhrM/virtualenv-14.0.6/virtualenv.py", line 877, in install_wheel

    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "/var/folders/74/717cmqhs4wb2sv408dzl7hkh0000gn/T/tmp-3954rVnCVXonEhrM/virtualenv-14.0.6/virtualenv.py", line 783, in call_subprocess

    % (cmd_desc, proc.returncode))

OSError: Command /Users/KS/.platformio/penv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
