### ISSUE TITLE
Platform command failed: platform list --json-output

### ISSUE THREAD

**Issue by pavel1024** [platformio/platformio-atom-ide#706]
on my Mac

Error: Error: Traceback (most recent call last):
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py", line 217, in platform_list
    for manifest in pm.get_installed():
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 268, in get_installed
    manifest = self.load_manifest(pkg_dir)
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 232, in load_manifest
    src_manifest_path = self.get_src_manifest_path(pkg_dir)
  File "/Users/pavel/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 203, in get_src_manifest_path
    for item in os.listdir(pkg_dir):
OSError: [Errno 13] Permission denied: '/Users/pavel/.platformio/platforms/espressif8266'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

    at /Users/pavel/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (/Users/pavel/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/pavel/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/private/var/folders/8q/5d3hplnd38x8llglg1n_jw5c0000gn/T/AppTranslocation/36841693-AB5E-4487-9BB7-86A77F9293B1/d/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/private/var/folders/8q/5d3hplnd38x8llglg1n_jw5c0000gn/T/AppTranslocation/36841693-AB5E-4487-9BB7-86A77F9293B1/d/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please remove `/Users/pavel/.platformio` folder and restart Atom. If it didn't help, please reopen an issue.
