### ISSUE TITLE
Platform command failed: platform install pio platform install atmelavr

### ISSUE THREAD

**Issue by Giusmen2** [platformio/platformio-atom-ide#713]
Error: Error: Detected unknown package 'pio platform install atmelavr'

    at file:///C:/Users/Giuseppe/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
    at onExit (file:///C:/Users/Giuseppe/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/Giuseppe/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\Giuseppe\Desktop\Atom\resources\app.asar\src\buffered-process.js:322:11)
    at ChildProcess.<anonymous> (C:\Users\Giuseppe\Desktop\Atom\resources\app.asar\src\buffered-process.js:352:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
should be `atmelavr`
