### ISSUE TITLE
InstallationManager: Failed to download file

### ISSUE THREAD

**Issue by supermanny81** [platformio/platformio-atom-ide#714]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/mannygar/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/mannygar/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by supermanny81** [comment]
Restarted platform IO today and got this error on boot.  I might have started an update and closed it yesterday without noticing.

**Comment by ivankravets** [comment]
Does it work now?

**Comment by supermanny81** [comment]
It works now, thanks for checking in.
