### ISSUE TITLE
Uninstall incompatible packages: platformio-ide-terminal

### ISSUE THREAD

**Issue by kp3695** [platformio/platformio-atom-ide#716]
Error: Failed to delete platformio-ide-terminal: EPERM: operation not permitted, unlink 'C:\Users\Koreyp\.atom\packages\platformio-ide-terminal\node_modules\pty.js\build\Release\pty.node'

    at file:///C:/Users/Koreyp/.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:137:27
    at onExit (file:///C:/Users/Koreyp/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (file:///C:/Users/Koreyp/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (C:\Users\Koreyp\AppData\Local\learn_ide\app-2.5.3\resources\app.asar\src\buffered-process.js:303:11)
    at ChildProcess.<anonymous> (C:\Users\Koreyp\AppData\Local\learn_ide\app-2.5.3\resources\app.asar\src\buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please restart Atom and try again
