### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mattb5906** [platformio/platformio-atom-ide#718]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: self signed certificate in certificate chain
    at file:///C:/Users/matt.baker/.atom/packages/platformio-ide/lib/installer/helpers.js:49:9
    at throw (<anonymous>)
    at step (file:///C:/Users/matt.baker/.atom/packages/platformio-ide/lib/installer/helpers.js:156:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by mattb5906** [comment]
Just realised this was down to our anti-virus system blocking it.
