### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBoards' of undefined

### ISSUE THREAD

**Issue by karel1956** [platformio/platformio-atom-ide#72]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package, v1.0.5

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBoards' of undefined

```
At /C:/Users/Karel/.atom/packages/platformio-ide/lib/import-arduino-project/view.js:174

TypeError: Cannot read property 'getSelectedBoards' of undefined
    at ImportArduinoProjectView.getSelectedBoards (C:/Users/Karel/.atom/packages/platformio-ide/lib/import-arduino-project/view.js:142:29)
    at ImportArduinoProjectView.updateImportButtonDisabled (C:/Users/Karel/.atom/packages/platformio-ide/lib/import-arduino-project/view.js:159:12)
    at HTMLInputElement.ImportArduinoProjectView.useArduinoLibManager.onclick (C:/Users/Karel/.atom/packages/platformio-ide/lib/import-arduino-project/view.js:58:12)
```

### Commands

```
     -0:25.5.0 platformio-ide:import-arduino-ide-project (div.panels-item)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
platformio-ide, v1.0.5

# Dev
No dev packages
```

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide/commit/2731fe5bc8a5e2852fea1060380eaa8a363ee8e7

Could you try the latest development version https://github.com/platformio/platformio-atom-ide/archive/develop.zip? Don't forget to run `npm install` in `C:/Users/Karel/.atom/packages/platformio-ide`.
