### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Harrilamb** [platformio/platformio-atom-ide#720]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (/Users/HarrisonL/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/HarrisonL/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please remove `/Users/HarrisonL/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
