### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by wataruland** [platformio/platformio-atom-ide#728]
Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\Wataru\.platformio\project-examples\espressif\esp8266-wifiscan\lib'
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Wataru/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\Wataru\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please remove `C:/Users/Wataru/.platformio` folder and restart Atom. If it didn't help, please reopen an issue.
