### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by hanif85** [platformio/platformio-atom-ide#730]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Aji/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\Aji\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Just restart atom
