### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by sdixon99** [platformio/platformio-atom-ide#737]
Error: Error: incorrect header check
    at ProjectExamplesStage.<anonymous> (/Users/scott/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (/Users/scott/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Just restart Atom
