### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by wanglin1985** [platformio/platformio-atom-ide#742]
Error: Error: Error: Failed to download file http://dl.platformio.org/ide-data/platformio-examples.tar.gz: null
    at ProjectExamplesStage.<anonymous> (/Users/lin/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (/Users/lin/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please restart Atom
