### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by FanXuX** [platformio/platformio-atom-ide#754]
Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\faxu\.platformio\project-examples\atmelavr\digitstump-mouse\lib'
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/faxu/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (C:\Users\faxu\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please remove `C:\Users\faxu/.platformio` folder and restart Atom. If it didn't help, please reopen an issue.
