### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ShAzmoodeh** [platformio/platformio-atom-ide#756]
Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\Home\.platformio\project-examples\espressif\esp32-espidf-peripherals-uart\src'
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Home/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\Home\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please remove `C:\Users\Home/.platformio` folder and restart Atom. If it didn't help, please reopen an issue.
