### ISSUE TITLE
Library command failed: lib --global builtin --json-output

### ISSUE THREAD

**Issue by Syberteck** [platformio/platformio-atom-ide#758]
Error: Error: Traceback (most recent call last):
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py", line 297, in lib_builtin
    items = get_builtin_libs(storage)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 134, in __call__
    value = self.func(*args)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py", line 279, in get_builtin_libs
    for manifest in pm.get_installed():
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 268, in get_installed
    manifest = self.load_manifest(pkg_dir)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 232, in load_manifest
    src_manifest_path = self.get_src_manifest_path(pkg_dir)
  File "/Users/DellWin7/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 203, in get_src_manifest_path
    for item in os.listdir(pkg_dir):
OSError: [Errno 13] Permission denied: '/Users/DellWin7/.platformio/platforms/espressif8266'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

    at utils.runPIOCommand.spawnOptions (/Users/DellWin7/.atom/packages/platformio-ide/lib/library/helpers.js:39:25)
    at onExit (/Users/DellWin7/.atom/packages/platformio-ide/lib/utils.js:92:7)
    at exit (/Users/DellWin7/.atom/packages/platformio-ide/lib/utils.js:102:21)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
> Permission denied

Try to remove `/Users/DellWin7/.platformio` folder and start again
