### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by alihassan123** [platformio/platformio-atom-ide#762]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Ali Hassan\.platformio\.cache-ide\tmp-1984M2if3IWtL8t9\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Ali Hassan\.platformio\.cache-ide\tmp-1984M2if3IWtL8t9\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Ali Hassan\.platformio\.cache-ide\tmp-1984M2if3IWtL8t9\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\Ali Hassan\.platformio\.cache-ide\tmp-1984M2if3IWtL8t9\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\Lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\ALIHAS~1\\PLATFO~1\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please remove `C:\Users\Ali Hassan/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
