### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by LBTRONIC** [platformio/platformio-atom-ide#767]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\User\.platformio\.cache-ide\tmp-7524FMH6K4IYrJ59\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\User\.platformio\.cache-ide\tmp-7524FMH6K4IYrJ59\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\User\.platformio\.cache-ide\tmp-7524FMH6K4IYrJ59\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\User\.platformio\.cache-ide\tmp-7524FMH6K4IYrJ59\virtualenv-14.0.6\virtualenv.py", line 1101, in install_python
    copy_required_modules(home_dir, symlink)
  File "C:\Users\User\.platformio\.cache-ide\tmp-7524FMH6K4IYrJ59\virtualenv-14.0.6\virtualenv.py", line 1041, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "C:\Users\User\.platformio\.cache-ide\tmp-7524FMH6K4IYrJ59\virtualenv-14.0.6\virtualenv.py", line 1015, in change_prefix
    (filename, prefixes)
AssertionError: Filename C:\python27\Lib\os.py does not start with any of these prefixes: ['C:\\Python27']

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
