### ISSUE TITLE
Problem occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by yuvals2146** [platformio/platformio-atom-ide#771]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/student/.atom/packages/platformio-ide/.editorconfig'
    at Error (native)

    at utils.runAPMCommand.busyTitle (/Users/student/.atom/packages/platformio-ide/lib/installer/ide.js:154:77)
    at onExit (/Users/student/.atom/packages/platformio-ide/lib/utils.js:144:7)
    at exit (/Users/student/.atom/packages/platformio-ide/lib/utils.js:159:14)
    at triggerExitCallback (/private/var/folders/qt/5ky56zx96397451jmg49synr0000gp/T/AppTranslocation/14EA17C8-EA8F-4CB4-B60B-B0D1E0269011/d/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /private/var/folders/qt/5ky56zx96397451jmg49synr0000gp/T/AppTranslocation/14EA17C8-EA8F-4CB4-B60B-B0D1E0269011/d/Atom.app/Contents/Resources/app/src/buffered-process.js:359:1
    at Socket.<anonymous> (/private/var/folders/qt/5ky56zx96397451jmg49synr0000gp/T/AppTranslocation/14EA17C8-EA8F-4CB4-B60B-B0D1E0269011/d/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by ivankravets** [comment]
Just restart Atom
