### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platformio-atom-ide#773]
Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\gunterwe\.platformio\project-examples\raspberrypi\wiringpi-serial'
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/gunterwe/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (C:\Users\gunterwe\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please remove `C:\Users\gunterwe/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
