### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by kruebsam** [platformio/platformio-atom-ide#774]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Michael\.platformio\.cache-ide\tmp-2000ENtNTNP1wBzu\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Michael\.platformio\.cache-ide\tmp-2000ENtNTNP1wBzu\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Michael\.platformio\.cache-ide\tmp-2000ENtNTNP1wBzu\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\Michael\.platformio\.cache-ide\tmp-2000ENtNTNP1wBzu\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\Michael\.platformio\.cache-ide\tmp-2000ENtNTNP1wBzu\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Zugriff verweigert

**Comment by ivankravets** [comment]
Please remove `C:\Users\Michael/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
