### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by wjnforever** [platformio/platformio-atom-ide#780]
Error: Error: EPERM: operation not permitted, mkdir 'C:\Users\wujing\.platformio\project-examples\stm32\arduino-blink\lib'
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/wujing/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (C:\Users\wujing\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
> operation not permitted

Is something wrong with permissions?  Could you remove `C:\Users\wujing\.platformio` folder and restart?
