### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by RayTimlin** [platformio/platformio-atom-ide#785]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: 
    at file:///C:/Users/raytim/.atom/packages/platformio-ide/lib/installer/helpers.js:49:9
    at next (<anonymous>)
    at step (file:///C:/Users/raytim/.atom/packages/platformio-ide/lib/installer/helpers.js:156:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please remove `C:/Users/raytim/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
