### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ericonetto** [platformio/platformio-atom-ide#789]
Those versions bugs keep happening.
From time to time I have to clean the installation.  

Traceback (most recent call last):
  File "C:\Users\erico\.platformio\penv\Scripts\platformio-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\erico\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3038, in <module>
    @_call_aside
  File "c:\users\erico\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3022, in _call_aside
    f(*args, **kwargs)
  File "c:\users\erico\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 3051, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\erico\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 657, in _build_master
    ws.require(__requires__)
  File "c:\users\erico\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 971, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\erico\.platformio\penv\lib\site-packages\pkg_resources\__init__.py", line 857, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyserial!=3.3,<4,>=3' distribution was not found and is required by platformio

**Comment by ivankravets** [comment]
Please remove `c:\users\erico\.platformio\penv` folder and restart Atom. If it didn't help, please reopen an issue.
