### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by maruyama0314** [platformio/platformio-atom-ide#792]
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (/Users/maruyamatatsuya/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (/Users/maruyamatatsuya/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please restart Atom
