### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by pajoheji0909** [platformio/platformio-atom-ide#795]
Traceback (most recent call last):
  File "/home/parksh/.platformio/penv/bin/platformio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>

    @_call_aside
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside

    f(*args, **kwargs)
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set

    working_set = WorkingSet._build_master()
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master

    ws.require(__requires__)
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 969, in require

    needed = self.resolve(parse_requirements(requirements))
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in requires

    dm = self._dep_map
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2816, in _dep_map

    self.__dep_map = self._compute_dependencies()
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2825, in _compute_dependencies

    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2807, in _parsed_pkg_info

    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/parksh/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1862, in get_metadata

    raise KeyError("No metadata except PKG-INFO is available")
KeyError: 'No metadata except PKG-INFO is available'

**Comment by ivankravets** [comment]
Please remove `/home/parksh/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
