### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by frank3141** [platformio/platformio-atom-ide#798]
Error: Error: EPERM: operation not permitted, mkdir 'd:\Users\frank\.platformio\project-examples\espressif\esp32-espidf-storage-sdcard\lib'
    at ProjectExamplesStage.<anonymous> (file:///d:/Users/frank/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (d:\Users\frank\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
> operation not permitted

Is something with permissions?  Try to remove `d:\Users\frank\.platformio` and start again
