### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by rasw** [platformio/platformio-atom-ide#801]
Error: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\wilso_000\.atom\packages\platformio-ide\node_modules\mime-db\HISTORY.md'
    at Error (native)

    at C:\Users\wilso_000\.atom\packages\platformio-ide\lib\installer\ide.js:42:75
    at throw (<anonymous>)
    at step (C:\Users\wilso_000\.atom\packages\platformio-ide\lib\installer\ide.js:89:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please upgrade IDE manually via Atom > Settings > Updates
