### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by wubomagic** [platformio/platformio-atom-ide#813]
Error: Error: Error: Failed to download file http://dl.platformio.org/ide-data/platformio-examples.tar.gz: null
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/wub/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at throw (<anonymous>)
    at step (C:\Users\wub\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Fixed in latest 2.0.0-rc.1. Please upgrade our package in Atom.
