### ISSUE TITLE
InstallationManager: WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by Noobidoo** [platformio/platformio-atom-ide#815]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\noobs\.platformio\.cache-ide\tmp-15060nUGGF3U47PpY\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\noobs\.platformio\.cache-ide\tmp-15060nUGGF3U47PpY\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\noobs\.platformio\.cache-ide\tmp-15060nUGGF3U47PpY\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\noobs\.platformio\.cache-ide\tmp-15060nUGGF3U47PpY\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\noobs\.platformio\.cache-ide\tmp-15060nUGGF3U47PpY\virtualenv-14.0.6\virtualenv.py", line 743, in call_subprocess
    cwd=cwd, env=env)
  File "C:\Users\noobs\.platformio\python27\Lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\noobs\.platformio\python27\Lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
