### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by alekosdat** [platformio/platformio-atom-ide#818]
Error: Traceback (most recent call last):
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 995, in _process_result
    **ctx.params)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 80, in process_result
    maintenance.on_platformio_end(ctx, result)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 75, in on_platformio_end
    check_platformio_upgrade()
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 238, in check_platformio_upgrade
    update_core_packages(silent=True)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/core.py", line 90, in update_core_packages
    pm.update(name, requirements, only_check=only_check)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/core.py", line 52, in update
    result = PackageManager.update(self, *args, **kwargs)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 735, in update
    self.uninstall(pkg_dir, trigger_event=False)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py", line 672, in uninstall
    util.rmtree_(pkg_dir)
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 602, in rmtree_
    return rmtree(path, onerror=_onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/iterat/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 599, in _onerror
    os.chmod(name, stat.S_IWRITE)
OSError: [Errno 2] No such file or directory: '/home/iterat/.platformio/packages/tool-pioplus'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please remove `/home/iterat/.platformio/packages/tool-pioplus` folder if exists and restart IDE
