### ISSUE TITLE
InstallationManager: shutil.Error

### ISSUE THREAD

**Issue by brainey** [platformio/platformio-atom-ide#821]
Virtualenv Create: Traceback (most recent call last):
  File "/home/brainey/.platformio/.cache-ide/tmp-158208UPsVz9n4JtO/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/home/brainey/.platformio/.cache-ide/tmp-158208UPsVz9n4JtO/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/home/brainey/.platformio/.cache-ide/tmp-158208UPsVz9n4JtO/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/brainey/.platformio/.cache-ide/tmp-158208UPsVz9n4JtO/virtualenv-14.0.6/virtualenv.py", line 1101, in install_python

    copy_required_modules(home_dir, symlink)
  File "/home/brainey/.platformio/.cache-ide/tmp-158208UPsVz9n4JtO/virtualenv-14.0.6/virtualenv.py", line 1042, in copy_required_modules

    copyfile(filename, dst_filename, symlink)
  File "/home/brainey/.platformio/.cache-ide/tmp-158208UPsVz9n4JtO/virtualenv-14.0.6/virtualenv.py", line 348, in copyfile

    copyfileordir(src, dest, symlink)
  File "/home/brainey/.platformio/.cache-ide/tmp-158208UPsVz9n4JtO/virtualenv-14.0.6/virtualenv.py", line 325, in copyfileordir

    shutil.copy2(src, dest)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))

shutil.Error: `/usr/lib/python2.7/abc.py` and `/home/brainey/.platformio/penv/lib/python2.7/abc.py` are the same file

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
