### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by darmandovargas** [platformio/platformio-atom-ide#842]
Error: Error: Error: Failed to download file http://dl.platformio.org/ide-data/platformio-examples.tar.gz: null
    at ProjectExamplesStage.<anonymous> (/Users/Diego/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at Generator.throw (<anonymous>)
    at step (/Users/Diego/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Fixed in latest 2.0.0-rc.1. Please upgrade our package in Atom.
