### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ronymaychan** [platformio/platformio-atom-ide#848]
Traceback (most recent call last):
File "C:\Users\rmay\.platformio\packages\_tmp_installing-hnrqwk-package\script\scons", line 190, in <module>

import SCons.Script
File "C:\Users\rmay\.platformio\packages\_tmp_installing-hnrqwk-package\script\..\engine\SCons\Script\__init__.py", line 75, in <module>
import SCons.Action
ImportError: No module named Action

 [ERROR] Took 0.81 seconds 

Environment uno   	[ERROR]

 [ERROR] Took 0.81 seconds

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/826
