### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by 18073117401** [platformio/platformio-atom-ide#850]
Traceback (most recent call last):
File "C:\Users\Administrator\.platformio\packages\tool-scons\script\scons", line 190, in <module>

import SCons.Script
File "C:\Users\Administrator\.platformio\packages\tool-scons\script\..\engine\SCons\__init__.py", line 43, in <module>
import SCons.compat
ImportError: No module named compat

 [ERROR] Took 0.36 seconds

**Comment by perfessor101** [comment]
reinstalled ... installed via python ... updated anything and everything ... pythonIO hasn't been working for me in months

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/826
