### ISSUE TITLE
InstallationManager: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by dmallo** [platformio/platformio-atom-ide#854]
Virtualenv Create: Traceback (most recent call last):
  File "/Users/dmallo/.platformio/.cache-ide/tmp-842916IqJPywFA35L/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>

    main()
  File "/Users/dmallo/.platformio/.cache-ide/tmp-842916IqJPywFA35L/virtualenv-14.0.6/virtualenv.py", line 705, in main

    symlink=options.symlink)
  File "/Users/dmallo/.platformio/.cache-ide/tmp-842916IqJPywFA35L/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/dmallo/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/Users/dmallo/.platformio/penv/bin/../lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
