### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by juan11perez** [platformio/platformio-atom-ide#856]
Error: Traceback (most recent call last):
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func

    return f(get_current_context(), *args, **kwargs)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 39, in __init__
    self._gather_tplvars()
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 152, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 135, in __call__
    value = self.func(*args)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py", line 74, in get_project_build_data
    target=["idedata"])
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 109, in cli
    result = (envname, ep.process())
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 193, in process
    result = self._run()
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/commands/run.py", line 287, in _run
    p = PlatformFactory.newPlatform(self.options['platform'])
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py", line 212, in newPlatform
    name, requirements)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 308, in get_package_dir
    manifest = self.get_package(name, requirements, url)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 278, in get_package
    for manifest in self.get_installed():
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 268, in get_installed
    manifest = self.load_manifest(pkg_dir)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 232, in load_manifest
    src_manifest_path = self.get_src_manifest_path(pkg_dir)
  File "/Users/Juan/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py", line 203, in get_src_manifest_path
    for item in os.listdir(pkg_dir):
OSError: [Errno 13] Permission denied: '/Users/Juan/.platformio/platforms/espressif8266'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please remove `/Users/Juan/.platformio` folder and restart Atom

**Comment by juan11perez** [comment]
Thank you 


Juan Perez
-------- Original message --------From: Ivan Kravets <notifications@github.com> Date: 06/09/2017  16:34  (GMT+04:00) To: platformio/platformio-atom-ide <platformio-atom-ide@noreply.github.com> Cc: juan11perez <juan11perez@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [platformio/platformio-atom-ide] C/C++ project index rebuild failed (#856) 
Please remove /Users/Juan/.platformio folder and restart Atom

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/platformio/platformio-atom-ide","title":"platformio/platformio-atom-ide","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/platformio/platformio-atom-ide"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ivankravets in #856: Please remove `/Users/Juan/.platformio` folder and restart Atom"}],"action":{"name":"View Issue","url":"https://github.com/platformio/platformio-atom-ide/issues/856#issuecomment-327469130"}}}
