### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by evertongodoy** [platformio/platformio-atom-ide#862]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Everton Godoy\.platformio\.cache-ide\tmp-8696h1TXVzaek6Ka\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Everton Godoy\.platformio\.cache-ide\tmp-8696h1TXVzaek6Ka\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Everton Godoy\.platformio\.cache-ide\tmp-8696h1TXVzaek6Ka\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\Everton Godoy\.platformio\.cache-ide\tmp-8696h1TXVzaek6Ka\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\Lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\EVERTO~1\\PLATFO~1\\penv\\Scripts\\python.exe'

**Comment by evertongodoy** [comment]
Reiniciei o windows e ao abrir o ATOM, funcionou normalmente.
I rebooted windows and when I opened the ATOM, it worked normally.
