### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ajennings6767** [platformio/platformio-atom-ide#866]
New to this so cut me some slack. Here is the error:

Error: Error: Error: Failed to download file http://dl.platformio.org/ide-data/platformio-examples.tar.gz: Error: EPERM: operation not permitted, open 'C:\Users\XBBL3NZ\.platformio\.cache-ide\examples.tar.gz'
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/XBBL3NZ/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:158:13)
    at Generator.throw (<anonymous>)
    at step (C:\Users\XBBL3NZ\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

Think this is likely due to corporate firewall or something of the like. Is there are workaround?

**Comment by ivankravets** [comment]
Fixed in latest 2.0.0-rc.1. Please upgrade our package in Atom.
