### ISSUE TITLE
Uncaught SyntaxError: Unexpected token : in JSON at position 3

### ISSUE THREAD

**Issue by profra** [platformio/platformio-atom-ide#872]
[Enter steps to reproduce:]

1. Atom upgrade to last version 1.19.3.
2. ... after restart this issue...

**Atom**: 1.19.3 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide](https://github.com/platformio/platformio-atom-ide) package 2.0.0-beta.8

### Stack Trace

Uncaught SyntaxError: Unexpected token : in JSON at position 3

```
At file:///C:/Users/fp.CHG/AppData/Local/atom/app-1.19.3/resources/app/static/index.html:1

SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at /packages/platformio-ide/lib/installer/ide.js:81:65
    at Request._callback (/packages/platformio-ide/lib/utils.js:184:12)
    at Request.self.callback (/packages/platformio-ide/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/platformio-ide/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/platformio-ide/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:10.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
dbg 1.6.1 
dbg-gdb 1.7.6 
file-icons 2.1.11 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.7 
linter-write-good 0.9.0 
minimap 4.29.6 
output-panel 0.3.4 
platformio-ide 2.0.0-beta.8 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.5.5 
Pymakr 1.0.3 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment]
Could you upgrade to PIO IDE 2.0.0-rc.1 . Does it work?

**Comment by ivankravets** [comment]
Please reopen if you still need help
