### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by WerWolv98** [platformio/platformio-atom-ide#873]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Nikolaij\.platformio\.cache-ide\tmp-2264ykAcbiv2NPfY\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Nikolaij\.platformio\.cache-ide\tmp-2264ykAcbiv2NPfY\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Nikolaij\.platformio\.cache-ide\tmp-2264ykAcbiv2NPfY\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\Nikolaij\.platformio\.cache-ide\tmp-2264ykAcbiv2NPfY\virtualenv-14.0.6\virtualenv.py", line 1223, in install_python
    shutil.copyfile(pythondll, os.path.join(os.path.dirname(py_executable), py_executable_dll))
  File "C:\Users\Nikolaij\.platformio\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\Nikolaij\\.platformio\\penv\\Scripts\\python27.dll'

**Comment by ivankravets** [comment]
Please remove `'C:\Users\Nikolaij\.platformio` folder and restart Atom
