### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gallochri** [platformio/platformio-atom-ide#877]
PIP: Exception:
Traceback (most recent call last):
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/distro.py", line 594, in __init__
    if include_lsb else {}
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/distro.py", line 933, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout)
CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 2

Traceback (most recent call last):
  File "/home/gallochri/.platformio/penv/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/__init__.py", line 233, in main

    return command.main(cmd_args)
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/basecommand.py", line 251, in main
    timeout=min(5, options.timeout)) as session:
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/distro.py", line 1050, in <module>

    _distro = LinuxDistribution()
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/distro.py", line 594, in __init__

    if include_lsb else {}
  File "/home/gallochri/.platformio/penv/lib/python2.7/site-packages/pip/_vendor/distro.py", line 933, in _get_lsb_release_info

    raise subprocess.CalledProcessError(code, cmd, stdout)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 2

**Comment by gallochri** [comment]
In openSUSE Tumbleweed fresh install missing " at the end of the string in /etc/lsb-release
