### ISSUE TITLE
ImportError: cannot import name LockFile

### ISSUE THREAD

**Issue by huangguozhen** [platformio/platformio-atom-ide#881]
when i click PlatformIO Debug. It show
OS: Ubuntu 14.04
```
Traceback (most recent call last):
  File "main.py", line 12, in init main (/tmp/tmpYeU6r8/main.c:3313)
  File "/home/zhen/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 25, in <module>
    from lockfile import LockFailed, LockFile
ImportError: cannot import name LockFile
```
System info:
- echo $PYTHONPATH
```null```
- python --version
```Python 2.7.6```
- pip --version
```pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)```
- pip list
```
adium-theme-ubuntu (0.3.4)
ansible (2.3.2.0)
appdirs (1.4.3)
apt-xapian-index (0.45)
arrow (0.10.0)
asn1crypto (0.22.0)
bcrypt (3.1.3)
boto (2.48.0)
bottle (0.12.13)
certifi (2017.7.27.1)
cffi (1.10.0)
chardet (2.0.1)
click (6.7)
command-not-found (0.3)
cryptography (2.0.3)
debtagshw (0.1)
defer (1.0.6)
dirspec (13.10)
duplicity (0.6.23)
enum34 (1.1.6)
httplib2 (0.8)
idna (2.6)
ipaddress (1.0.18)
Jinja2 (2.7.2)
lockfile (0.8)
lxml (3.3.3)
MarkupSafe (0.18)
ndg-httpsclient (0.4.2)
oauthlib (0.6.1)
oneconf (0.3.7.14.4.1)
packaging (16.8)
PAM (0.4.2)
paramiko (1.10.1)
pexpect (3.1)
Pillow (2.3.0)
pip (9.0.1)
piston-mini-client (0.7.5)
platformio (3.4.1)
pyasn1 (0.3.2)
pycparser (2.18)
pycrypto (2.6.1)
pycups (1.9.66)
pygobject (3.12.0)
PyNaCl (1.1.2)
pyOpenSSL (0.13)
pyparsing (2.2.0)
pypng (0.0.18)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu2)
python-dateutil (2.6.1)
python-debian (0.1.21-nmu2ubuntu2)
pyxdg (0.25)
PyYAML (3.10)
qrcode (5.3)
redis (2.10.6)
reportlab (3.0)
requests (2.2.1)
schedule (0.4.3)
semantic-version (2.6.0)
sessioninstaller (0.0.0)
setuptools (3.3)
shadowsocks (2.8.2)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
system-service (0.1.6)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
Werkzeug (0.12.2)
xdiagnose (3.6.3build2)
zope.interface (4.0.5)
```

**Comment by huangguozhen** [comment]
fixed by
```
sudo apt-get remove python-lockfile
pip install -U lockfile
```
