### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ompurwar** [platformio/platformio-atom-ide#886]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: read ECONNRESET
    at file:///D:/Users/hello/.atom/packages/platformio-ide/lib/installer/helpers.js:49:9
    at Generator.throw (<anonymous>)
    at step (file:///D:/Users/hello/.atom/packages/platformio-ide/lib/installer/helpers.js:156:2)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

**Comment by ivankravets** [comment]
Internet connection? try to restart Atom
