### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by EAmgarten** [platformio/platformio-atom-ide#894]
Error: Traceback (most recent call last):
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 104, in main
    cli(None, None, None)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 74, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 67, in on_platformio_start
    after_upgrade(ctx)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 191, in after_upgrade
    if u.run(ctx):
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 112, in run
    result.append(callback(ctx))
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 155, in _update_dev_platforms
    ctx.invoke(cmd_platform_update)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py", line 376, in platform_update
    platform, only_packages=only_packages, only_check=only_check)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py", line 115, in update
    p = PlatformFactory.newPlatform(pkg_dir)
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py", line 202, in newPlatform
    if isdir(name):
  File "/Users/edersonamgarten/.platformio/penv/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Could you open PlatformIO IDE Terminal and type 
```
pio update
```

Does it work?

**Comment by ivankravets** [comment]
Please reopen if you still need help
