### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by chenmh86** [platformio/platformio-atom-ide#896]
Error: Cannot read property 'getReferenceTarget' of null

    at file:///C:/Users/77394/.atom/packages/platformio-ide/lib/installer/ide.js:58:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/77394/.atom/packages/platformio-ide/lib/installer/ide.js:177:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please upgrade manually: Atom > Settings > Updates
