### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by bondarevky** [platformio/platformio-atom-ide#917]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\Engineer Konstantin\.platformio\.cache\tmp-124205p5DZ5at2nLx\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\Engineer Konstantin\.platformio\.cache\tmp-124205p5DZ5at2nLx\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\Engineer Konstantin\.platformio\.cache\tmp-124205p5DZ5at2nLx\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\Engineer Konstantin\.platformio\.cache\tmp-124205p5DZ5at2nLx\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\Lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\ENGINE~1\\PLATFO~1\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please remove `C:\Users\Engineer Konstantin.platformio` folder and restart IDE
