### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by bbnipz** [platformio/platformio-atom-ide#924]
Error: Request for package information failed: connect EACCES 50.16.244.237:443

    at file:///C:/Users/A/.atom/packages/platformio-ide/lib/installer/ide.js:58:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/A/.atom/packages/platformio-ide/lib/installer/ide.js:177:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please check your internet connection
