### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ajvuik** [platformio/platformio-atom-ide#934]
Error: Error: ENOENT: no such file or directory, open 'C:\Users\Arjan\.atom\packages\platformio-ide\.cache\examples.tar.gz'
    at ProjectExamplesStage.<anonymous> (C:\Users\Arjan\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:201:15)
    at throw (<anonymous>)
    at step (C:\Users\Arjan\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Please uninstall current `platformio-ide` package in Atom and install the latest RC version

**Comment by ElderJoy** [comment]
Thank you for your support!
