### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by DIegs73** [platformio/platformio-atom-ide#938]
Traceback (most recent call last):
File "C:\Users\DIego-PC\.platformio\packages\tool-scons\script\scons", line 190, in <module>
import SCons.Script
File "C:\Users\DIego-PC\.platformio\packages\tool-scons\script\..\engine\SCons\__init__.py", line 43, in <module>
ImportError: No module named compat
 [ERROR] Took 0.46 seconds

**Comment by ivankravets** [comment]
Please remove `C:\Users\DIego-PC.platformio` folder and restart IDE
