### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by DIegs73** [platformio/platformio-atom-ide#939]
Traceback (most recent call last):
File "C:\Users\DIego-PC\.platformio\packages\tool-scons\script\scons", line 190, in <module>
import SCons.Script
File "C:\Users\DIego-PC\.platformio\packages\tool-scons\script\..\engine\SCons\__init__.py", line 43, in <module>
ImportError: No module named compat
 [ERROR] Took 0.50 seconds

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/938
