### ISSUE TITLE
Problem has been occured while installing PlatformIO IDE.

### ISSUE THREAD

**Issue by bbnipz** [platformio/platformio-atom-ide#941]
Error: Installing platformio-ide to C:\Users\A\.atom\packages failed
Request for package information failed: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80 (5 attempts) (ECONNRESET)

    at C:\Users\A\.atom\packages\platformio-ide\lib\installer\ide.js:66:84
    at Generator.throw (<anonymous>)
    at step (C:\Users\A\.atom\packages\platformio-ide\lib\installer\ide.js:89:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please uninstall/install `platformio-ide` extension
