### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by HBeserra** [platformio/platformio-atom-ide#942]
Error: Error: Failed to download file https://github.com/platformio/platformio-examples/tarball/master: 
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/herbe/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at throw (<anonymous>)
    at step (C:\Users\herbe\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/934
