### ISSUE TITLE
Problem has beenn occured while uprading PlatformIO IDE.

### ISSUE THREAD

**Issue by et84121** [platformio/platformio-atom-ide#950]
Error: undefined

    at utils.runAPMCommand.busyTitle (C:\Users\whale\.atom\packages\platformio-ide\lib\installer\ide.js:154:87)
    at onExit (C:\Users\whale\.atom\packages\platformio-ide\lib\utils.js:144:7)
    at exit (C:\Users\whale\.atom\packages\platformio-ide\lib\utils.js:159:14)
    at triggerExitCallback (C:\Users\whale\AppData\Local\atom\app-1.20.0\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\whale\AppData\Local\atom\app-1.20.0\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please uninstall `platformio-ide` package and install again

**Comment by ivankravets** [comment]
Please uninstall `platformio-ide` package and install again
