### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by juusechec** [platformio/platformio-atom-ide#956]
Error: Traceback (most recent call last):
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py", line 74, in cli
    maintenance.on_platformio_start(ctx, force, caller)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 44, in on_platformio_start
    after_upgrade(ctx)
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/platformio/maintenance.py", line 188, in after_upgrade
    app.clean_cache()
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/platformio/app.py", line 263, in clean_cache
    with ContentCache() as cc:
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/platformio/app.py", line 147, in __enter__
    self.delete()
  File "/home/jorge/.platformio/penv/lib/python2.7/site-packages/platformio/app.py", line 250, in delete
    with open(self._db_path, "w") as fp:
IOError: [Errno 2] No such file or directory: '/home/jorge/.platformio/.cache/db.data'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please remove `/home/jorge/.platformio/.cache` and restart IDE
