### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by srodg68** [platformio/platformio-atom-ide#959]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\brodg68\.platformio\.cache-ide\tmp-16032488gJMpzWvc2\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\brodg68\.platformio\.cache-ide\tmp-16032488gJMpzWvc2\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\brodg68\.platformio\.cache-ide\tmp-16032488gJMpzWvc2\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\brodg68\.platformio\.cache-ide\tmp-16032488gJMpzWvc2\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\brodg68\\.platformio\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please remove `C:\Users\brodg68\.platformio\penv` and restart IDE
