### ISSUE TITLE
ImportError: No module named compat

### ISSUE THREAD

**Issue by simonCor** [platformio/platformio-atom-ide#960]
Traceback (most recent call last):
File "/home/sschwarz/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
File "/home/sschwarz/.platformio/packages/tool-scons/script/../engine/SCons/__init__.py", line 43, in <module>
ImportError: No module named compat
========================== [ERROR] Took 0.36 seconds ==========================
Environment sonoff        	[ERROR]
========================== [ERROR] Took 0.36 seconds ==========================

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
