### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Eduardom13** [platformio/platformio-atom-ide#970]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 150.187.65.3:3128
    at _callee$ (/home/eduardo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2522:19)
    at tryCatch (/home/eduardo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:780:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/eduardo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1014:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/eduardo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:832:21)
    at step (/home/eduardo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2631:191)
    at /home/eduardo/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2631:402
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please check Internet connection and restart IDE
