### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by cjdg** [platformio/platformio-atom-ide#973]
Error: Error: Failed to download file examples.tar.gz
  at ProjectExamplesStage.<anonymous> (/home/cjdg/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:201:15)
  at Generator.throw (<anonymous>:null:null)
  at step (/home/cjdg/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:13:273)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/934
