### ISSUE TITLE
OError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by MarcusWolschon** [platformio/platformio-atom-ide#979]
After an automatic update, projects can no longer be build.

Access is denied.
Error: spawn platformio ENOENT

Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\mw2_7\.platformio\.cache\tmp-15400sWBBUSV7JfKu\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\mw2_7\.platformio\.cache\tmp-15400sWBBUSV7JfKu\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\mw2_7\.platformio\.cache\tmp-15400sWBBUSV7JfKu\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\mw2_7\.platformio\.cache\tmp-15400sWBBUSV7JfKu\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Users\mw2_7\.platformio\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\mw2_7\\.platformio\\penv\\Scripts\\python.exe'

**Comment by MarcusWolschon** [comment]
This is a German Windows 10.
The python.exe exists but can not be executed.
Even as admin user I have no permissions to even see the access permissions for that file.

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
