### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jygatech** [platformio/platformio-atom-ide#987]
Error: Error: Failed to download file examples.tar.gz
    at ProjectExamplesStage.<anonymous> (file:///C:/Users/Andre/.atom/packages/platformio-ide/lib/installer/stages/project-examples.js:148:13)
    at Generator.throw (<anonymous>)
    at step (C:\Users\Andre\.atom\packages\platformio-ide\lib\installer\stages\project-examples.js:13:273)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/934
