### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by vMeph** [platformio/platformio-atom-ide#993]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\vMeph\.platformio\.cache\tmp-9024txyi8Yi5283J\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\vMeph\.platformio\.cache\tmp-9024txyi8Yi5283J\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\vMeph\.platformio\.cache\tmp-9024txyi8Yi5283J\virtualenv-14.0.6\virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "C:\Users\vMeph\.platformio\.cache\tmp-9024txyi8Yi5283J\virtualenv-14.0.6\virtualenv.py", line 1197, in install_python
    shutil.copyfile(executable, py_executable)
  File "C:\Users\vMeph\.platformio\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'C:\\Users\\vMeph\\.platformio\\penv\\Scripts\\python.exe'

**Comment by ivankravets** [comment]
Please remove `C:\Users\vMeph\.platformio\penv` and restart IDE
