### ISSUE TITLE
Problem has been occured while installing PlatformIO IDE.

### ISSUE THREAD

**Issue by migromao** [platformio/platformio-atom-ide#998]
Error: Cloning https://github.com/platformio/platformio-atom-ide.git failed
Installing modules done
Cannot read property 'getReferenceTarget' of null

    at C:\Users\Miguel Romão\.atom\packages\platformio-ide\lib\installer\ide.js:66:84
    at Generator.throw (<anonymous>)
    at step (C:\Users\Miguel Romão\.atom\packages\platformio-ide\lib\installer\ide.js:89:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please remove `C:\Users\Miguel Romão\.atom\packages\platformio-ide` and navigate to Atom > Settings > Install. Search for `platformio-ide` and install it
